"""The host-kernel sandbox a gate run executes under.

The last isolation the gate has that is enforced by the kernel rather than by
agreement. The prefix makes the source private; this makes "the gate fetched
nothing mid-run" checkable instead of believed -- and it is the only mechanism
here that a mistake in the gate's own code cannot talk its way past. macOS uses
Seatbelt. Linux uses Bubblewrap to enter a network namespace with loopback but
no external interface while preserving the filesystem and AF_UNIX sockets.

Shaped by measurement, not by preference. `(deny default)` widened by
enumerated allows was tried and abandoned: every read list produced a silent
`SIGABRT` -- exit 134, no stdout, no stderr -- and the kernel's denial log
needs sudo to read, so each iteration cost a rebuild to learn nothing. The
viable shape is `(allow default)` narrowed by targeted denials. That is also
where the value is: every failure this work chased was a write, a link or a
fetch, and denying reads buys little for a great deal of undiagnosable
debugging.

Two facts that are easy to get wrong and expensive to rediscover:

  `(deny network*)` denies **UNIX-domain sockets** as well as the internet.
  Without an explicit allow, the first sandboxed run looks exactly like
  "Docker isn't running" -- `permission denied ... docker.sock`.

  Apple Virtualization.framework works under it. A real VM booted and ran a
  guest command with the network denied, needing no `iokit-open` allow and no
  mach-lookup enumeration, and the sandbox provably reached the per-VM child:
  denying only that child's socket produced `capsem_process: Operation not
  permitted` while the daemon stayed up.
"""

from __future__ import annotations

import os
import shutil
import socket
import subprocess
import sys
from enum import StrEnum
from pathlib import Path

from . import host
from .config import GateConfig
from .errors import GateError

#: SBPL's own comment marker, so a generated profile can explain itself to
#: whoever reads it out of a failed run's directory.
_COMMENT = ";;"

class SandboxMode(StrEnum):
    """The closed set of host-kernel boundary policies a command may declare."""

    OFF = "off"
    REPORT = "report"
    ENFORCE = "enforce"


OFF, REPORT, ENFORCE = SandboxMode


def prepare_egress(config: GateConfig) -> None:
    """Create the one-time release capability before entering the sandbox."""
    from . import egress

    metadata = egress.prepare(config, config.path(config.runlog.root))
    os.environ[config.sandbox.egress_metadata_variable] = str(metadata)


def reexec(
    config: GateConfig,
    runner,
    *,
    default: SandboxMode,
    requested: SandboxMode | None,
    outside_egress: bool = False,
):
    """The current gate invocation under its declared kernel boundary."""
    chosen = mode(default, requested)
    if chosen == OFF or active(config):
        return None
    if outside_egress:
        prepare_egress(config)
    return applied(
        config,
        runner,
        default=chosen,
        requested=None,
        argv=(sys.executable, "-m", "capsem.gate", *sys.argv[1:]),
    )


def profile(config: GateConfig, *, report: bool) -> str:
    """The profile text for this run.

    `report` is the difference between measuring and enforcing. In report mode
    every rule still matches and nothing is refused, so one gate run yields the
    complete list of what the gate actually reaches for -- instead of forty
    runs each discovering one more thing at a different minute.
    """
    settings = config.sandbox
    lines = [
        "(version 1)",
        f"{_COMMENT} Generated by capsem.gate.sandbox. Every rule below comes",
        f"{_COMMENT} from [sandbox] in config/gate.toml; none is written here.",
        "(allow default)",
        f"{_COMMENT} {settings.network_reason}",
    ]

    if report:
        # `(with report)` is a modifier on *allow*, not on deny -- `sandbox-exec:
        # report modifier does not apply to deny action`, and the run dies before
        # it starts. So measuring is "permit everything and log it", which is
        # also what makes one run enough: nothing is refused, so nothing stops
        # early and the list that comes back is complete.
        #
        # Last, and alone. A later rule wins in SBPL, so the specific socket
        # allows below would silence reporting for exactly the paths already
        # known -- and the ones worth learning about are the rest.
        lines.append("(allow network* (with report))")
        return "\n".join(lines) + "\n"

    lines.append("(deny network*)")
    lines.append(f"{_COMMENT} {settings.socket_reason}")
    for socket_path in _sockets(config):
        lines.append(f'(allow network* (literal "{socket_path}"))')
    for prefix in settings.local_socket_prefixes:
        lines.append(f'(allow network* (regex #"^{prefix}"))')
    # Unanchored: the workspace lives inside a per-run prefix, so its absolute
    # path is not known when this profile is written.
    for pattern in settings.local_socket_regexes:
        lines.append(f'(allow network* (regex #"{pattern}"))')
    if settings.local_binds:
        # The gate starts servers and talks to them. Binding and accepting on
        # a local address is not a fetch, which is the thing being denied.
        lines.append('(allow network-bind (local ip "*:*"))')
        lines.append('(allow network-inbound (local ip "*:*"))')
    for address in settings.loopback:
        lines.append(f'(allow network* (remote ip "{address}"))')

    return "\n".join(lines) + "\n"


def _sockets(config: GateConfig) -> tuple[str, ...]:
    """Every AF_UNIX path the run must still reach, `~` resolved.

    The Docker socket is the one that bites: it is a UNIX socket, `network*`
    covers those, and denying it makes a working daemon look absent.
    """
    return tuple(str(Path(path).expanduser()) for path in config.sandbox.sockets)


def mode(
    command_default: SandboxMode, requested: SandboxMode | None
) -> SandboxMode:
    """What this run uses: what was asked for, else what the command declares.

    A flag rather than only a declaration because report mode is a
    *measurement* -- the point is to run the ordinary gate and collect what it
    reached for, without editing the command to do it.
    """
    for value in (command_default, requested):
        if value is not None and not isinstance(value, SandboxMode):
            raise TypeError(f"expected SandboxMode enum, got {value!r}")
    return requested or command_default


def written_to(config: GateConfig, directory: Path, *, report: bool) -> Path:
    """Render the profile into `directory` and return where it landed.

    Kept rather than reconstructed: a profile rebuilt from config afterwards
    may not be the one that ran, and the question a refused run raises is
    always "what exactly was I refused by".

    It lands in the history root and not in the run's own directory, which is
    the one thing worth knowing here. The profile has to exist before the
    process that executes under it -- this is called from `reexec()`, above
    every resource -- and the run directory is allocated by the recording that
    starts inside that process. There is no run to put it in yet. The cost is
    that consecutive runs overwrite it, so it answers "the last run" rather
    than "that run"; `sandboxreport` writes its capture into the run directory
    precisely because, being a resource, it can.
    """
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / config.sandbox.profile_name
    target.write_text(profile(config, report=report), encoding="utf-8")
    return target


def wrap(config: GateConfig, written: Path, argv: tuple[str, ...]) -> tuple[str, ...]:
    """The same macOS command, under the Seatbelt profile at `written`.

    A wrapper rather than an in-process call, because a sandbox is inherited
    and irrevocable: applying it to this interpreter would sandbox the parent
    that has to reclaim the prefix afterwards. Same family as the keep-awake
    re-exec, and it has to happen in the same place -- before any resource is
    held, or the child waits out its own parent's machine lock.
    """
    return (config.sandbox.command, "-f", str(written), *argv)


def linux_wrap(config: GateConfig, argv: tuple[str, ...]) -> tuple[str, ...]:
    """The same Linux command in a loopback-only network namespace."""
    settings = config.sandbox
    if shutil.which(settings.linux_command) is None:
        raise GateError(
            f"Linux gate sandbox requires {settings.linux_command}; run bootstrap.sh"
        )
    return (settings.linux_command, *settings.linux_args, "--", *argv)


def active(config: GateConfig) -> bool:
    """Whether the kernel, rather than a forgeable marker, says we are inside.

    Trusting an environment variable here lets an operator (or inherited shell
    state) disable the only enforcement boundary by exporting one string. On
    macOS a nested Seatbelt application is refused. On Linux the property being
    claimed is checked directly: the kernel exposes only loopback interfaces.
    A host with that same effective boundary is already safe; a forged marker
    on an ordinary host still sees its external interface and cannot bypass the
    wrapper.
    """
    if host.on_macos():
        if shutil.which(config.sandbox.command) is None:
            raise GateError(f"macOS gate sandbox requires {config.sandbox.command}")
        probe = subprocess.run(
            [
                config.sandbox.command,
                "-p",
                "(version 1)(allow default)",
                "true",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if probe.returncode == 0:
            return False
        if "sandbox_apply" in probe.stderr and "Operation not permitted" in probe.stderr:
            return True
        raise GateError(
            "could not determine whether the macOS Seatbelt sandbox is active: "
            f"{probe.stderr.strip() or f'exit {probe.returncode}'}"
        )
    if host.on_linux():
        try:
            interfaces = {name for _index, name in socket.if_nameindex()}
        except OSError as error:
            raise GateError(f"cannot inspect Linux network interfaces: {error}") from error
        return interfaces == {"lo"}
    raise GateError(f"the gate sandbox does not support host system {host.system()!r}")


def applied(
    config: GateConfig,
    runner,
    *,
    default: SandboxMode,
    requested: SandboxMode | None,
    argv: tuple[str, ...],
) -> tuple[str, ...]:
    """`argv`, wrapped in this host's kernel sandbox, or unchanged when off.

    The whole decision in one place: which mode, where the profile is written,
    and whether to wrap at all. It lives here rather than on the command
    because the command's only job is to say *whether* it wants a sandbox --
    everything about what one is belongs to this module.
    """
    chosen = mode(default, requested)
    if chosen == OFF or active(config):
        return argv
    if host.on_linux():
        if chosen == REPORT:
            raise GateError(
                "Linux sandbox report mode is not implemented; use enforce for "
                "kernel-denied egress rather than claiming unobserved access"
            )
        runner.step("Running in the enforce Bubblewrap network namespace")
        return linux_wrap(config, argv)
    if not host.on_macos():
        raise GateError(f"the gate sandbox does not support host system {host.system()!r}")
    written = written_to(
        config, config.path(config.runlog.root), report=chosen == REPORT
    )
    runner.step(f"Running under the {chosen} sandbox profile at {written}")
    if chosen == REPORT:
        # Here and nowhere later. `log` refuses to run inside a sandbox, and
        # every line after this one executes inside the profile just written.
        # Imported locally: `sandboxreport` imports this module for `REPORT`.
        from . import sandboxreport

        sandboxreport.start_outside_the_sandbox(config, runner)
    return wrap(config, written, argv)
