"""The macOS sandbox profile a run executes under.

The last isolation the gate has that is enforced by the kernel rather than by
agreement. The prefix makes the source private; this makes "the gate fetched
nothing mid-run" checkable instead of believed -- and it is the only mechanism
here that a mistake in the gate's own code cannot talk its way past.

Shaped by measurement, not by preference. `(deny default)` widened by
enumerated allows was tried and abandoned: every read list produced a silent
`SIGABRT` -- exit 134, no stdout, no stderr -- and the kernel's denial log
needs sudo to read, so each iteration cost a rebuild to learn nothing. The
viable shape is `(allow default)` narrowed by targeted denials. That is also
where the value is: every failure this work chased was a write, a link or a
fetch, and denying reads buys little for a great deal of undiagnosable
debugging.

Two facts that are easy to get wrong and expensive to rediscover:

  `(deny network*)` denies **UNIX-domain sockets** as well as the internet.
  Without an explicit allow, the first sandboxed run looks exactly like
  "Docker isn't running" -- `permission denied ... docker.sock`.

  Apple Virtualization.framework works under it. A real VM booted and ran a
  guest command with the network denied, needing no `iokit-open` allow and no
  mach-lookup enumeration, and the sandbox provably reached the per-VM child:
  denying only that child's socket produced `capsem_process: Operation not
  permitted` while the daemon stayed up.
"""

from __future__ import annotations

from pathlib import Path

from .config import GateConfig

#: SBPL's own comment marker, so a generated profile can explain itself to
#: whoever reads it out of a failed run's directory.
_COMMENT = ";;"


def profile(config: GateConfig, *, report: bool) -> str:
    """The profile text for this run.

    `report` is the difference between measuring and enforcing. In report mode
    every rule still matches and nothing is refused, so one gate run yields the
    complete list of what the gate actually reaches for -- instead of forty
    runs each discovering one more thing at a different minute.
    """
    settings = config.sandbox
    modifier = " (with report)" if report else ""
    lines = [
        "(version 1)",
        f"{_COMMENT} Generated by capsem.gate.sandbox. Every rule below comes",
        f"{_COMMENT} from [sandbox] in config/gate.toml; none is written here.",
        "(allow default)",
    ]

    lines.append(f"{_COMMENT} {settings.network_reason}")
    lines.append(f"(deny network*{modifier})")

    lines.append(f"{_COMMENT} {settings.socket_reason}")
    for socket in _sockets(config):
        lines.append(f'(allow network* (literal "{socket}"))')
    for prefix in settings.local_socket_prefixes:
        lines.append(f'(allow network* (regex #"^{prefix}"))')
    for address in settings.loopback:
        lines.append(f'(allow network* (remote ip "{address}"))')

    return "\n".join(lines) + "\n"


def _sockets(config: GateConfig) -> tuple[str, ...]:
    """Every AF_UNIX path the run must still reach, `~` resolved.

    The Docker socket is the one that bites: it is a UNIX socket, `network*`
    covers those, and denying it makes a working daemon look absent.
    """
    return tuple(str(Path(path).expanduser()) for path in config.sandbox.sockets)


def wrap(config: GateConfig, written: Path, argv: tuple[str, ...]) -> tuple[str, ...]:
    """The same command, under the profile at `written`.

    A wrapper rather than an in-process call, because a sandbox is inherited
    and irrevocable: applying it to this interpreter would sandbox the parent
    that has to reclaim the prefix afterwards. Same family as the keep-awake
    re-exec, and it has to happen in the same place -- before any resource is
    held, or the child waits out its own parent's machine lock.
    """
    return (config.sandbox.command, "-f", str(written), *argv)
