"""The macOS sandbox profile a run executes under.

The last isolation the gate has that is enforced by the kernel rather than by
agreement. The prefix makes the source private; this makes "the gate fetched
nothing mid-run" checkable instead of believed -- and it is the only mechanism
here that a mistake in the gate's own code cannot talk its way past.

Shaped by measurement, not by preference. `(deny default)` widened by
enumerated allows was tried and abandoned: every read list produced a silent
`SIGABRT` -- exit 134, no stdout, no stderr -- and the kernel's denial log
needs sudo to read, so each iteration cost a rebuild to learn nothing. The
viable shape is `(allow default)` narrowed by targeted denials. That is also
where the value is: every failure this work chased was a write, a link or a
fetch, and denying reads buys little for a great deal of undiagnosable
debugging.

Two facts that are easy to get wrong and expensive to rediscover:

  `(deny network*)` denies **UNIX-domain sockets** as well as the internet.
  Without an explicit allow, the first sandboxed run looks exactly like
  "Docker isn't running" -- `permission denied ... docker.sock`.

  Apple Virtualization.framework works under it. A real VM booted and ran a
  guest command with the network denied, needing no `iokit-open` allow and no
  mach-lookup enumeration, and the sandbox provably reached the per-VM child:
  denying only that child's socket produced `capsem_process: Operation not
  permitted` while the daemon stayed up.
"""

from __future__ import annotations

from pathlib import Path

from .config import GateConfig

#: SBPL's own comment marker, so a generated profile can explain itself to
#: whoever reads it out of a failed run's directory.
_COMMENT = ";;"

#: The three modes, spelled once. `off` is the default because the profile
#: denies the network and most commands are short reads that gain nothing from
#: it; `report` measures without refusing; `enforce` refuses.
OFF, REPORT, ENFORCE = "off", "report", "enforce"


def profile(config: GateConfig, *, report: bool) -> str:
    """The profile text for this run.

    `report` is the difference between measuring and enforcing. In report mode
    every rule still matches and nothing is refused, so one gate run yields the
    complete list of what the gate actually reaches for -- instead of forty
    runs each discovering one more thing at a different minute.
    """
    settings = config.sandbox
    lines = [
        "(version 1)",
        f"{_COMMENT} Generated by capsem.gate.sandbox. Every rule below comes",
        f"{_COMMENT} from [sandbox] in config/gate.toml; none is written here.",
        "(allow default)",
        f"{_COMMENT} {settings.network_reason}",
    ]

    if report:
        # `(with report)` is a modifier on *allow*, not on deny -- `sandbox-exec:
        # report modifier does not apply to deny action`, and the run dies before
        # it starts. So measuring is "permit everything and log it", which is
        # also what makes one run enough: nothing is refused, so nothing stops
        # early and the list that comes back is complete.
        #
        # Last, and alone. A later rule wins in SBPL, so the specific socket
        # allows below would silence reporting for exactly the paths already
        # known -- and the ones worth learning about are the rest.
        lines.append("(allow network* (with report))")
        return "\n".join(lines) + "\n"

    lines.append("(deny network*)")
    lines.append(f"{_COMMENT} {settings.socket_reason}")
    for socket in _sockets(config):
        lines.append(f'(allow network* (literal "{socket}"))')
    for prefix in settings.local_socket_prefixes:
        lines.append(f'(allow network* (regex #"^{prefix}"))')
    for address in settings.loopback:
        lines.append(f'(allow network* (remote ip "{address}"))')

    return "\n".join(lines) + "\n"


def _sockets(config: GateConfig) -> tuple[str, ...]:
    """Every AF_UNIX path the run must still reach, `~` resolved.

    The Docker socket is the one that bites: it is a UNIX socket, `network*`
    covers those, and denying it makes a working daemon look absent.
    """
    return tuple(str(Path(path).expanduser()) for path in config.sandbox.sockets)


def mode(command_default: str, requested: str | None) -> str:
    """What this run uses: what was asked for, else what the command declares.

    A flag rather than only a declaration because report mode is a
    *measurement* -- the point is to run the ordinary gate and collect what it
    reached for, without editing the command to do it.
    """
    return requested or command_default


def written_to(config: GateConfig, directory: Path, *, report: bool) -> Path:
    """Render the profile into `directory` and return where it landed.

    Kept rather than reconstructed: a profile rebuilt from config afterwards
    may not be the one that ran, and the question a refused run raises is
    always "what exactly was I refused by".

    It lands in the history root and not in the run's own directory, which is
    the one thing worth knowing here. The profile has to exist before the
    process that executes under it -- this is called from `reexec()`, above
    every resource -- and the run directory is allocated by the recording that
    starts inside that process. There is no run to put it in yet. The cost is
    that consecutive runs overwrite it, so it answers "the last run" rather
    than "that run"; `sandboxreport` writes its capture into the run directory
    precisely because, being a resource, it can.
    """
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / config.sandbox.profile_name
    target.write_text(profile(config, report=report), encoding="utf-8")
    return target


def wrap(config: GateConfig, written: Path, argv: tuple[str, ...]) -> tuple[str, ...]:
    """The same command, under the profile at `written`.

    A wrapper rather than an in-process call, because a sandbox is inherited
    and irrevocable: applying it to this interpreter would sandbox the parent
    that has to reclaim the prefix afterwards. Same family as the keep-awake
    re-exec, and it has to happen in the same place -- before any resource is
    held, or the child waits out its own parent's machine lock.
    """
    return (config.sandbox.command, "-f", str(written), *argv)


def applied(
    config: GateConfig,
    runner,
    *,
    default: str,
    requested: str | None,
    argv: tuple[str, ...],
) -> tuple[str, ...]:
    """`argv`, wrapped in this run's profile, or unchanged when off.

    The whole decision in one place: which mode, where the profile is written,
    and whether to wrap at all. It lives here rather than on the command
    because the command's only job is to say *whether* it wants a sandbox --
    everything about what one is belongs to this module.
    """
    chosen = mode(default, requested)
    if chosen == OFF:
        return argv
    written = written_to(
        config, config.path(config.runlog.root), report=chosen == REPORT
    )
    runner.step(f"Running under the {chosen} sandbox profile at {written}")
    if chosen == REPORT:
        # Here and nowhere later. `log` refuses to run inside a sandbox, and
        # every line after this one executes inside the profile just written.
        # Imported locally: `sandboxreport` imports this module for `REPORT`.
        from . import sandboxreport

        sandboxreport.start_outside_the_sandbox(config, runner)
    return wrap(config, written, argv)
