#!/bin/bash
# Detect a package transaction launched by the installed capsem.service.

capsem_install_runs_inside_service() {
    local cgroup_file="${1:-/proc/self/cgroup}"
    [ -r "$cgroup_file" ] || return 1
    grep -Eq '(^|/)capsem[.]service($|/)' "$cgroup_file"
}
