use axum::{response::Html, Json};
use capsem_plugin_engine::ui::{validate_messages, A2uiServerMessage, Ui, A2UI_BASIC_CATALOG_ID};
use capsem_plugin_engine::ui_tools::{acceptance_program, run_tool_program, UiToolProgramResult};
use serde::{Deserialize, Serialize};

pub async fn preview_html() -> Html<String> {
    let html = std::fs::read_to_string("ui-preview/dist/index.html").unwrap_or_else(|_| {
        r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Capsem UI Preview</title>
  </head>
  <body>
    <main style="font-family: system-ui; max-width: 760px; margin: 48px auto;">
      <h1>Capsem UI Preview</h1>
      <p>Build the Svelte preview with <code>npm run ui:build</code>, then refresh.</p>
      <p>The Rust A2UI endpoint is available at <a href="/ui/spec/demo">/ui/spec/demo</a>.</p>
    </main>
  </body>
</html>
"#
        .to_owned()
    });
    Html(html)
}

pub async fn demo() -> Json<UiPreviewPayload> {
    let payload = demo_payload();
    for example in &payload.examples {
        validate_messages(&example.messages)
            .expect("preview examples are generated by typed Rust helpers");
    }
    Json(payload)
}

pub async fn validate(Json(request): Json<ValidateUiRequest>) -> Json<ValidateUiResponse> {
    match validate_messages(&request.messages) {
        Ok(()) => Json(ValidateUiResponse {
            ok: true,
            error: None,
        }),
        Err(error) => Json(ValidateUiResponse {
            ok: false,
            error: Some(error),
        }),
    }
}

fn demo_payload() -> UiPreviewPayload {
    UiPreviewPayload {
        generated_by: "rust::capsem_plugin_engine::ui::Ui",
        catalog_id: A2UI_BASIC_CATALOG_ID,
        tool_acceptance: run_tool_program(acceptance_program()),
        examples: vec![
            UiPreviewExample::new(
                "Alert",
                r#"ui.alert(msg="Security review required")"#,
                "security",
                UiRecipe::new(
                    "alert",
                    "discovery",
                    "https://preline.co/docs/components/alerts.html#discovery",
                ),
                Ui::alert("preview-alert", "Security review required"),
            ),
            UiPreviewExample::new(
                "Ask Modal",
                r#"ui.ask(text="Allow this model call?", yes="Allow", no="Deny")"#,
                "interactive",
                UiRecipe::new(
                    "modal",
                    "basic",
                    "https://preline.co/docs/components/modal.html",
                ),
                Ui::ask("preview-ask", "Allow this model call?", "Allow", "Deny"),
            ),
            UiPreviewExample::new(
                "Card",
                r#"ui.card(title="A2UI Basic Card", description="Rendered through Preline card tokens.")"#,
                "component",
                UiRecipe::new(
                    "card",
                    "simple",
                    "https://preline.co/docs/components/card.html#simple-card",
                ),
                Ui::card(
                    "preview-card",
                    "A2UI Basic Card",
                    "Rendered through the Svelte/Preline Card pattern.",
                ),
            ),
            UiPreviewExample::new(
                "Status Callout",
                r#"ui.status_callout(title="A2UI Basic", msg="Composed, not invented.")"#,
                "status",
                UiRecipe::new(
                    "card",
                    "top-border",
                    "https://preline.co/docs/components/card.html",
                ),
                Ui::status_callout(
                    "preview-status",
                    "A2UI Basic",
                    "Composed from Card, Row, Icon, and Text.",
                ),
            ),
            UiPreviewExample::new(
                "Chat Baseline",
                "ui.chat_baseline()",
                "chat",
                UiRecipe::new(
                    "card",
                    "chat-baseline",
                    "https://preline.co/docs/components/card.html",
                ),
                Ui::chat_baseline("preview-chat"),
            ),
        ],
    }
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UiPreviewPayload {
    pub generated_by: &'static str,
    pub catalog_id: &'static str,
    pub tool_acceptance: UiToolProgramResult,
    pub examples: Vec<UiPreviewExample>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UiPreviewExample {
    pub name: &'static str,
    pub api: &'static str,
    pub surface: &'static str,
    pub recipe: UiRecipe,
    pub messages: Vec<A2uiServerMessage>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UiRecipe {
    pub component: &'static str,
    pub variant: &'static str,
    pub docs_url: &'static str,
}

impl UiRecipe {
    fn new(component: &'static str, variant: &'static str, docs_url: &'static str) -> Self {
        Self {
            component,
            variant,
            docs_url,
        }
    }
}

impl UiPreviewExample {
    fn new(
        name: &'static str,
        api: &'static str,
        surface: &'static str,
        recipe: UiRecipe,
        document: capsem_plugin_engine::ui::A2uiDocument,
    ) -> Self {
        Self {
            name,
            api,
            surface,
            recipe,
            messages: document.messages,
        }
    }
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidateUiRequest {
    pub messages: Vec<A2uiServerMessage>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidateUiResponse {
    pub ok: bool,
    pub error: Option<String>,
}
