"""Keep generated bytes out of source and converge repository output under target/."""

from __future__ import annotations

import ast
import hashlib
import re
import subprocess
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
POLICY = Path(__file__).with_name("generated_output_debt.toml")
SELF = "tests/citadel/test_generated_output_boundary.py"
POLICY_PATH = "tests/citadel/generated_output_debt.toml"

FINAL_OUTPUT_ROOTS = {
    "assets": "target/assets",
    "benchmarks": "target/test-benchmarks",
    "coverage": "target/coverage",
    "distribution": "target/distribution",
    "gate_runs": "target/gate-runs",
    "materialized_config": "target/config",
    "packages": "target/packages",
    "test_artifacts": "target/test-artifacts",
}

RATIONALE = """\
Repository-generated bytes belong under ignored target/ owners. Root assets,
packages, distribution, and failure evidence are temporary exact debt; they
must not become source, leak into the source digest, rely on ambient fallback,
or remain wired into CI after their producers move. See the target/ contract in
the approved repository cleanup proposal and config/README.md.
"""

PRODUCTION_ROOTS = (
    "src/",
    "scripts/",
    "build_system/builder/",
    ".github/",
    "config/",
    "release-site/",
)
AMBIENT_ROOTS = ("src/", "scripts/", "build_system/builder/")
PRODUCER_WORDS = re.compile(
    r"(?:\b(?:mkdir|cp|mv)\b|write(?:_text|_bytes)?\s*\(|"
    r"\bOUTPUT(?:_[A-Z]+)?\s*=|\bout(?:put)?[_-]?(?:dir|path|pkg)\s*=|"
    r"\bdestination\s*=)",
    re.IGNORECASE,
)
AMBIENT_WORDS = re.compile(
    r"(?:\bfallback\b|:-[^}\n]*assets\b|"
    r"default\s*=\s*(?:Path\()?['\"]assets['\"]|default:\s*assets\b)",
    re.IGNORECASE,
)
OLD_ROOT = re.compile(
    r"(?:"
    r"(?<![\w$/{.-])(?:assets|packages|dist|test-artifacts)/|"
    r"\.\./(?:assets|packages|dist|test-artifacts)/|"
    r"Path\(['\"](?:assets|packages|dist|test-artifacts)(?:/|['\"])|"
    r"repo_root\s*/\s*['\"](?:assets|packages|dist|test-artifacts)['\"]|"
    r"^\s*output\s*=\s*['\"](?:assets|packages|dist|test-artifacts)['\"]"
    r")"
)
CI_OLD_PATH = re.compile(
    r"^(?:assets/|packages/|dist/|test-artifacts/|frontend/test-artifacts/)",
)


@dataclass(frozen=True)
class Observed:
    producers: tuple[str, ...]
    ambient_assets: tuple[str, ...]
    ci_transfers: tuple[str, ...]
    tracked: tuple[str, ...]
    source_subject: tuple[str, ...]
    ignored_probes: frozenset[str]
    prefix_exports: tuple[str, ...]
    output_roots: dict[str, str]


def _git(*args: str, check: bool = True) -> list[str]:
    result = subprocess.run(
        ("git", *args),
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if check and result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout.splitlines()


def _digest(records: tuple[str, ...]) -> str:
    return hashlib.sha256("\0".join(sorted(records)).encode()).hexdigest()


def _text_sources(paths: list[str]) -> dict[str, str]:
    sources: dict[str, str] = {}
    for path in paths:
        if path in {SELF, POLICY_PATH} or path.startswith(("tests/", "sprints/", "tmp/")):
            continue
        candidate = ROOT / path
        if candidate.is_symlink() or not candidate.is_file():
            continue
        raw = candidate.read_bytes()
        if b"\0" in raw:
            continue
        try:
            sources[path] = raw.decode()
        except UnicodeDecodeError:
            continue
    return sources


def _producer_records(sources: dict[str, str]) -> tuple[str, ...]:
    records = [
        f"{path}:{line.strip()}"
        for path, text in sources.items()
        if path.startswith(PRODUCTION_ROOTS)
        for line in text.splitlines()
        if not line.lstrip().startswith(("#", "//", "*", "<!--", "`"))
        if OLD_ROOT.search(line)
        and PRODUCER_WORDS.search(line)
        and "http://" not in line
        and "https://" not in line
        and "/usr/" not in line
        and ".capsem/assets" not in line
        and not re.search(r"['\"]/assets/", line)
    ]
    return tuple(sorted(records))


def _ambient_asset_records(sources: dict[str, str]) -> tuple[str, ...]:
    records = [
        f"{path}:{line.strip()}"
        for path, text in sources.items()
        if path.startswith(AMBIENT_ROOTS)
        for line in text.splitlines()
        if not line.lstrip().startswith(("#", "//", "*", "<!--", "`"))
        if re.search(r"(?<!target/)assets(?:/|\b)", line)
        and AMBIENT_WORDS.search(line)
        and "http://" not in line
        and "https://" not in line
        and "/usr/" not in line
        and ".capsem/assets" not in line
        and "choices=" not in line
    ]
    return tuple(sorted(records))


def _ci_transfer_records() -> tuple[str, ...]:
    records: list[str] = []
    for path in _git("ls-files", ".github/workflows"):
        for line in (ROOT / path).read_text(encoding="utf-8").splitlines():
            stripped = line.strip().lstrip("- ")
            if stripped.startswith("path:"):
                stripped = stripped.removeprefix("path:").strip()
            if CI_OLD_PATH.match(stripped):
                records.append(f"{path}:{line.strip()}")
    return tuple(sorted(records))


def _prefix_exports() -> tuple[str, ...]:
    config = tomllib.loads((ROOT / "config/gate.toml").read_text(encoding="utf-8"))
    return tuple(config["prefix"]["exports"])


def _output_roots() -> dict[str, str]:
    config = tomllib.loads((ROOT / "config/gate.toml").read_text(encoding="utf-8"))
    return config.get("outputs", {})


def _gate_config() -> dict[str, Any]:
    return tomllib.loads((ROOT / "config/gate.toml").read_text(encoding="utf-8"))


def _literal_assignment(path: Path, name: str) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for statement in tree.body:
        if not isinstance(statement, ast.Assign):
            continue
        if any(isinstance(target, ast.Name) and target.id == name for target in statement.targets):
            expression = statement.value
            if (
                isinstance(expression, ast.Call)
                and isinstance(expression.func, ast.Name)
                and expression.func.id == "frozenset"
                and len(expression.args) == 1
                and not expression.keywords
            ):
                expression = expression.args[0]
            value = ast.literal_eval(expression)
            return set(value)
    raise AssertionError(f"{path}: missing literal assignment {name}")


def _observe(probes: list[str]) -> Observed:
    tracked = tuple(_git("ls-files"))
    sources = _text_sources(list(tracked))
    subject = tuple(_git("ls-files", "-co", "--exclude-standard"))
    ignored = frozenset(
        probe
        for probe in probes
        if subprocess.run(
            ("git", "check-ignore", "--quiet", "--", probe),
            cwd=ROOT,
            check=False,
        ).returncode
        == 0
    )
    return Observed(
        producers=_producer_records(sources),
        ambient_assets=_ambient_asset_records(sources),
        ci_transfers=_ci_transfer_records(),
        tracked=tracked,
        source_subject=subject,
        ignored_probes=ignored,
        prefix_exports=_prefix_exports(),
        output_roots=_output_roots(),
    )


def _tracked_generated_problems(
    tracked: tuple[str, ...], allowed_support: frozenset[str]
) -> list[str]:
    problems: list[str] = []
    for path in tracked:
        if path.startswith(("assets/", "packages/", "dist/", "test-artifacts/", "target/")):
            problems.append(f"tracked generated root byte: {path}")
        generated_name = ".generated." in Path(path).name
        generated_source = path.startswith(("src/", "config/", "build_system/")) and generated_name
        if generated_source and path not in allowed_support:
            problems.append(f"generated file in source/config root: {path}")
    return problems


def _problems(policy: dict[str, Any], observed: Observed) -> list[str]:
    problems: list[str] = []
    probes = tuple(policy.get("approved_output_probes", []))
    allowed_support = frozenset(policy.get("allowed_generated_support", []))
    if not probes or not allowed_support:
        problems.append("missing approved output/source-support surface")
    for field, records in (
        ("producer", observed.producers),
        ("ambient_asset", observed.ambient_assets),
        ("ci_transfer", observed.ci_transfers),
    ):
        expected_count = policy.get(f"{field}_count")
        expected_digest = policy.get(f"{field}_sha256")
        found_digest = _digest(records)
        if len(records) != expected_count or found_digest != expected_digest:
            problems.append(
                f"{field} debt: expected count={expected_count!r} sha256={expected_digest!r}; "
                f"found count={len(records)} sha256={found_digest}"
            )
    expected_exports = tuple(policy.get("prefix_exports", []))
    if observed.prefix_exports != expected_exports:
        problems.append(
            f"prefix exports: expected {expected_exports!r}, found {observed.prefix_exports!r}"
        )
    if observed.output_roots != FINAL_OUTPUT_ROOTS:
        problems.append(
            f"output roots: expected {FINAL_OUTPUT_ROOTS!r}, "
            f"found {observed.output_roots!r}"
        )
    problems.extend(_tracked_generated_problems(observed.tracked, allowed_support))
    unignored = sorted(set(probes) - observed.ignored_probes)
    if unignored:
        problems.append(f"approved output paths are not ignored: {unignored}")
    leaked = sorted(
        path
        for path in observed.source_subject
        if any(path == probe or path.startswith(str(Path(probe).parent) + "/") for probe in probes)
    )
    if leaked:
        problems.append(f"generated output leaked into source identity: {leaked}")
    return problems


def _synthetic(**changes: object) -> Observed:
    values: dict[str, object] = {
        "producers": (),
        "ambient_assets": (),
        "ci_transfers": (),
        "tracked": (),
        "source_subject": (),
        "ignored_probes": frozenset({"target/assets/.boundary-probe"}),
        "prefix_exports": (),
        "output_roots": FINAL_OUTPUT_ROOTS,
    }
    values.update(changes)
    return Observed(**values)  # type: ignore[arg-type]


def _synthetic_policy() -> dict[str, Any]:
    empty = hashlib.sha256(b"").hexdigest()
    return {
        "approved_output_probes": ["target/assets/.boundary-probe"],
        "allowed_generated_support": ["config/settings/schema.generated.json"],
        "producer_count": 0,
        "producer_sha256": empty,
        "ambient_asset_count": 0,
        "ambient_asset_sha256": empty,
        "ci_transfer_count": 0,
        "ci_transfer_sha256": empty,
        "prefix_exports": [],
    }


@pytest.mark.parametrize(
    ("observed", "message"),
    [
        (_synthetic(producers=("scripts/build.sh:mkdir -p packages/out",)), "producer debt"),
        (
            _synthetic(tracked=("target/assets/manifest.json",)),
            "tracked generated root byte",
        ),
        (
            _synthetic(tracked=("config/profiles/code/catalog.generated.json",)),
            "generated file in source/config root",
        ),
        (
            _synthetic(source_subject=("target/assets/manifest.json",)),
            "leaked into source identity",
        ),
        (
            _synthetic(ambient_assets=("scripts/build.py:default=Path('assets')",)),
            "ambient_asset debt",
        ),
        (
            _synthetic(ci_transfers=(".github/workflows/ci.yaml:path: test-artifacts/",)),
            "ci_transfer debt",
        ),
        (_synthetic(ignored_probes=frozenset()), "not ignored"),
        (_synthetic(output_roots={"assets": "assets"}), "output roots"),
    ],
)
def test_each_generated_output_violation_is_observed_red(
    observed: Observed, message: str
) -> None:
    assert any(message in problem for problem in _problems(_synthetic_policy(), observed)), (
        RATIONALE
    )


def test_empty_output_surface_fails_closed() -> None:
    assert any(
        "missing approved output" in problem for problem in _problems({}, _synthetic())
    ), RATIONALE


def test_producer_scanner_distinguishes_repository_roots() -> None:
    records = _producer_records(
        {
            "scripts/new.py": '\n'.join(
                (
                    'Path("assets/cache").mkdir(parents=True)',
                    'output_pkg = Path("../packages/Capsem.pkg")',
                    'Path("target/staging/assets/cache").mkdir(parents=True)',
                    'Path("/assets/container-cache").mkdir(parents=True)',
                    'Path("$CAPSEM_HOME/assets/manifest.json").write_text(data)',
                )
            )
        }
    )
    assert records == (
        'scripts/new.py:Path("assets/cache").mkdir(parents=True)',
        'scripts/new.py:output_pkg = Path("../packages/Capsem.pkg")',
    )


def test_ambient_scanner_distinguishes_path_defaults_from_asset_data() -> None:
    records = _ambient_asset_records(
        {
            "scripts/new.py": '\n'.join(
                (
                    'parser.add_argument("--assets", default=Path("assets"))',
                    'ASSETS_DIR="${CAPSEM_ASSETS_DIR:-$ROOT/assets}"',
                    'assets: list[Asset] = Field(default_factory=list)',
                    'parser.add_argument("--lane", choices=("assets",), default="assets")',
                )
            )
        }
    )
    assert records == (
        'scripts/new.py:ASSETS_DIR="${CAPSEM_ASSETS_DIR:-$ROOT/assets}"',
        'scripts/new.py:parser.add_argument("--assets", default=Path("assets"))',
    )


def test_non_rust_repository_asset_owners_use_the_canonical_target_root() -> None:
    policy = tomllib.loads(POLICY.read_text(encoding="utf-8"))
    observed = _observe(policy["approved_output_probes"])
    config = _gate_config()
    target = FINAL_OUTPUT_ROOTS["assets"]

    assert not [record for record in observed.producers if "assets" in record], RATIONALE
    assert not observed.ambient_assets, RATIONALE
    assert not [record for record in observed.ci_transfers if "assets/" in record], RATIONALE
    assert config["imagebuild"]["output"] == target
    assert config["service"]["assets_dir"] == target
    assert config["suites"]["pytest"]["test_manifest"] == f"{target}/manifest.json"
    assert config["functional"]["assets_dir"] == target
    assert config["package"]["generated_inputs"][0] == target
    assert target in config["prefix"]["lent"]
    assert target in config["prefix"]["exports"]
    assert "assets" not in config["prefix"]["lent"]
    assert "assets" not in config["prefix"]["exports"]


def test_native_package_owners_use_the_canonical_target_root() -> None:
    policy = tomllib.loads(POLICY.read_text(encoding="utf-8"))
    observed = _observe(policy["approved_output_probes"])
    config = _gate_config()
    target = FINAL_OUTPUT_ROOTS["packages"]
    workflow = (ROOT / ".github/workflows/release.yaml").read_text(encoding="utf-8")
    macos_builder = (
        ROOT / "build_system/packaging/macos/build-pkg.sh"
    ).read_text(encoding="utf-8")
    local_macos_builder = (
        ROOT / "build_system/packaging/macos/build-test-macos-package.sh"
    ).read_text(encoding="utf-8")

    assert not [
        record
        for record in observed.producers
        if "packages/Capsem" in record or "dist/*.deb" in record
    ], RATIONALE
    assert "dist_dir" not in config["package"]
    assert config["install"]["generated_inputs"] == [target]
    assert config["sbom"]["linux_packages_glob"] == "*{version}*.deb"
    assert config["sbom"]["macos_package_name"] == "Capsem-{version}.pkg"
    assert target in config["prefix"]["exports"]
    assert "dist" not in config["prefix"]["exports"]
    assert "packages" not in config["prefix"]["exports"]
    assert '"packages/Capsem-$VERSION.pkg"' not in workflow
    assert "cp dist/*.deb" not in workflow
    assert "target/packages/Capsem-$VERSION.pkg" in workflow
    assert "cp target/packages/*.deb" in workflow
    assert "/target/packages/Capsem-$VERSION.pkg" in macos_builder
    assert 'PKG="$ROOT/target/packages/Capsem-$VERSION.pkg"' in local_macos_builder


def test_test_evidence_and_coverage_use_canonical_target_roots() -> None:
    config = _gate_config()
    coverage = FINAL_OUTPUT_ROOTS["coverage"]
    evidence = FINAL_OUTPUT_ROOTS["test_artifacts"]
    workflow = (ROOT / ".github/workflows/ci.yaml").read_text(encoding="utf-8")
    release_workflow = (ROOT / ".github/workflows/release.yaml").read_text(
        encoding="utf-8"
    )
    storage = tomllib.loads(
        (ROOT / "config/storage-policy.toml").read_text(encoding="utf-8")
    )
    nextest = tomllib.loads(
        (ROOT / ".config/nextest.toml").read_text(encoding="utf-8")
    )
    linux_runner = (ROOT / "scripts/test-linux-rust.sh").read_text(encoding="utf-8")
    frontend_vitest = (ROOT / "frontend/vitest.config.ts").read_text(encoding="utf-8")
    release_vitest = (ROOT / "build_system/release_site/vitest.config.ts").read_text(
        encoding="utf-8"
    )
    conftest = (ROOT / "tests/conftest.py").read_text(encoding="utf-8")
    collector = (
        ROOT / "build_system/builder/release/tools/release_collect_evidence.py"
    ).read_text(encoding="utf-8")

    assert storage["debug_artifacts"]["root"] == evidence, RATIONALE
    assert {coverage, evidence} <= set(config["prefix"]["exports"]), RATIONALE
    assert config["hostimage"]["extract_to"] == f"{coverage}/linux", RATIONALE
    assert config["workspace"]["coverage_file"] == f"{coverage}/.coverage", RATIONALE
    assert config["workspace"]["evidence_dir"] == evidence, RATIONALE
    assert config["suites"]["pytest"]["coverage_flags"] == [
        "--cov=build_system/builder",
        f"--cov-report=xml:{coverage}/python/codecov.xml",
    ], RATIONALE
    assert nextest["store"]["dir"] == f"{coverage}/nextest", RATIONALE
    assert nextest["profile"]["ci-unit"]["inherits"] == "ci", RATIONALE
    assert nextest["profile"]["ci-integration"]["inherits"] == "ci", RATIONALE
    assert nextest["profile"]["ci-unit"]["junit"]["path"] == "junit.xml", RATIONALE
    assert nextest["profile"]["ci-integration"]["junit"]["path"] == "junit.xml", (
        RATIONALE
    )
    assert f'$ROOT/{coverage}/linux' in linux_runner, RATIONALE
    assert f"reportsDirectory: '../{coverage}/web-app'" in frontend_vitest, RATIONALE
    assert f"reportsDirectory: '../../{coverage}/distribution-site'" in release_vitest, RATIONALE
    assert "_GATE_CONFIG.outputs.test_artifacts" in conftest, RATIONALE
    assert f'Path("{evidence}") / "release"' in collector, RATIONALE

    required_ci_paths = {
        f"{coverage}/linux/codecov.json",
        f"{coverage}/linux/summary.txt",
        f"{coverage}/linux/nextest/ci/junit.xml",
        f"{coverage}/rust/unit.json",
        f"{coverage}/rust/integration.json",
        f"{coverage}/rust/summary.txt",
        f"{coverage}/python/codecov.xml",
        f"{coverage}/web-app/coverage-final.json",
        f"{coverage}/distribution-site/lcov.info",
        f"{coverage}/nextest/ci-unit/junit.xml",
        f"{coverage}/nextest/ci-integration/junit.xml",
        f"{coverage}/junit/frontend.xml",
        f"{coverage}/junit/python-cross-system.xml",
        f"{coverage}/junit/python-build-system.xml",
        f"{evidence}/",
    }
    assert not sorted(path for path in required_ci_paths if path not in workflow), RATIONALE
    assert f"{evidence}/" in release_workflow, RATIONALE
    for stale in (
        "frontend/test-artifacts/",
        "frontend/coverage/coverage-final.json",
        "build_system/release_site/coverage/lcov.info",
        "target/linux-rust-coverage",
        "target/nextest/ci/junit.xml",
    ):
        assert stale not in workflow, RATIONALE


def test_generated_output_transfer_and_cleanup_ownership_is_symmetric() -> None:
    config = _gate_config()
    exports = set(config["prefix"]["exports"])
    reclaimable = set(config["disk"]["reclaimable"])
    generated = set(FINAL_OUTPUT_ROOTS.values())

    assert exports == generated, RATIONALE
    protected = {
        FINAL_OUTPUT_ROOTS["assets"],
        FINAL_OUTPUT_ROOTS["materialized_config"],
        FINAL_OUTPUT_ROOTS["packages"],
    }
    assert generated - protected <= reclaimable, RATIONALE
    assert protected.isdisjoint(reclaimable), RATIONALE
    assert all(path.startswith("target/") for path in reclaimable), RATIONALE

    gitignore = {
        line.strip()
        for line in (ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    assert "target/" in gitignore, RATIONALE
    assert not {
        "test-artifacts/",
        "coverage/",
        ".coverage",
        "codecov-*.json",
        "codecov-*.xml",
        "*-junit.xml",
        "/assets",
        "/packages/",
        "/build_system/packaging/packages/",
    } & gitignore, RATIONALE
    assert "dist/" in gitignore, RATIONALE

    dockerignore = {
        line.strip()
        for line in (ROOT / ".dockerignore").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    assert "**/target" in dockerignore, RATIONALE
    assert not {"**/assets", "**/packages", "**/test-artifacts"} & dockerignore, (
        RATIONALE
    )
    assert "**/dist" in dockerignore, RATIONALE

    classifier = ROOT / "build_system/builder/gate/tools/ci/classify_ci_scope.py"
    retired = {"assets", "dist", "packages", "target", "test-artifacts"}
    assert retired.isdisjoint(_literal_assignment(classifier, "KNOWN_DIRECTORIES")), (
        RATIONALE
    )
    assert retired.isdisjoint(_literal_assignment(classifier, "RUST_GUEST_CONFIG_ROOTS")), (
        RATIONALE
    )


def test_current_generated_output_boundary_is_exact() -> None:
    policy = tomllib.loads(POLICY.read_text(encoding="utf-8"))
    assert policy.get("version") == 1
    problems = _problems(policy, _observe(policy["approved_output_probes"]))
    assert not problems, RATIONALE + "\n" + "\n".join(problems)
