//! Session id and time helpers shared by the service and its tools.

pub use capsem_foundation::time::epoch_to_iso;
use capsem_foundation::time::epoch_to_parts;

/// Generate a unique timestamp suffix for archival directories.
///
/// This is not the VM route ID. Runtime VM/session IDs are UUIDs generated by
/// the service registry.
pub fn generate_session_id() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let secs = now.as_secs();
    let (y, m, d, hours, minutes, seconds) = epoch_to_parts(secs);

    // 4 random hex chars from timestamp nanos + XOR with a counter.
    let nanos = now.subsec_nanos();
    let rand_bits = nanos ^ std::process::id().wrapping_mul(2654435761);
    let suffix = rand_bits & 0xFFFF;

    format!("{y:04}{m:02}{d:02}-{hours:02}{minutes:02}{seconds:02}-{suffix:04x}",)
}

/// Validate that a string looks like a valid session ID.
pub fn is_valid_session_id(s: &str) -> bool {
    // YYYYMMDD-HHMMSS-XXXX = 20 chars
    if s.len() != 20 {
        return false;
    }
    let bytes = s.as_bytes();
    // Check structure: 8 digits, dash, 6 digits, dash, 4 hex
    bytes[0..8].iter().all(|b| b.is_ascii_digit())
        && bytes[8] == b'-'
        && bytes[9..15].iter().all(|b| b.is_ascii_digit())
        && bytes[15] == b'-'
        && bytes[16..20].iter().all(|b| b.is_ascii_hexdigit())
}

/// Current UTC time as ISO 8601 string.
pub fn now_iso() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    epoch_to_iso(secs)
}
