"""Render the macOS Seatbelt profile from gate configuration."""

from __future__ import annotations

import os
import re
from pathlib import Path

from .config import GateConfig

#: SBPL's own comment marker, so a generated profile can explain itself to
#: whoever reads it out of a failed run's directory.
_COMMENT = ";;"


def profile(config: GateConfig, *, report: bool) -> str:
    """The profile text for this run.

    `report` is the difference between measuring and enforcing. In report mode
    every rule still matches and nothing is refused, so one gate run yields the
    complete list of what the gate actually reaches for -- instead of forty
    runs each discovering one more thing at a different minute.
    """
    settings = config.sandbox
    lines = [
        "(version 1)",
        f"{_COMMENT} Generated by capsem_builder.gate.sandbox. Every rule below comes",
        f"{_COMMENT} from [sandbox] in config/gate.toml; none is written here.",
        "(allow default)",
        f"{_COMMENT} {settings.network_reason}",
    ]

    if report:
        # `(with report)` is a modifier on *allow*, not on deny -- `sandbox-exec:
        # report modifier does not apply to deny action`, and the run dies before
        # it starts. So measuring is "permit everything and log it", which is
        # also what makes one run enough: nothing is refused, so nothing stops
        # early and the list that comes back is complete.
        #
        # Last, and alone. A later rule wins in SBPL, so the specific socket
        # allows below would silence reporting for exactly the paths already
        # known -- and the ones worth learning about are the rest.
        lines.append("(allow network* (with report))")
        return "\n".join(lines) + "\n"

    lines.append("(deny network*)")
    lines.append(f"{_COMMENT} {settings.socket_reason}")
    for socket_path in _sockets(config):
        lines.append(f'(allow network* (literal "{socket_path}"))')
    for prefix in settings.local_socket_prefixes:
        # Prefix punctuation is policy. ``Path`` normalizes a trailing slash
        # away, turning a configured ``/tmp/capsem/`` namespace into the
        # broader ``/tmp/capsem`` match (which also accepts arbitrary suffixes).
        expanded = os.path.expanduser(prefix)
        lines.append(f'(allow network* (regex #"^{re.escape(expanded)}"))')
    # Unanchored: the workspace lives inside a per-run prefix, so its absolute
    # path is not known when this profile is written.
    for pattern in settings.local_socket_regexes:
        lines.append(f'(allow network* (regex #"{pattern}"))')
    if settings.local_binds:
        # The gate starts servers and talks to them. Binding and accepting on
        # a local address is not a fetch, which is the thing being denied.
        lines.append('(allow network-bind (local ip "*:*"))')
        lines.append('(allow network-inbound (local ip "*:*"))')
    for address in settings.loopback:
        lines.append(f'(allow network* (remote ip "{address}"))')

    return "\n".join(lines) + "\n"


def _sockets(config: GateConfig) -> tuple[str, ...]:
    """Every AF_UNIX path the run must still reach, `~` resolved.

    The Docker socket is the one that bites: it is a UNIX socket, `network*`
    covers those, and denying it makes a working daemon look absent.
    """
    return tuple(str(Path(path).expanduser()) for path in config.sandbox.sockets)
