[settings."vm.environment.ssh.public_key"]
value = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBkujAwh+zwKM656FDYEuYdJcBCuMSxXDpTdCoz6PNMI"
modified = "2026-04-20T14:54:44Z"

[settings."repository.git.identity.author_name"]
value = "Elie Bursztein"
modified = "2026-04-20T14:54:44Z"

[settings."repository.git.identity.author_email"]
value = "github@elie.net"
modified = "2026-04-20T14:54:44Z"
