# Generated by scripts/generate-native-artifact-types.ts from schemas/capsem-ui/artifacts/native-artifact.v1.schema.json.
# Do not edit by hand.

from __future__ import annotations

from typing import Literal


NativeArtifactKind = Literal["generatedText", "generatedImage", "generatedEmbedding", "sheet", "table", "chart", "diagram", "timeline", "slide", "slideDeck"]

NATIVE_ARTIFACT_KINDS: tuple[str, ...] = ("generatedText", "generatedImage", "generatedEmbedding", "sheet", "table", "chart", "diagram", "timeline", "slide", "slideDeck",)

NATIVE_ARTIFACT_COMPONENTS: dict[str, str] = {
    "generatedText": "capsem-text",
    "generatedImage": "capsem-media",
    "generatedEmbedding": "capsem-embedding",
    "sheet": "capsem-sheet",
    "table": "capsem-table",
    "chart": "capsem-chart",
    "diagram": "capsem-diagram",
    "timeline": "capsem-timeline",
    "slide": "capsem-slide",
    "slideDeck": "capsem-slide-deck",
}

NATIVE_ARTIFACT_MEDIA: dict[str, str] = {
    "generatedText": "text",
    "generatedImage": "image",
    "generatedEmbedding": "embedding",
}

PLOTLY_CHART_KINDS: tuple[str, ...] = ("barChart", "lineChart", "heatmapChart", "boxPlot", "scatterPlot",)
PLOTLY_STACK_MODES: tuple[str, ...] = ("none", "stacked", "grouped",)
PLOTLY_DIRECTIONS: tuple[str, ...] = ("vertical", "horizontal",)
