import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const schemaPath = "schemas/capsem-ui/artifacts/native-artifact.v1.schema.json";
const tsPath = "ui-preview/src/generated/nativeArtifact.ts";
const pyPath = "python/capsem_native_client/generated_native_artifact.py";

type JsonObject = Record<string, unknown>;

const check = process.argv.includes("--check");

const schema = JSON.parse(await readFile(schemaPath, "utf8")) as JsonObject;
const schemaProperties = requiredObject(schema.properties, "properties");
const kindSchema = requiredObject(schemaProperties.kind, "properties.kind");
const kinds = requiredArray(kindSchema.enum, "properties.kind.enum").map(String);
const specs = Object.fromEntries(kinds.map((kind) => [kind, specForKind(schema, kind)]));
const generated = {
  [tsPath]: renderTypescript(kinds, specs),
  [pyPath]: renderPython(kinds, specs),
};

let failed = false;
for (const [target, content] of Object.entries(generated)) {
  if (check) {
    const current = await readFile(target, "utf8").catch(() => "");
    if (current !== content) {
      console.error(`${target} is out of date; run npm run generate:artifact-types`);
      failed = true;
    }
  } else {
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content);
  }
}

if (failed) process.exit(1);

type SpecInfo = {
  component: string;
  media?: string;
  chartValues?: string[];
  stackValues?: string[];
  directionValues?: string[];
  legendValues?: string[];
  exportValues?: string[];
};

function specForKind(schema: JsonObject, kind: string): SpecInfo {
  const clauses = requiredArray(schema.allOf, "allOf");
  for (const clause of clauses) {
    const object = requiredObject(clause, "allOf[]");
    const condition = requiredObject(object.if, "if");
    const properties = requiredObject(condition.properties, "if.properties");
    const kindSchema = requiredObject(properties.kind, "if.properties.kind");
    if (kindSchema.const !== kind) continue;
    const then = requiredObject(object.then, "then");
    const thenProperties = requiredObject(then.properties, "then.properties");
    const spec = requiredObject(thenProperties.spec, "then.properties.spec");
    const specProperties = requiredObject(spec.properties, "spec.properties");
    return {
      component: requiredConst(specProperties.component, `${kind}.component`),
      media: optionalConst(specProperties.media),
      chartValues: optionalEnum(specProperties.chart),
      stackValues: optionalEnum(specProperties.stack),
      directionValues: optionalEnum(specProperties.direction),
      legendValues: optionalEnum(specProperties.legend),
      exportValues: optionalItemsEnum(specProperties.export),
    };
  }
  throw new Error(`missing schema clause for ${kind}`);
}

function renderTypescript(kinds: string[], specs: Record<string, SpecInfo>): string {
  const q = (value: string) => JSON.stringify(value);
  return `// Generated by scripts/generate-native-artifact-types.ts from ${schemaPath}.
// Do not edit by hand.

export type NativeArtifactBase<K extends NativeArtifactKind, S extends NativeArtifactSpec> = {
  id: string;
  kind: K;
  title: string;
  handle: string;
  spec: S;
};

export type NativeArtifactKind = ${union(kinds)};

export type NativeArtifact =
${kinds.map((kind) => `  | NativeArtifactBase<${q(kind)}, ${specTypeName(kind)}>`).join("\n")};

export type NativeArtifactSpec =
${kinds.map((kind) => `  | ${specTypeName(kind)}`).join("\n")};

export type ArtifactSpecBase<C extends string> = {
  component: C;
  stylePatches?: unknown;
  textPatches?: unknown;
};

export type GeneratedTextSpec = ArtifactSpecBase<${q(specs.generatedText.component)}> & {
  media: ${q(specs.generatedText.media ?? "text")};
  provider: string;
  model?: string | null;
  system?: string | null;
  prompt: string;
  text?: string | null;
  usage?: unknown;
  cost?: unknown;
  durationMs?: number | null;
  status: string;
  error?: string | null;
};

export type GeneratedImageSpec = ArtifactSpecBase<${q(specs.generatedImage.component)}> & {
  media: ${q(specs.generatedImage.media ?? "image")};
  provider: string;
  model?: string | null;
  prompt: string;
  caption?: string | null;
  revisedPrompt?: string | null;
  dataUrl?: string | null;
  usage?: unknown;
  cost?: unknown;
  durationMs?: number | null;
  status: string;
  error?: string | null;
};

export type GeneratedEmbeddingSpec = ArtifactSpecBase<${q(specs.generatedEmbedding.component)}> & {
  media: ${q(specs.generatedEmbedding.media ?? "embedding")};
  provider: string;
  model?: string | null;
  input: string[];
  embedding?: unknown;
  usage?: unknown;
  cost?: unknown;
  durationMs?: number | null;
  status: string;
  error?: string | null;
};

export type JsonRow = Record<string, unknown>;

export type SheetSpec = ArtifactSpecBase<${q(specs.sheet.component)}> & {
  columns: string[];
  rows: JsonRow[];
  source?: unknown;
};

export type TableSpec = ArtifactSpecBase<${q(specs.table.component)}> & {
  sourceArtifact: string;
  columns: string[];
  rows: JsonRow[];
  searchable?: boolean;
  filterable?: boolean;
  pageSize: number;
};

export type PlotlyChartKind = ${union(specs.chart.chartValues ?? [])};
export type ChartStackMode = ${union(specs.chart.stackValues ?? [])};
export type ChartDirection = ${union(specs.chart.directionValues ?? [])};
export type LegendPosition = ${union((specs.chart.legendValues ?? []).filter((value) => value !== "null"))};

export type ChartSeriesSpec = {
  name: string;
  field: string;
  axis?: "left" | "right" | null;
};

export type ChartSpec = ArtifactSpecBase<${q(specs.chart.component)}> & {
  chart: PlotlyChartKind;
  sourceArtifact: string;
  data: JsonRow[];
  x: string;
  series: ChartSeriesSpec[];
  xLabel: string;
  xUnit?: string | null;
  yLabel: string;
  yUnit: string;
  stack?: ChartStackMode;
  direction?: ChartDirection;
  legend?: LegendPosition | null;
  secondAxis?: Record<string, unknown> | null;
  fit?: Record<string, unknown> | null;
  export?: Array<${union(specs.chart.exportValues ?? [])}>;
};

export type DiagramSpec = ArtifactSpecBase<${q(specs.diagram.component)}> & {
  kind: "mermaid";
  source: string;
  export?: Array<${union(specs.diagram.exportValues ?? [])}>;
};

export type TimelineLane = {
  id: string;
  title: string;
};

export type TimelineEvent = {
  id: string;
  title: string;
  lane: string;
  start: string;
  end?: string | null;
  description?: string | null;
};

export type TimelineSpec = ArtifactSpecBase<${q(specs.timeline.component)}> & {
  lanes: TimelineLane[];
  events: TimelineEvent[];
  export?: Array<${union(specs.timeline.exportValues ?? [])}>;
};

export type SlideBlock =
  | { kind: "text"; title: string; body: string }
  | { kind: "image"; artifactId: string }
  | { kind: "diagram"; artifactId: string }
  | { kind: "table"; artifactId: string }
  | { kind: "sheet"; artifactId: string }
  | { kind: "chart"; artifactId: string };

export type SlideSpec = ArtifactSpecBase<${q(specs.slide.component)}> & {
  blocks: SlideBlock[];
};

export type SlideDeckSpec = ArtifactSpecBase<${q(specs.slideDeck.component)}> & {
  slides: Array<{ artifactId: string; title: string }>;
  export?: Array<${union(specs.slideDeck.exportValues ?? [])}>;
};
`;
}

function renderPython(kinds: string[], specs: Record<string, SpecInfo>): string {
  return `# Generated by scripts/generate-native-artifact-types.ts from ${schemaPath}.
# Do not edit by hand.

from __future__ import annotations

from typing import Literal


NativeArtifactKind = Literal[${kinds.map((kind) => JSON.stringify(kind)).join(", ")}]

NATIVE_ARTIFACT_KINDS: tuple[str, ...] = (${kinds.map((kind) => JSON.stringify(kind)).join(", ")},)

NATIVE_ARTIFACT_COMPONENTS: dict[str, str] = {
${kinds.map((kind) => `    ${JSON.stringify(kind)}: ${JSON.stringify(specs[kind].component)},`).join("\n")}
}

NATIVE_ARTIFACT_MEDIA: dict[str, str] = {
${Object.entries(specs)
  .filter(([, spec]) => spec.media)
  .map(([kind, spec]) => `    ${JSON.stringify(kind)}: ${JSON.stringify(spec.media)},`)
  .join("\n")}
}

PLOTLY_CHART_KINDS: tuple[str, ...] = (${(specs.chart.chartValues ?? []).map((value) => JSON.stringify(value)).join(", ")},)
PLOTLY_STACK_MODES: tuple[str, ...] = (${(specs.chart.stackValues ?? []).map((value) => JSON.stringify(value)).join(", ")},)
PLOTLY_DIRECTIONS: tuple[str, ...] = (${(specs.chart.directionValues ?? []).map((value) => JSON.stringify(value)).join(", ")},)
`;
}

function specTypeName(kind: string): string {
  return `${kind[0].toUpperCase()}${kind.slice(1)}Spec`;
}

function union(values: string[]): string {
  return values.length ? values.map((value) => JSON.stringify(value)).join(" | ") : "never";
}

function requiredObject(value: unknown, name: string): JsonObject {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`${name} must be object`);
  }
  return value as JsonObject;
}

function requiredArray(value: unknown, name: string): unknown[] {
  if (!Array.isArray(value)) throw new Error(`${name} must be array`);
  return value;
}

function requiredConst(value: unknown, name: string): string {
  const object = requiredObject(value, name);
  if (typeof object.const !== "string") throw new Error(`${name}.const must be string`);
  return object.const;
}

function optionalConst(value: unknown): string | undefined {
  if (!value) return undefined;
  const object = requiredObject(value, "optional const");
  return typeof object.const === "string" ? object.const : undefined;
}

function optionalEnum(value: unknown): string[] | undefined {
  if (!value) return undefined;
  const object = requiredObject(value, "optional enum");
  const values = object.enum;
  if (!Array.isArray(values)) return undefined;
  return values.map((item) => (item === null ? "null" : String(item)));
}

function optionalItemsEnum(value: unknown): string[] | undefined {
  if (!value) return undefined;
  const object = requiredObject(value, "optional items enum");
  return optionalEnum(object.items);
}
