#!/usr/bin/env python3
"""Hermetic local release glow-up for the install test rail.

This script intentionally uses the same build commands as the release lane:

* a Tauri-built .deb is repacked by ``scripts/repack-deb.sh``;
* host binary SBOMs are generated by ``scripts/generate-host-binary-sbom.py``;
* binary metadata is recorded by ``capsem-admin assets channel record-binary``;
* release-channel manifests are generated by ``capsem-admin assets channel build``;
* ``site/public/install.sh`` installs from a local HTTP release channel;
* the installed CLI switches stable -> nightly -> stable through ``--channel``;
* an explicit corporate manifest locks the machine onto that corporate channel.

No hand-authored release manifest is created here.
"""

from __future__ import annotations

import argparse
import copy
import contextlib
from dataclasses import dataclass
import errno
import functools
import hashlib
import http.server
import json
import os
from pathlib import Path
import re
import shutil
import shlex
import socketserver
import subprocess
import sys
import threading
from typing import cast
import urllib.request
from urllib.parse import unquote, urljoin, urlparse

try:
    from release_glowup import (
        ArtifactIdentity,
        PairingIdentity,
        TransitionKind,
        artifact_identity_from_manifest_package,
        assert_manifest_artifact,
        build_report,
        build_transition_evidence,
        classify_pairing_inputs,
        tamper_profile_artifact_digest,
        validate_installed_evidence,
        validate_pairing_inputs,
    )
except ModuleNotFoundError:
    from scripts.release_glowup import (
        ArtifactIdentity,
        PairingIdentity,
        TransitionKind,
        artifact_identity_from_manifest_package,
        assert_manifest_artifact,
        build_report,
        build_transition_evidence,
        classify_pairing_inputs,
        tamper_profile_artifact_digest,
        validate_installed_evidence,
        validate_pairing_inputs,
    )

try:
    from release_inputs import load_verified_release_inputs, safe_relative, verify_payload
except ModuleNotFoundError:
    from scripts.release_inputs import (
        load_verified_release_inputs,
        safe_relative,
        verify_payload,
    )


PROJECT_ROOT = Path(__file__).resolve().parents[1]
HOST_BINARIES = (
    "capsem",
    "capsem-service",
    "capsem-process",
    "capsem-tui",
    "capsem-mcp",
    "capsem-mcp-aggregator",
    "capsem-mcp-builtin",
    "capsem-gateway",
    "capsem-tray",
    "capsem-admin",
    "capsem-mock-server",
)


@dataclass(frozen=True)
class ExactReleasePairing:
    channel: str
    transition: TransitionKind
    changed_profiles: tuple[str, ...]
    before: PairingIdentity
    after: PairingIdentity
    before_manifest: Path
    after_manifest: Path
    before_package: Path
    after_package: Path
    before_profile_inputs: Path
    after_profile_inputs: Path


@dataclass(frozen=True)
class ExactReleaseTransport:
    before_manifest: Path
    after_manifest: Path
    current_manifest: Path
    channel_catalog: Path
    before_manifest_url: str
    after_manifest_url: str
    current_manifest_url: str
    channel_catalog_url: str
    before_package: Path
    after_package: Path


@dataclass(frozen=True)
class ExactInstalledGlowupEvidence:
    fresh_installed: Path
    fresh_doctor: Path
    fresh_winterfell: Path
    candidate_installed: Path
    candidate_doctor: Path
    candidate_winterfell: Path
    tamper_rejection: Path
    incompatible_rejection: Path
    preserved_installed: Path
    preserved_doctor: Path
    preserved_winterfell: Path


@dataclass(frozen=True)
class AdversarialExactCandidates:
    tampered_manifest: Path
    incompatible_manifest: Path


def _environment_path(name: str) -> Path | None:
    value = os.environ.get(name)
    return Path(value) if value else None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-deb", required=True, type=Path)
    parser.add_argument("--bin-dir", required=True, type=Path)
    parser.add_argument("--assets-dir", required=True, type=Path)
    parser.add_argument("--config-root", required=True, type=Path)
    parser.add_argument(
        "--install-script", default=PROJECT_ROOT / "site/public/install.sh", type=Path
    )
    parser.add_argument(
        "--work-dir", default=PROJECT_ROOT / "target/local-release-glowup", type=Path
    )
    parser.add_argument("--skip-install", action="store_true")
    parser.add_argument(
        "--package-ready",
        action="store_true",
        help="Use an already repacked publishable package without rebuilding it.",
    )
    parser.add_argument(
        "--release-channel",
        choices=("stable", "nightly"),
        default=os.environ.get("CAPSEM_RELEASE_CHANNEL"),
    )
    parser.add_argument(
        "--release-transition",
        choices=(
            "auto",
            TransitionKind.BINARY_ONLY.value,
            TransitionKind.PROFILE_ONLY.value,
            TransitionKind.PROFILE_THEN_BINARY.value,
        ),
        default=os.environ.get("CAPSEM_RELEASE_TRANSITION"),
    )
    parser.add_argument(
        "--before-manifest",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_BEFORE_MANIFEST"),
    )
    parser.add_argument(
        "--after-manifest",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_AFTER_MANIFEST"),
    )
    parser.add_argument(
        "--before-package",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_BEFORE_PACKAGE"),
    )
    parser.add_argument(
        "--before-profile-inputs",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_BEFORE_PROFILE_INPUTS"),
    )
    parser.add_argument(
        "--after-profile-inputs",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_AFTER_PROFILE_INPUTS"),
    )
    parser.add_argument("--profile", default=os.environ.get("CAPSEM_RELEASE_PROFILE"))
    parser.add_argument(
        "--candidate-profile-publication",
        type=Path,
        default=_environment_path("CAPSEM_RELEASE_CANDIDATE_PROFILE_PUBLICATION"),
    )
    parser.add_argument(
        "--publication-base",
        default=os.environ.get("CAPSEM_RELEASE_PUBLICATION_BASE"),
    )
    args = parser.parse_args()
    exact_pairing = validate_exact_release_pairing(args)

    if args.work_dir.exists():
        shutil.rmtree(args.work_dir)
    args.work_dir.mkdir(parents=True)
    dist = args.work_dir / "dist"
    artifacts = args.work_dir / "artifacts"
    manifests = args.work_dir / "manifests"
    for path in (dist, artifacts, manifests):
        path.mkdir(parents=True)
    report_disk_capacity(args.work_dir, "local release glow-up start")

    stable_version = deb_version(args.input_deb)
    nightly_version = stable_version
    arch = deb_arch(args.input_deb)
    admin = args.bin_dir / "capsem-admin"
    if not admin.is_file() or not os.access(admin, os.X_OK):
        raise SystemExit(f"local release glow-up requires executable {admin}")

    with local_release_server(dist) as base_url:
        exact_transport: ExactReleaseTransport | None = None
        if exact_pairing is not None:
            exact_transport = stage_exact_release_transport(
                exact_pairing,
                dist=dist,
                base_url=base_url,
            )
        stable_manifest_url = f"{base_url}/assets/stable/manifest.json"
        nightly_manifest_url = f"{base_url}/assets/nightly/manifest.json"
        stable_download_base = f"{base_url}/releases/download/stable"
        nightly_download_base = f"{base_url}/releases/download/nightly"
        stable_deb = (
            artifacts / "stable" / f"v{stable_version}" / f"Capsem_{stable_version}_{arch}.deb"
        )
        nightly_deb = (
            artifacts / "nightly" / f"v{nightly_version}" / f"Capsem_{nightly_version}_{arch}.deb"
        )
        stable_sbom = artifacts / "stable" / f"v{stable_version}" / "capsem-sbom.spdx.json"
        nightly_sbom = artifacts / "nightly" / f"v{nightly_version}" / "capsem-sbom.spdx.json"

        if args.package_ready:
            shutil.copy2(args.input_deb, stable_deb)
            shutil.copy2(args.input_deb, nightly_deb)
        else:
            repack_deb(
                args.input_deb,
                stable_deb,
                args.bin_dir,
                args.config_root,
                args.assets_dir,
                stable_manifest_url,
            )
            repack_deb(
                args.input_deb,
                nightly_deb,
                args.bin_dir,
                args.config_root,
                args.assets_dir,
                nightly_manifest_url,
            )
        generate_sbom(stable_sbom, stable_deb)
        generate_sbom(nightly_sbom, nightly_deb)

        # Serve release artifacts from the exact URL shape used by release metadata.
        copy_artifact_tree(
            stable_deb,
            dist / "releases" / "download" / "stable" / f"v{stable_version}" / stable_deb.name,
        )
        copy_artifact_tree(
            stable_sbom,
            dist / "releases" / "download" / "stable" / f"v{stable_version}" / stable_sbom.name,
        )
        copy_artifact_tree(
            nightly_deb,
            dist / "releases" / "download" / "nightly" / f"v{nightly_version}" / nightly_deb.name,
        )
        copy_artifact_tree(
            nightly_sbom,
            dist / "releases" / "download" / "nightly" / f"v{nightly_version}" / nightly_sbom.name,
        )

        stable_manifest = manifests / "stable-assets-manifest.json"
        nightly_manifest = manifests / "nightly-assets-manifest.json"
        shutil.copy2(args.assets_dir / "manifest.json", stable_manifest)
        shutil.copy2(args.assets_dir / "manifest.json", nightly_manifest)
        report_disk_capacity(args.work_dir, "before immutable VM blob staging")
        stage_manifest_artifacts(stable_manifest, args.assets_dir, dist, base_url)
        # Both channels begin with the same verified profile cohort. Binary
        # authoring below mutates only each manifest's package inventory.
        shutil.copy2(stable_manifest, nightly_manifest)

        record_binary(
            admin, stable_manifest, stable_version, stable_deb, stable_sbom, stable_download_base
        )
        record_binary(
            admin,
            nightly_manifest,
            nightly_version,
            nightly_deb,
            nightly_sbom,
            nightly_download_base,
        )
        build_channel(
            admin,
            stable_manifest,
            args.assets_dir,
            args.config_root / "profiles",
            "stable",
            dist,
            base_url,
        )
        stable_channel_manifest = dist / "assets" / "stable" / "manifest.json"
        stable_channel_sha_before_nightly = file_sha256(stable_channel_manifest)
        stable_channel_packages_before_nightly = current_package_versions(stable_channel_manifest)
        build_channel(
            admin,
            nightly_manifest,
            args.assets_dir,
            args.config_root / "profiles",
            "nightly",
            dist,
            base_url,
        )
        if file_sha256(stable_channel_manifest) != stable_channel_sha_before_nightly:
            raise SystemExit("nightly channel build mutated stable manifest")
        if (
            current_package_versions(stable_channel_manifest)
            != stable_channel_packages_before_nightly
        ):
            raise SystemExit("nightly channel build mutated stable package records")

        install_script_url = f"{base_url}/install.sh"
        shutil.copy2(args.install_script, dist / "install.sh")
        corp_dir = dist / "corp"
        corp_dir.mkdir()
        corp_manifest = corp_dir / "manifest.json"
        shutil.copy2(stable_channel_manifest, corp_manifest)
        corp_manifest_url = f"{base_url}/corp/manifest.json"
        stable_artifact = check_generated_release(
            base_url,
            stable_manifest_url,
            stable_deb,
            dist,
            "stable",
            expected_version=stable_version,
            expected_architecture=arch,
        )
        nightly_artifact = check_generated_release(
            base_url,
            nightly_manifest_url,
            nightly_deb,
            dist,
            "nightly",
            expected_version=nightly_version,
            expected_architecture=arch,
        )
        if not args.skip_install:
            if exact_pairing is not None:
                if exact_transport is None:
                    raise SystemExit("exact release transport was not staged")
                exact_evidence = run_exact_installed_glowup(
                    pairing=exact_pairing,
                    transport=exact_transport,
                    install_script_url=install_script_url,
                    release_base_url=base_url,
                    evidence_dir=args.work_dir / "exact-transition-evidence",
                )
                installed = json.loads(
                    exact_evidence.candidate_installed.read_text(encoding="utf-8")
                )
                installed["package_receipt"] = True
                installed["binary_cohort"] = True
                exact_artifact = artifact_identity_from_manifest_package(
                    exact_pairing.after_manifest.read_bytes(),
                    exact_pairing.after_package,
                )
                transitions = exact_installed_transition_rows(
                    exact_pairing,
                    exact_evidence,
                )
                expected_transitions = [
                    TransitionKind.FRESH_INSTALL,
                    exact_pairing.transition,
                    TransitionKind.TAMPER_REJECTION,
                ]
                report = build_report(
                    adapter="linux-docker-systemd",
                    artifact=exact_artifact,
                    installed=installed,
                    capabilities={
                        "native_install": True,
                        "systemd": True,
                        "service_owned_update": True,
                        "full_doctor": True,
                        "installed_winterfell": True,
                    },
                    transitions=transitions,
                    expected_transitions=expected_transitions,
                )
                report["adapter_evidence"] = {
                    "base_url": base_url,
                    "release_pairing": {
                        "kind": exact_pairing.transition.value,
                        "before": exact_pairing.before.as_report(),
                        "after": exact_pairing.after.as_report(),
                    },
                    "polled_manifest_url": exact_transport.current_manifest_url,
                    "channel_catalog_url": exact_transport.channel_catalog_url,
                    "rejections": {
                        "tampered_artifact": json.loads(
                            exact_evidence.tamper_rejection.read_text(encoding="utf-8")
                        ),
                        "incompatible_profile": json.loads(
                            exact_evidence.incompatible_rejection.read_text(
                                encoding="utf-8"
                            )
                        ),
                    },
                }
            else:
                evidence_path = args.work_dir / "installed-evidence.json"
                run_installed_glowup(
                    install_script_url=install_script_url,
                    release_base_url=base_url,
                    stable_manifest_url=stable_manifest_url,
                    nightly_manifest_url=nightly_manifest_url,
                    corp_manifest_url=corp_manifest_url,
                    package_version=stable_version,
                    stable_package=stable_deb,
                    nightly_package=nightly_deb,
                    package_architecture=arch,
                    evidence_out=evidence_path,
                )
                installed = json.loads(evidence_path.read_text(encoding="utf-8"))
                installed["package_receipt"] = True
                installed["binary_cohort"] = True
                report = build_report(
                    adapter="linux-docker-systemd",
                    artifact=nightly_artifact,
                    installed=installed,
                    capabilities={
                        "native_install": True,
                        "systemd": True,
                        "stable_nightly_round_trip": True,
                        "corporate_channel_lock": True,
                    },
                )
                report["adapter_evidence"] = {
                    "base_url": base_url,
                    "stable_manifest_url": stable_manifest_url,
                    "nightly_manifest_url": nightly_manifest_url,
                    "stable_artifact": stable_artifact.as_report(),
                }
            (args.work_dir / "report.json").write_text(
                json.dumps(report, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )

    print(
        "local release glow-up passed: "
        f"stable={stable_version} nightly={nightly_version} dist={dist}"
    )
    return 0


def validate_exact_release_pairing(
    args: argparse.Namespace,
) -> ExactReleasePairing | None:
    """Fail closed when a release lane supplies an incomplete exact pairing."""

    core_fields = {
        "release_channel": args.release_channel,
        "release_transition": args.release_transition,
        "before_manifest": args.before_manifest,
        "after_manifest": args.after_manifest,
        "before_package": args.before_package,
        "before_profile_inputs": args.before_profile_inputs,
        "after_profile_inputs": args.after_profile_inputs,
    }
    profile_fields = {
        "profile": args.profile,
        "candidate_profile_publication": args.candidate_profile_publication,
        "publication_base": args.publication_base,
    }
    if not any(value is not None for value in (*core_fields.values(), *profile_fields.values())):
        return None
    missing = [name for name, value in core_fields.items() if value is None]
    if missing:
        raise SystemExit(
            "exact pairing requires release channel, transition, before/after "
            "manifests, before package, and before/after profile inputs; "
            f"missing={missing}"
        )

    channel = str(args.release_channel)
    before_manifest = Path(args.before_manifest)
    after_manifest = Path(args.after_manifest)
    before_package = Path(args.before_package)
    before_profile_inputs = Path(args.before_profile_inputs)
    after_profile_inputs = Path(args.after_profile_inputs)
    before_manifest_bytes = before_manifest.read_bytes()
    after_manifest_bytes = after_manifest.read_bytes()
    before_report, _, _ = load_verified_release_inputs(before_profile_inputs)
    after_report, _, _ = load_verified_release_inputs(after_profile_inputs)
    if before_report.get("kind") != "profiles" or after_report.get("kind") != "profiles":
        raise SystemExit("exact pairing inputs must contain verified profiles")
    if (before_profile_inputs / "manifest.json").read_bytes() != before_manifest_bytes:
        raise SystemExit(
            "exact pairing before profile inputs do not reproduce the public-before manifest"
        )
    if (after_profile_inputs / "manifest.json").read_bytes() != after_manifest_bytes:
        raise SystemExit(
            "exact pairing after profile inputs do not reproduce the candidate-after manifest"
        )

    before_artifact = artifact_identity_from_manifest_package(
        before_manifest_bytes,
        before_package,
    )
    after_artifact = artifact_identity_from_manifest_package(
        after_manifest_bytes,
        Path(args.input_deb),
    )
    if args.release_transition == "auto":
        transition, changed_profiles = classify_pairing_inputs(
            channel=channel,
            before_manifest_bytes=before_manifest_bytes,
            after_manifest_bytes=after_manifest_bytes,
            before_artifact=before_artifact,
            after_artifact=after_artifact,
        )
        if args.profile is not None and changed_profiles != (args.profile,):
            raise SystemExit(
                "exact pairing selected profile does not match the classified manifest delta"
            )
    else:
        transition = TransitionKind(str(args.release_transition))
        changed_profiles = (str(args.profile),) if args.profile is not None else ()

    changed_profile = transition in {
        TransitionKind.PROFILE_ONLY,
        TransitionKind.PROFILE_THEN_BINARY,
    }
    publication_fields = {
        "candidate_profile_publication": args.candidate_profile_publication,
        "publication_base": args.publication_base,
    }
    supplied_publication_fields = [
        name for name, value in publication_fields.items() if value is not None
    ]
    if transition is TransitionKind.PROFILE_ONLY:
        missing_profile = [name for name, value in profile_fields.items() if value is None]
        if missing_profile:
            raise SystemExit(
                "exact profile pairing requires profile, candidate publication, "
                f"and publication base; missing={missing_profile}"
            )
        try:
            run(
                [
                    sys.executable,
                    "scripts/verify-profile-publication.py",
                    "--manifest",
                    str(after_manifest),
                    "--profile",
                    str(args.profile),
                    "--publication-base",
                    str(args.publication_base),
                    "--release-dir",
                    str(args.candidate_profile_publication),
                ]
            )
        except subprocess.CalledProcessError as error:
            raise SystemExit(
                "exact pairing candidate profile publication failed verification"
            ) from error
    elif transition is TransitionKind.PROFILE_THEN_BINARY:
        if not changed_profiles:
            raise SystemExit("profile_then_binary exact pairing requires staged profiles")
        if supplied_publication_fields and len(supplied_publication_fields) != 2:
            raise SystemExit(
                "candidate profile publication base and directory must be supplied together"
            )
        if len(supplied_publication_fields) == 2:
            if args.profile is None:
                raise SystemExit("a local candidate publication requires its selected profile")
            try:
                run(
                    [
                        sys.executable,
                        "scripts/verify-profile-publication.py",
                        "--manifest",
                        str(after_manifest),
                        "--profile",
                        str(args.profile),
                        "--publication-base",
                        str(args.publication_base),
                        "--release-dir",
                        str(args.candidate_profile_publication),
                    ]
                )
            except subprocess.CalledProcessError as error:
                raise SystemExit(
                    "exact pairing candidate profile publication failed verification"
                ) from error
    elif any(value is not None for value in profile_fields.values()):
        raise SystemExit(
            "binary_only exact pairing cannot supply candidate profile publication inputs"
        )

    before, after = validate_pairing_inputs(
        kind=transition,
        channel=channel,
        before_manifest_bytes=before_manifest_bytes,
        after_manifest_bytes=after_manifest_bytes,
        before_artifact=before_artifact,
        after_artifact=after_artifact,
        changed_profiles=changed_profiles if changed_profile else (),
    )
    return ExactReleasePairing(
        channel=channel,
        transition=transition,
        changed_profiles=changed_profiles,
        before=before,
        after=after,
        before_manifest=before_manifest,
        after_manifest=after_manifest,
        before_package=before_package,
        after_package=Path(args.input_deb),
        before_profile_inputs=before_profile_inputs,
        after_profile_inputs=after_profile_inputs,
    )


def _rewrite_transport_urls(
    value: object,
    *,
    manifest_url: str,
    replacements: dict[str, str],
    reverse: dict[str, str],
    used: set[str],
) -> None:
    if isinstance(value, dict):
        fields = cast(dict[str, object], value)
        for key, child in fields.items():
            if key == "url" and isinstance(child, str):
                absolute = urljoin(manifest_url, child)
                replacement = replacements.get(absolute)
                if replacement is not None:
                    fields[key] = replacement
                    reverse[replacement] = child
                    used.add(absolute)
                    continue
            _rewrite_transport_urls(
                child,
                manifest_url=manifest_url,
                replacements=replacements,
                reverse=reverse,
                used=used,
            )
    elif isinstance(value, list):
        for child in value:
            _rewrite_transport_urls(
                child,
                manifest_url=manifest_url,
                replacements=replacements,
                reverse=reverse,
                used=used,
            )


def _restore_transport_urls(value: object, reverse: dict[str, str]) -> None:
    if isinstance(value, dict):
        fields = cast(dict[str, object], value)
        for key, child in fields.items():
            if key == "url" and isinstance(child, str) and child in reverse:
                fields[key] = reverse[child]
            else:
                _restore_transport_urls(child, reverse)
    elif isinstance(value, list):
        for child in value:
            _restore_transport_urls(child, reverse)


def _stage_exact_transport_release(
    *,
    label: str,
    manifest_path: Path,
    package_path: Path,
    profile_inputs: Path,
    dist: Path,
    base_url: str,
) -> tuple[Path, Path]:
    manifest_bytes = manifest_path.read_bytes()
    authority = json.loads(manifest_bytes)
    if not isinstance(authority, dict):
        raise SystemExit(f"exact {label} manifest must be a JSON object")
    report, verified_manifest, _ = load_verified_release_inputs(profile_inputs)
    if report.get("kind") != "profiles" or verified_manifest != authority:
        raise SystemExit(f"exact {label} profile inputs do not reproduce their authority manifest")
    manifest_url = report.get("manifest_url")
    artifacts = report.get("artifacts")
    if not isinstance(manifest_url, str) or not isinstance(artifacts, list):
        raise SystemExit(f"exact {label} profile input report is malformed")

    root = dist / "transitions" / label
    replacements: dict[str, str] = {}
    expected_profile_urls: set[str] = set()
    for index, row_value in enumerate(artifacts):
        if not isinstance(row_value, dict):
            raise SystemExit(f"exact {label} profile input row {index} is malformed")
        row = cast(dict[str, object], row_value)
        url = row.get("url")
        if not isinstance(url, str):
            raise SystemExit(f"exact {label} profile input row {index} has no URL")
        relative = safe_relative(row.get("path"))
        source = profile_inputs / relative
        target = root / "profiles" / relative
        copy_artifact_tree(source, target)
        local_url = f"{base_url}/transitions/{label}/profiles/{relative.as_posix()}"
        replacements[url] = local_url
        expected_profile_urls.add(url)

    artifact = artifact_identity_from_manifest_package(manifest_bytes, package_path)
    package_record = assert_manifest_artifact(authority, artifact)
    package_url = package_record.get("url")
    if not isinstance(package_url, str):
        raise SystemExit(f"exact {label} package record has no URL")
    package_absolute_url = urljoin(manifest_url, package_url)
    staged_package = root / "package" / package_path.name
    copy_artifact_tree(package_path, staged_package)
    replacements[package_absolute_url] = (
        f"{base_url}/transitions/{label}/package/{package_path.name}"
    )

    transport = copy.deepcopy(authority)
    reverse: dict[str, str] = {}
    used: set[str] = set()
    _rewrite_transport_urls(
        transport,
        manifest_url=manifest_url,
        replacements=replacements,
        reverse=reverse,
        used=used,
    )
    if not expected_profile_urls.issubset(used):
        missing = sorted(expected_profile_urls - used)
        raise SystemExit(f"exact {label} transport omitted profile URLs: {missing}")
    if package_absolute_url not in used:
        raise SystemExit(f"exact {label} transport omitted its native package URL")

    restored = copy.deepcopy(transport)
    _restore_transport_urls(restored, reverse)
    if restored != authority:
        raise SystemExit(f"exact {label} transport changed release data beyond URL projection")
    transport_manifest = root / "manifest.json"
    transport_manifest.parent.mkdir(parents=True, exist_ok=True)
    transport_manifest.write_text(
        json.dumps(transport, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return transport_manifest, staged_package


def stage_exact_release_transport(
    pairing: ExactReleasePairing,
    *,
    dist: Path,
    base_url: str,
) -> ExactReleaseTransport:
    """Build URL-only local projections around exact manifests and artifact bytes."""

    before_manifest, before_package = _stage_exact_transport_release(
        label="before",
        manifest_path=pairing.before_manifest,
        package_path=pairing.before_package,
        profile_inputs=pairing.before_profile_inputs,
        dist=dist,
        base_url=base_url,
    )
    after_manifest, after_package = _stage_exact_transport_release(
        label="after",
        manifest_path=pairing.after_manifest,
        package_path=pairing.after_package,
        profile_inputs=pairing.after_profile_inputs,
        dist=dist,
        base_url=base_url,
    )
    current_manifest = dist / "transitions" / "current" / "manifest.json"
    copy_artifact_tree(before_manifest, current_manifest)
    current_contents = current_manifest.read_bytes()
    channel_catalog = dist / "transitions" / "channels.json"
    channel_catalog.write_text(
        json.dumps(
            {
                "version": 1,
                "generated_at": "2030-01-01T00:00:00Z",
                "release_site": f"{base_url}/",
                "channels": {
                    pairing.channel: {
                        "label": pairing.channel.replace("-", " ").title(),
                        "manifests": [
                            {
                                "version": json.loads(current_contents).get(
                                    "version", "1.0.0"
                                ),
                                "status": "current",
                                "url": "/transitions/current/manifest.json",
                                "digest": {
                                    "sha256": hashlib.sha256(current_contents).hexdigest(),
                                    "blake3": file_blake3(current_manifest),
                                },
                            }
                        ],
                    }
                },
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return ExactReleaseTransport(
        before_manifest=before_manifest,
        after_manifest=after_manifest,
        current_manifest=current_manifest,
        channel_catalog=channel_catalog,
        before_manifest_url=f"{base_url}/transitions/before/manifest.json",
        after_manifest_url=f"{base_url}/transitions/after/manifest.json",
        current_manifest_url=f"{base_url}/transitions/current/manifest.json",
        channel_catalog_url=f"{base_url}/transitions/channels.json",
        before_package=before_package,
        after_package=after_package,
    )


def promote_exact_manifest(manifest: Path, current_manifest: Path) -> None:
    """Atomically expose one already-staged manifest at the installed polling URL."""

    pending = current_manifest.with_suffix(".next")
    try:
        shutil.copyfile(manifest, pending)
        os.replace(pending, current_manifest)
    finally:
        pending.unlink(missing_ok=True)


def promote_exact_candidate_transport(transport: ExactReleaseTransport) -> None:
    """Atomically expose candidate-after bytes at the installed polling URL."""

    promote_exact_manifest(transport.after_manifest, transport.current_manifest)


def _adversarial_profile(
    manifest: dict[str, object],
    pairing: ExactReleasePairing,
) -> tuple[str, dict[str, object]]:
    profiles = manifest.get("profiles")
    if not isinstance(profiles, dict) or not profiles:
        raise SystemExit("exact adversarial candidate has no profiles")
    profile_map = cast(dict[str, object], profiles)
    profile_ids = pairing.changed_profiles or tuple(sorted(profiles))
    for profile_id in profile_ids:
        profile = profile_map.get(profile_id)
        if isinstance(profile_id, str) and isinstance(profile, dict):
            return profile_id, cast(dict[str, object], profile)
    raise SystemExit("exact adversarial candidate lacks its selected profile")


def _tamper_selected_profile_digest(
    manifest: dict[str, object],
    pairing: ExactReleasePairing,
) -> None:
    try:
        tamper_profile_artifact_digest(
            manifest,
            profile_ids=pairing.changed_profiles,
        )
    except RuntimeError as error:
        raise SystemExit(f"cannot stage exact adversarial profile: {error}") from error


def stage_adversarial_exact_candidates(
    pairing: ExactReleasePairing,
    transport: ExactReleaseTransport,
    *,
    output_dir: Path,
) -> AdversarialExactCandidates:
    """Derive local rejection candidates without changing authoritative release inputs."""

    authority_before = pairing.after_manifest.read_bytes()
    projected_before = transport.after_manifest.read_bytes()
    try:
        projected = json.loads(projected_before)
    except json.JSONDecodeError as error:
        raise SystemExit(f"exact projected candidate manifest is invalid: {error}") from error
    if not isinstance(projected, dict):
        raise SystemExit("exact projected candidate manifest must be an object")

    tampered = copy.deepcopy(projected)
    _tamper_selected_profile_digest(tampered, pairing)
    incompatible = copy.deepcopy(projected)
    _, incompatible_profile = _adversarial_profile(incompatible, pairing)
    incompatible_profile["min_capsem_version"] = "9999.0.0"

    output_dir.mkdir(parents=True, exist_ok=True)
    tampered_manifest = output_dir / "tampered-artifact-manifest.json"
    incompatible_manifest = output_dir / "incompatible-profile-manifest.json"
    tampered_manifest.write_text(
        json.dumps(tampered, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    incompatible_manifest.write_text(
        json.dumps(incompatible, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    if pairing.after_manifest.read_bytes() != authority_before:
        raise SystemExit("adversarial staging mutated the authoritative candidate manifest")
    if transport.after_manifest.read_bytes() != projected_before:
        raise SystemExit("adversarial staging mutated the exact projected candidate manifest")
    if tampered_manifest.read_bytes() == projected_before:
        raise SystemExit("tampered artifact candidate did not change the projected manifest")
    if incompatible_manifest.read_bytes() == projected_before:
        raise SystemExit("incompatible profile candidate did not change the projected manifest")
    return AdversarialExactCandidates(
        tampered_manifest=tampered_manifest,
        incompatible_manifest=incompatible_manifest,
    )


def run(cmd: list[str], *, cwd: Path = PROJECT_ROOT, env: dict[str, str] | None = None) -> None:
    merged = os.environ.copy()
    if env:
        merged.update(env)
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, env=merged, check=True)


def deb_version(path: Path) -> str:
    return subprocess.check_output(["dpkg-deb", "-f", str(path), "Version"], text=True).strip()


def deb_arch(path: Path) -> str:
    arch = subprocess.check_output(["dpkg-deb", "-f", str(path), "Architecture"], text=True).strip()
    if arch not in {"amd64", "arm64"}:
        raise SystemExit(f"unsupported local glow-up deb architecture: {arch}")
    return arch


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def file_blake3(path: Path) -> str:
    try:
        import blake3
    except ModuleNotFoundError:
        return subprocess.check_output(["b3sum", str(path)], text=True).split()[0]
    return blake3.blake3(path.read_bytes()).hexdigest()


def current_package_versions(manifest_path: Path) -> list[str]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    return sorted(
        package["version"]
        for package in manifest.get("packages", [])
        if isinstance(package, dict) and package.get("status") == "current"
    )


def report_disk_capacity(path: Path, label: str) -> None:
    usage = shutil.disk_usage(path)
    gib = 1024**3
    print(
        f"Disk capacity ({label}): {usage.free / gib:.1f} GiB free of {usage.total / gib:.1f} GiB",
        flush=True,
    )


def repack_deb(
    input_deb: Path,
    output_deb: Path,
    bin_dir: Path,
    config_root: Path,
    assets_dir: Path,
    manifest_url: str,
) -> None:
    output_deb.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "bash",
            "scripts/repack-deb.sh",
            "--manifest",
            manifest_url,
            str(input_deb),
            str(bin_dir),
            str(config_root),
            str(assets_dir),
            str(output_deb),
        ]
    )


def generate_sbom(output: Path, deb: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    run(["python3", "scripts/generate-host-binary-sbom.py", "--output", str(output), str(deb)])


def record_binary(
    admin: Path,
    manifest: Path,
    version: str,
    deb: Path,
    sbom: Path,
    release_download_base: str,
) -> None:
    run(
        [
            str(admin),
            "assets",
            "channel",
            "record-binary",
            "--manifest-path",
            str(manifest),
            "--version",
            version,
            "--artifact",
            str(deb),
            "--artifact",
            str(sbom),
        ],
        env={"CAPSEM_RELEASE_URL": release_download_base},
    )


def build_channel(
    admin: Path,
    manifest: Path,
    assets_dir: Path,
    profiles_dir: Path,
    channel: str,
    dist: Path,
    base_url: str,
) -> None:
    run(
        [
            str(admin),
            "assets",
            "channel",
            "build",
            "--manifest",
            manifest.resolve().as_uri(),
            "--assets-dir",
            str(assets_dir),
            "--profiles-dir",
            str(profiles_dir),
            "--channel",
            channel,
            "--manifest-version",
            "1.0.0",
            "--asset-source-base",
            f"{base_url}/assets/releases/{{asset_version}}",
            "--out-dir",
            str(dist),
        ],
        env={"CAPSEM_RELEASE_URL": f"{base_url}/releases/download/{channel}"},
    )


def copy_artifact_tree(source: Path, target: Path) -> None:
    """Stage an immutable artifact without duplicating it when possible.

    The local release server only reads these files.  A same-filesystem
    hardlink therefore preserves the exact bytes while avoiding another copy
    of the multi-gigabyte VM asset cohort late in ``just test``.  macOS and
    Linux both support this path.  Filesystems that cannot hardlink across the
    source/dist boundary retain the portable copy behavior.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(source, target)
    except OSError as error:
        fallback_errors = {
            errno.EACCES,
            errno.EPERM,
            errno.EXDEV,
            errno.ENOTSUP,
            errno.EOPNOTSUPP,
        }
        if error.errno not in fallback_errors:
            raise
        shutil.copy2(source, target)


def stage_manifest_artifacts(
    manifest_path: Path,
    assets_dir: Path,
    dist: Path,
    base_url: str,
) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if isinstance(manifest.get("profiles"), dict):
        _stage_graph_manifest_artifacts(manifest_path, manifest, dist, base_url)
        return

    assets = manifest.get("assets")
    if not isinstance(assets, dict):
        raise SystemExit("local glow-up asset manifest has no assets object")
    version = assets.get("current")
    releases = assets.get("releases")
    release = releases.get(version) if isinstance(releases, dict) else None
    arches = release.get("arches") if isinstance(release, dict) else None
    if not isinstance(version, str) or not isinstance(arches, dict):
        raise SystemExit("local glow-up asset manifest has no current release arches")
    release_dir = dist / "assets" / "releases" / version
    release_dir.mkdir(parents=True, exist_ok=True)
    for arch, rows in arches.items():
        if not isinstance(arch, str) or not isinstance(rows, dict):
            raise SystemExit("local glow-up asset manifest has invalid architecture rows")
        for logical_name, descriptor in rows.items():
            source = assets_dir / arch / logical_name
            if not source.is_file() or not isinstance(descriptor, dict):
                raise SystemExit(f"local glow-up VM asset is missing: {source}")
            expected_size = descriptor.get("size")
            if source.stat().st_size != expected_size:
                raise SystemExit(f"local glow-up VM asset size mismatch: {source}")
            # The immediately following capsem-admin channel build validates
            # every source digest against this same manifest.
            copy_artifact_tree(source, release_dir / f"{arch}-{logical_name}")


def _stage_graph_manifest_artifacts(
    manifest_path: Path,
    manifest: dict[str, object],
    dist: Path,
    base_url: str,
) -> None:
    profiles = manifest.get("profiles")
    if not isinstance(profiles, dict) or not profiles:
        raise SystemExit("local glow-up release graph has no profiles")

    staged: list[tuple[dict[str, object], Path, Path, bytes]] = []
    for profile_id, profile in sorted(profiles.items()):
        if not isinstance(profile, dict) or profile.get("status") == "revoked":
            continue
        architectures = profile.get("architectures")
        if not isinstance(architectures, list) or not architectures:
            raise SystemExit(f"local glow-up release profile {profile_id} has no architectures")
        staged_architectures: list[dict[str, object]] = []
        for architecture in architectures:
            if not isinstance(architecture, dict):
                raise SystemExit(
                    f"local glow-up release profile {profile_id} has malformed architecture"
                )
            arch = architecture.get("architecture", "unknown")
            active_rows: list[tuple[str, int, dict[str, object], str]] = []
            for section in ("config", "images", "evidence"):
                rows = architecture.get(section, [])
                if not isinstance(rows, list):
                    raise SystemExit(
                        f"local glow-up release profile {profile_id}/{arch} "
                        f"has malformed {section}"
                    )
                for index, row in enumerate(rows):
                    if not isinstance(row, dict) or row.get("status") == "revoked":
                        continue
                    url = row.get("url")
                    if not isinstance(url, str):
                        raise SystemExit(
                            f"local glow-up release profile {profile_id}/{arch} "
                            f"{section}[{index}] has no URL"
                        )
                    active_rows.append((section, index, row, url))
            if not active_rows:
                raise SystemExit(
                    f"local glow-up release profile {profile_id}/{arch} has no active artifacts"
                )
            local_rows = [
                row
                for row in active_rows
                if (parsed := urlparse(row[3])).scheme == "file" and not parsed.netloc
            ]
            if local_rows and len(local_rows) != len(active_rows):
                raise SystemExit(
                    f"local glow-up release profile {profile_id}/{arch} "
                    "mixes staged and unstaged artifacts"
                )
            if not local_rows:
                continue
            staged_architectures.append(architecture)
            for section, index, row, url in active_rows:
                parsed = urlparse(url)
                source = Path(unquote(parsed.path))
                if not source.is_file():
                    raise SystemExit(f"local glow-up graph artifact is missing: {source}")
                payload = source.read_bytes()
                label = (
                    f"profile {profile_id}/{arch} {section}[{index}] "
                    f"{row.get('name') or row.get('path') or row.get('kind') or url}"
                )
                try:
                    verify_payload(payload, row, label)
                except ValueError as error:
                    raise SystemExit(str(error)) from error
                digest = cast(dict[str, object], row["digest"])
                sha256 = cast(str, digest["sha256"]).lower()
                filename = source.name
                if not filename or filename in {".", ".."}:
                    raise SystemExit(f"local glow-up graph artifact has unsafe name: {url}")
                relative = Path("artifacts") / "sha256" / sha256 / filename
                staged.append((row, source, dist / relative, payload))
        if not staged_architectures:
            raise SystemExit(
                f"local glow-up release profile {profile_id} has no fully staged architectures"
            )
        profile["architectures"] = staged_architectures

    if not staged:
        raise SystemExit("local glow-up release graph resolved no profile artifacts")

    for row, source, target, payload in staged:
        if target.exists():
            if not target.is_file() or target.read_bytes() != payload:
                raise SystemExit(f"local glow-up graph artifact collision: {target}")
        else:
            copy_artifact_tree(source, target)
        relative = target.relative_to(dist).as_posix()
        row["url"] = f"{base_url.rstrip('/')}/{relative}"

    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def check_generated_release(
    base_url: str,
    manifest_url: str,
    expected_deb: Path,
    dist: Path,
    channel: str,
    *,
    expected_version: str | None = None,
    expected_architecture: str | None = None,
) -> ArtifactIdentity:
    request = urllib.request.Request(
        manifest_url,
        headers={"User-Agent": "capsem-release-client/1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        manifest = json.loads(response.read())
    packages = manifest.get("packages")
    if not isinstance(packages, list) or not packages:
        raise SystemExit(f"generated {channel} release manifest has no packages")
    package = next((item for item in packages if item.get("name") == expected_deb.name), None)
    if package is None:
        raise SystemExit(f"generated {channel} release manifest missing {expected_deb.name}")
    package_url = str(package.get("url", ""))
    if not package_url.startswith(f"{base_url}/releases/download/"):
        raise SystemExit(f"generated {channel} package URL is not local: {package.get('url')}")
    package_path = dist / package_url.removeprefix(f"{base_url}/")
    if not package_path.is_file():
        raise SystemExit(f"generated {channel} package URL is not served: {package_url}")
    inferred = re.fullmatch(r"Capsem_(.+)_(amd64|arm64)\.deb", expected_deb.name)
    if inferred is None:
        raise SystemExit(f"cannot infer release identity from {expected_deb.name}")
    artifact = ArtifactIdentity.from_path(
        expected_deb if expected_deb.is_file() else package_path,
        version=expected_version or inferred.group(1),
        platform="linux",
        architecture=expected_architecture or inferred.group(2),
    )
    if expected_version is not None and expected_architecture is not None:
        package = assert_manifest_artifact(manifest, artifact)
    profile_artifacts = release_profile_artifacts(manifest)
    missing_assets: list[str] = []
    staged_assets: list[tuple[str, Path, dict[str, object]]] = []
    for record in profile_artifacts:
        url = cast(str, record["url"])
        artifact_path = local_release_artifact_path(base_url, url, dist)
        if not artifact_path.is_file():
            missing_assets.append(url)
        else:
            staged_assets.append((url, artifact_path, record))
    if missing_assets:
        raise SystemExit(
            f"generated {channel} release is missing VM asset blob(s): " + ", ".join(missing_assets)
        )
    for url, artifact_path, record in staged_assets:
        try:
            verify_payload(
                artifact_path.read_bytes(),
                record,
                f"generated {channel} profile artifact {url}",
            )
        except ValueError as error:
            raise SystemExit(str(error)) from error
    return artifact


def local_release_artifact_path(base_url: str, url: str, dist: Path) -> Path:
    base = urlparse(base_url)
    parsed = urlparse(url)
    if parsed.query or parsed.fragment:
        raise SystemExit(f"generated VM asset URL has query or fragment: {url}")
    if parsed.scheme or parsed.netloc:
        if (parsed.scheme, parsed.netloc) != (base.scheme, base.netloc):
            raise SystemExit(f"generated VM asset URL is not local: {url}")
    elif not url.startswith("/") or url.startswith("//"):
        raise SystemExit(f"generated VM asset URL is not manifest-root-relative: {url}")
    try:
        relative = safe_relative(
            unquote(parsed.path).lstrip("/"),
            "generated VM asset URL",
        )
    except ValueError as error:
        raise SystemExit(str(error)) from error
    return dist / relative


def release_asset_urls(manifest: dict[str, object]) -> list[str]:
    return [cast(str, record["url"]) for record in release_profile_artifacts(manifest)]


def release_profile_artifacts(manifest: dict[str, object]) -> list[dict[str, object]]:
    artifacts: list[dict[str, object]] = []
    image_count = 0
    profiles = manifest.get("profiles")
    if not isinstance(profiles, dict):
        raise SystemExit("generated stable release manifest has no profile graph")
    for profile in profiles.values():
        if not isinstance(profile, dict):
            continue
        profile_fields = cast(dict[str, object], profile)
        architectures = profile_fields.get("architectures")
        if not isinstance(architectures, list):
            continue
        for architecture in architectures:
            if not isinstance(architecture, dict):
                continue
            architecture_fields = cast(dict[str, object], architecture)
            for section in ("config", "images", "evidence"):
                rows = architecture_fields.get(section)
                if not isinstance(rows, list):
                    continue
                for row in rows:
                    if not isinstance(row, dict):
                        continue
                    row_fields = cast(dict[str, object], row)
                    if isinstance(row_fields.get("url"), str):
                        artifacts.append(row_fields)
                        if section == "images":
                            image_count += 1
    if image_count == 0:
        raise SystemExit("generated stable release manifest has no VM asset URLs")
    return artifacts


def _exact_installed_probe_shell(evidence_dir: Path) -> str:
    return f"""
CAPSEM_BIN="$HOME/.capsem/bin/capsem"
CAPSEM_HOME_DIR="$HOME/.capsem"
EVIDENCE_DIR={shlex.quote(str(evidence_dir))}
mkdir -p "$EVIDENCE_DIR"
wait_for_service() {{
  for attempt in $(seq 1 90); do
    if CAPSEM_HOME="$CAPSEM_HOME_DIR" CAPSEM_RUN_DIR="$CAPSEM_HOME_DIR/run" \
      "$CAPSEM_BIN" status > "$EVIDENCE_DIR/service-status.txt" 2>&1 \
      && grep -Fq "Installed: true" "$EVIDENCE_DIR/service-status.txt" \
      && grep -Fq "Running:   true" "$EVIDENCE_DIR/service-status.txt" \
      && grep -Fq "Service:   ok" "$EVIDENCE_DIR/service-status.txt" \
      && grep -Fq "Gateway:   ok" "$EVIDENCE_DIR/service-status.txt"; then
      return 0
    fi
    sleep 2
  done
  cat "$EVIDENCE_DIR/service-status.txt" >&2 || true
  systemctl --user status capsem.service --no-pager -l >&2 || true
  journalctl --user-unit capsem.service --no-pager -n 200 >&2 || true
  return 1
}}
check_binary_versions() {{
  expected="$1"
  for binary in {" ".join(HOST_BINARIES)}; do
    test -x "$CAPSEM_HOME_DIR/bin/$binary"
    if [ "$binary" = capsem ]; then
      "$CAPSEM_HOME_DIR/bin/$binary" version
    else
      "$CAPSEM_HOME_DIR/bin/$binary" --version
    fi > "$EVIDENCE_DIR/$binary.version" 2>&1
    grep -F "$expected" "$EVIDENCE_DIR/$binary.version"
  done
}}
probe_installed_transition() {{
  label="$1"
  manifest_url="$2"
  channel="$3"
  package_version="$4"
  artifact="$5"
  platform="$6"
  architecture="$7"
  wait_for_service
  check_binary_versions "$package_version"
  dpkg-query -W -f='${{Version}}' capsem | grep -Fx "$package_version"
  python3 scripts/verify-installed-release.py \
    --capsem "$CAPSEM_BIN" \
    --capsem-home "$CAPSEM_HOME_DIR" \
    --manifest-url "$manifest_url" \
    --channel "$channel" \
    --package-version "$package_version" \
    --artifact "$artifact" \
    --platform "$platform" \
    --architecture "$architecture" \
    --evidence-out "$EVIDENCE_DIR/$label-installed.json"
  doctor_log="$EVIDENCE_DIR/$label-doctor.log"
  failed_process_logs="$EVIDENCE_DIR/$label-failed-process-logs.txt"
  if ! CAPSEM_HOME="$CAPSEM_HOME_DIR" CAPSEM_RUN_DIR="$CAPSEM_HOME_DIR/run" \
    "$CAPSEM_BIN" doctor > "$doctor_log" 2>&1; then
    : > "$failed_process_logs"
    while IFS= read -r process_log; do
      printf '\n===== %s =====\n' "$process_log" >> "$failed_process_logs"
      tail -n 200 "$process_log" >> "$failed_process_logs" 2>&1 || true
    done < <(
      find "$CAPSEM_HOME_DIR/run/sessions" -type f -name process.log \
        -path "*-failed-*" -print 2>> "$failed_process_logs" || true
    )
    cat "$doctor_log" >&2
    cat "$failed_process_logs" >&2
    systemctl --user status capsem.service --no-pager -l >&2 || true
    journalctl --user-unit capsem.service --no-pager -n 200 >&2 || true
    return 1
  fi
  printf '%s\n' '{{"schema":"capsem.installed_doctor.v1","passed":true}}' \
    > "$EVIDENCE_DIR/$label-doctor.json"
  uv run python scripts/run-installed-winterfell.py \
    --bin-dir "$CAPSEM_HOME_DIR/bin" \
    --assets-dir "$CAPSEM_HOME_DIR/assets" \
    --profiles-dir "$CAPSEM_HOME_DIR/profiles" \
    --evidence-out "$EVIDENCE_DIR/$label-winterfell.json"
}}
wait_for_exact_transition() {{
  expected_manifest_sha="$1"
  expected_package_version="$2"
  for attempt in $(seq 1 90); do
    installed_manifest_sha=""
    installed_package_version=""
    if [ -f "$CAPSEM_HOME_DIR/assets/manifest.json" ]; then
      installed_manifest_sha=$(sha256sum "$CAPSEM_HOME_DIR/assets/manifest.json" | cut -d' ' -f1)
    fi
    installed_package_version=$(dpkg-query -W -f='${{Version}}' capsem 2>/dev/null || true)
    if [ "$installed_manifest_sha" = "$expected_manifest_sha" ] \
      && [ "$installed_package_version" = "$expected_package_version" ]; then
      return 0
    fi
    sleep 2
  done
  echo "automatic update did not activate exact candidate: expected manifest=$expected_manifest_sha package=$expected_package_version" >&2
  cat "$CAPSEM_HOME_DIR/logs/update.log" >&2 || true
  systemctl --user status capsem.service --no-pager -l >&2 || true
  journalctl --user-unit capsem.service --no-pager -n 200 >&2 || true
  return 1
}}
installed_profile_tree_digest() {{
  find "$CAPSEM_HOME_DIR/profiles" -type f -print0 \
    | sort -z \
    | xargs -0 sha256sum \
    | sha256sum \
    | cut -d' ' -f1
}}
wait_for_automatic_rejection() {{
  since="$1"
  for attempt in $(seq 1 90); do
    if journalctl --user-unit capsem.service --since "$since" --no-pager -o cat \
      | grep -Fq "automatic release update failed"; then
      return 0
    fi
    sleep 2
  done
  journalctl --user-unit capsem.service --since "$since" --no-pager -o cat >&2 || true
  return 1
}}
wait_for_incompatible_profile_rejection() {{
  since="$1"
  for attempt in $(seq 1 90); do
    journal=$(
      journalctl --user-unit capsem.service --since "$since" --no-pager -o cat
    )
    if printf '%s\n' "$journal" \
      | grep -Fq "automatic release update failed" \
      && printf '%s\n' "$journal" \
      | grep -Fq "requires Capsem 9999.0.0 or newer"; then
      return 0
    fi
    sleep 2
  done
  journalctl --user-unit capsem.service --since "$since" --no-pager -o cat >&2 || true
  return 1
}}
"""


def run_exact_installed_glowup(
    *,
    pairing: ExactReleasePairing,
    transport: ExactReleaseTransport,
    install_script_url: str,
    release_base_url: str,
    evidence_dir: Path,
) -> ExactInstalledGlowupEvidence:
    before_artifact = artifact_identity_from_manifest_package(
        pairing.before_manifest.read_bytes(),
        pairing.before_package,
    )
    after_artifact = artifact_identity_from_manifest_package(
        pairing.after_manifest.read_bytes(),
        pairing.after_package,
    )
    if before_artifact.platform != "linux" or after_artifact.platform != "linux":
        raise SystemExit("Linux installed glow-up requires exact Linux package artifacts")
    if before_artifact.architecture != after_artifact.architecture:
        raise SystemExit("exact installed transition cannot change package architecture")

    evidence_dir.mkdir(parents=True, exist_ok=True)
    probe_functions = _exact_installed_probe_shell(evidence_dir)
    before_script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {shlex.quote(install_script_url)} | \
  CAPSEM_CHANNEL={shlex.quote(pairing.channel)} \
  CAPSEM_RELEASE_BASE_URL={shlex.quote(release_base_url)} \
  CAPSEM_MANIFEST_URL={shlex.quote(transport.current_manifest_url)} sh
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" \
  CAPSEM_RELEASE_CHANNELS_URL={shlex.quote(transport.channel_catalog_url)} \
  "$HOME/.capsem/bin/capsem" update --assets --channel {shlex.quote(pairing.channel)}
systemctl --user set-environment \
  CAPSEM_AUTOMATIC_UPDATE_INITIAL_DELAY_SECS=2 \
  CAPSEM_AUTOMATIC_UPDATE_POLL_SECS=2
systemctl --user restart capsem.service
probe_installed_transition fresh-install \
  {shlex.quote(transport.current_manifest_url)} \
  {shlex.quote(pairing.channel)} \
  {shlex.quote(before_artifact.version)} \
  {shlex.quote(str(pairing.before_package))} \
  {shlex.quote(before_artifact.platform)} \
  {shlex.quote(before_artifact.architecture.value)}
"""
    run(["bash", "-lc", before_script])

    promote_exact_candidate_transport(transport)
    after_script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
wait_for_exact_transition \
  {shlex.quote(file_sha256(transport.after_manifest))} \
  {shlex.quote(after_artifact.version)}
probe_installed_transition candidate-after \
  {shlex.quote(transport.current_manifest_url)} \
  {shlex.quote(pairing.channel)} \
  {shlex.quote(after_artifact.version)} \
  {shlex.quote(str(pairing.after_package))} \
  {shlex.quote(after_artifact.platform)} \
  {shlex.quote(after_artifact.architecture.value)}
"""
    run(["bash", "-lc", after_script])

    adversarial = stage_adversarial_exact_candidates(
        pairing,
        transport,
        output_dir=evidence_dir / "adversarial",
    )
    tamper_evidence = evidence_dir / "tampered-rejection.json"
    promote_exact_manifest(
        adversarial.tampered_manifest,
        transport.current_manifest,
    )
    tamper_script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
cp "$CAPSEM_HOME_DIR/assets/manifest.json" \
  "$EVIDENCE_DIR/tampered-before-manifest.json"
profile_digest_before=$(installed_profile_tree_digest)
rejection_since=$(date --iso-8601=seconds)
systemctl --user restart capsem.service
wait_for_automatic_rejection "$rejection_since"
cmp "$EVIDENCE_DIR/tampered-before-manifest.json" \
  "$CAPSEM_HOME_DIR/assets/manifest.json"
! cmp -s {shlex.quote(str(transport.current_manifest))} \
  "$CAPSEM_HOME_DIR/assets/manifest.json"
test "$(installed_profile_tree_digest)" = "$profile_digest_before"
dpkg-query -W -f='${{Version}}' capsem \
  | grep -Fx {shlex.quote(after_artifact.version)}
printf '%s\n' \
  '{{"schema":"capsem.installed_rejection.v1","kind":"tampered_artifact","result":"rejected","preserved_previous":true}}' \
  > {shlex.quote(str(tamper_evidence))}
"""
    try:
        run(["bash", "-lc", tamper_script])
    finally:
        promote_exact_candidate_transport(transport)

    incompatible_evidence = evidence_dir / "incompatible-rejection.json"
    promote_exact_manifest(
        adversarial.incompatible_manifest,
        transport.current_manifest,
    )
    incompatible_script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
cp "$CAPSEM_HOME_DIR/assets/manifest.json" \
  "$EVIDENCE_DIR/incompatible-before-manifest.json"
profile_digest_before=$(installed_profile_tree_digest)
rejection_since=$(date --iso-8601=seconds)
systemctl --user restart capsem.service
wait_for_incompatible_profile_rejection "$rejection_since"
cmp "$EVIDENCE_DIR/incompatible-before-manifest.json" \
  "$CAPSEM_HOME_DIR/assets/manifest.json"
! cmp -s {shlex.quote(str(transport.current_manifest))} \
  "$CAPSEM_HOME_DIR/assets/manifest.json"
test "$(installed_profile_tree_digest)" = "$profile_digest_before"
dpkg-query -W -f='${{Version}}' capsem \
  | grep -Fx {shlex.quote(after_artifact.version)}
printf '%s\n' \
  '{{"schema":"capsem.installed_rejection.v1","kind":"incompatible_profile","result":"rejected","blocked_reason":"requires Capsem 9999.0.0 or newer","preserved_previous":true}}' \
  > {shlex.quote(str(incompatible_evidence))}
"""
    try:
        run(["bash", "-lc", incompatible_script])
    finally:
        promote_exact_candidate_transport(transport)

    preserved_script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
systemctl --user restart capsem.service
probe_installed_transition rejection-preserved \
  {shlex.quote(transport.current_manifest_url)} \
  {shlex.quote(pairing.channel)} \
  {shlex.quote(after_artifact.version)} \
  {shlex.quote(str(pairing.after_package))} \
  {shlex.quote(after_artifact.platform)} \
  {shlex.quote(after_artifact.architecture.value)}
"""
    run(["bash", "-lc", preserved_script])

    return ExactInstalledGlowupEvidence(
        fresh_installed=evidence_dir / "fresh-install-installed.json",
        fresh_doctor=evidence_dir / "fresh-install-doctor.json",
        fresh_winterfell=evidence_dir / "fresh-install-winterfell.json",
        candidate_installed=evidence_dir / "candidate-after-installed.json",
        candidate_doctor=evidence_dir / "candidate-after-doctor.json",
        candidate_winterfell=evidence_dir / "candidate-after-winterfell.json",
        tamper_rejection=tamper_evidence,
        incompatible_rejection=incompatible_evidence,
        preserved_installed=evidence_dir / "rejection-preserved-installed.json",
        preserved_doctor=evidence_dir / "rejection-preserved-doctor.json",
        preserved_winterfell=evidence_dir / "rejection-preserved-winterfell.json",
    )


def _probe_report_passed(path: Path, expected_schema: str) -> bool:
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"installed transition probe report is unreadable: {path}: {error}") from error
    if not isinstance(report, dict):
        raise SystemExit(f"installed transition probe report is not an object: {path}")
    if report.get("schema") != expected_schema or report.get("passed") is not True:
        raise SystemExit(f"installed transition probe failed: {path}: {report}")
    return True


def _validate_exact_installed_state(
    path: Path,
    pairing: PairingIdentity,
) -> None:
    try:
        installed = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"installed transition evidence is unreadable: {path}: {error}") from error
    if not isinstance(installed, dict):
        raise SystemExit(f"installed transition evidence is not an object: {path}")
    installed["package_receipt"] = True
    installed["binary_cohort"] = True
    validate_installed_evidence(installed)
    if installed.get("channel") != pairing.channel:
        raise SystemExit(f"installed transition evidence has wrong channel: {path}")
    if installed.get("package_version") != pairing.package_version:
        raise SystemExit(f"installed transition evidence has wrong package version: {path}")


def _validate_installed_rejection(path: Path, expected_kind: str) -> None:
    try:
        rejection = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"installed rejection evidence is unreadable: {path}: {error}") from error
    if not isinstance(rejection, dict):
        raise SystemExit(f"installed rejection evidence is not an object: {path}")
    if (
        rejection.get("schema") != "capsem.installed_rejection.v1"
        or rejection.get("kind") != expected_kind
        or rejection.get("result") != "rejected"
        or rejection.get("preserved_previous") is not True
    ):
        raise SystemExit(f"installed rejection evidence failed: {path}: {rejection}")
    if expected_kind == "incompatible_profile" and not isinstance(
        rejection.get("blocked_reason"),
        str,
    ):
        raise SystemExit(f"installed rejection evidence omitted blocked reason: {path}")


def exact_installed_transition_rows(
    pairing: ExactReleasePairing,
    evidence: ExactInstalledGlowupEvidence,
) -> list[dict[str, object]]:
    _validate_exact_installed_state(evidence.fresh_installed, pairing.before)
    _validate_exact_installed_state(evidence.candidate_installed, pairing.after)
    _validate_exact_installed_state(evidence.preserved_installed, pairing.after)
    _validate_installed_rejection(evidence.tamper_rejection, "tampered_artifact")
    _validate_installed_rejection(evidence.incompatible_rejection, "incompatible_profile")
    fresh_doctor = _probe_report_passed(
        evidence.fresh_doctor,
        "capsem.installed_doctor.v1",
    )
    fresh_winterfell = _probe_report_passed(
        evidence.fresh_winterfell,
        "capsem.installed_winterfell.v1",
    )
    candidate_doctor = _probe_report_passed(
        evidence.candidate_doctor,
        "capsem.installed_doctor.v1",
    )
    candidate_winterfell = _probe_report_passed(
        evidence.candidate_winterfell,
        "capsem.installed_winterfell.v1",
    )
    preserved_doctor = _probe_report_passed(
        evidence.preserved_doctor,
        "capsem.installed_doctor.v1",
    )
    preserved_winterfell = _probe_report_passed(
        evidence.preserved_winterfell,
        "capsem.installed_winterfell.v1",
    )
    return [
        build_transition_evidence(
            kind=TransitionKind.FRESH_INSTALL,
            before=None,
            after=pairing.before,
            result="activated",
            doctor_passed=fresh_doctor,
            winterfell_passed=fresh_winterfell,
        ),
        build_transition_evidence(
            kind=pairing.transition,
            before=pairing.before,
            after=pairing.after,
            result="activated",
            doctor_passed=candidate_doctor,
            winterfell_passed=candidate_winterfell,
            staged_profiles_sha256=(
                pairing.after.profiles_sha256
                if pairing.transition is TransitionKind.PROFILE_THEN_BINARY
                else None
            ),
        ),
        build_transition_evidence(
            kind=TransitionKind.TAMPER_REJECTION,
            before=pairing.after,
            after=pairing.after,
            result="rejected",
            doctor_passed=preserved_doctor,
            winterfell_passed=preserved_winterfell,
            preserved_previous=True,
        ),
    ]


def run_installed_glowup(
    *,
    install_script_url: str,
    release_base_url: str,
    stable_manifest_url: str,
    nightly_manifest_url: str,
    corp_manifest_url: str,
    package_version: str,
    stable_package: Path,
    nightly_package: Path,
    package_architecture: str,
    evidence_out: Path | None = None,
) -> None:
    installed_evidence = (
        evidence_out or PROJECT_ROOT / "target" / "local-release-glowup-evidence.json"
    )
    evidence_arg = shlex.quote(str(installed_evidence))
    transition_evidence_dir = installed_evidence.parent / "channel-transition-evidence"
    probe_functions = _exact_installed_probe_shell(transition_evidence_dir)
    script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
{probe_functions}
check_update_log() {{
  event="$1"
  source="$2"
  python3 - "$event" "$source" "$HOME/.capsem/logs/update.log" <<'PY'
import json
import pathlib
import sys
event, source, path = sys.argv[1:]
rows = [json.loads(line) for line in pathlib.Path(path).read_text().splitlines()]
if not any(row.get("event") == event and row.get("source") == source for row in rows):
    raise SystemExit(f"missing correlated update audit event={{event}} source={{source}}")
PY
}}
check_origin_channel() {{
  channel="$1"
  source="$2"
  locked="$3"
  python3 - "$channel" "$source" "$locked" "$HOME/.capsem/assets/manifest-metadata.json" <<'PY'
import json
import pathlib
import sys
channel, source, locked, path = sys.argv[1:]
origin = json.loads(pathlib.Path(path).read_text())
assert origin["channel"] == channel, origin
assert origin["manifest_url"] == source, origin
assert origin["channel_locked"] is (locked == "true"), origin
PY
}}
release_channels_url={release_base_url}/channels.json
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=stable CAPSEM_RELEASE_BASE_URL={release_base_url} sh
test -x "$HOME/.capsem/bin/capsem"
test -f "$HOME/.capsem/assets/manifest.json"
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
stable_manifest_sha=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
probe_installed_transition fresh-stable \
  {stable_manifest_url} stable {package_version} \
  {shlex.quote(str(stable_package))} linux {shlex.quote(package_architecture)}
test -f "$HOME/.capsem/logs/install.log"
grep -F "event=manifest_source source={stable_manifest_url}" "$HOME/.capsem/logs/install.log"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/logs/install.log"
grep -F "event=assets_hydrated" "$HOME/.capsem/logs/install.log"
grep -F "event=service_install_invoked" "$HOME/.capsem/logs/install.log"
check_update_log asset_update_complete {stable_manifest_url}
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {package_version}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --yes --channel nightly
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel nightly {nightly_manifest_url} false
check_update_log asset_update_complete {nightly_manifest_url}
probe_installed_transition channel-nightly \
  {nightly_manifest_url} nightly {package_version} \
  {shlex.quote(str(nightly_package))} linux {shlex.quote(package_architecture)}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --yes --channel stable
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel stable {stable_manifest_url} false
check_update_log asset_update_complete {stable_manifest_url}
probe_installed_transition channel-stable-return \
  {stable_manifest_url} stable {package_version} \
  {shlex.quote(str(stable_package))} linux {shlex.quote(package_architecture)}
stable_manifest_sha_after_switch=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
test "$stable_manifest_sha" = "$stable_manifest_sha_after_switch"
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {corp_manifest_url}
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel corp {corp_manifest_url} true
check_update_log asset_update_complete {corp_manifest_url}
probe_installed_transition corporate \
  {corp_manifest_url} corp {package_version} \
  {shlex.quote(str(stable_package))} linux {shlex.quote(package_architecture)}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
check_update_log asset_update_complete {corp_manifest_url}
set +e
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --assets --channel nightly > "$HOME/.capsem/corp-escape.log" 2>&1
corp_escape_status=$?
set -e
test "$corp_escape_status" -ne 0
grep -F "corporate channel is locked" "$HOME/.capsem/corp-escape.log"
check_origin_channel corp {corp_manifest_url} true
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {package_version}
set +e
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {nightly_manifest_url} > "$HOME/.capsem/corp-repoint.log" 2>&1
corp_repoint_status=$?
set -e
test "$corp_repoint_status" -ne 0
grep -F "corporate channel is locked to" "$HOME/.capsem/corp-repoint.log"
check_origin_channel corp {corp_manifest_url} true
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=nightly CAPSEM_RELEASE_BASE_URL={release_base_url} sh
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
probe_installed_transition final-nightly \
  {nightly_manifest_url} nightly {package_version} \
  {shlex.quote(str(nightly_package))} linux {shlex.quote(package_architecture)}
cp "$EVIDENCE_DIR/final-nightly-installed.json" {evidence_arg}
"""
    run(["bash", "-lc", script])


@contextlib.contextmanager
def local_release_server(root: Path):
    class ThreadingServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
        daemon_threads = True

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(root))
    server = ThreadingServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        address = server.server_address
        host = address[0]
        port = address[1]
        yield f"http://{host}:{port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


if __name__ == "__main__":
    raise SystemExit(main())
