#!/usr/bin/env python3
"""Hermetic local release glow-up for the install test rail.

This script intentionally uses the same build commands as the release lane:

* a Tauri-built .deb is repacked by ``scripts/repack-deb.sh``;
* host binary SBOMs are generated by ``scripts/generate-host-binary-sbom.py``;
* binary metadata is recorded by ``capsem-admin assets channel record-binary``;
* release-channel manifests are generated by ``capsem-admin assets channel build``;
* ``site/public/install.sh`` installs from a local HTTP release channel;
* ``capsem update --assets`` switches stable -> nightly -> stable;
* ``capsem update --yes`` finds and applies a newer nightly package.

No hand-authored release manifest is created here.
"""

from __future__ import annotations

import argparse
import contextlib
import datetime
import functools
import hashlib
import http.server
import json
import os
from pathlib import Path
import re
import shutil
import socketserver
import subprocess
import tempfile
import threading
import urllib.request


PROJECT_ROOT = Path(__file__).resolve().parents[1]
HOST_BINARIES = (
    "capsem",
    "capsem-service",
    "capsem-process",
    "capsem-tui",
    "capsem-mcp",
    "capsem-mcp-aggregator",
    "capsem-mcp-builtin",
    "capsem-gateway",
    "capsem-tray",
    "capsem-admin",
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-deb", required=True, type=Path)
    parser.add_argument("--bin-dir", required=True, type=Path)
    parser.add_argument("--assets-dir", required=True, type=Path)
    parser.add_argument("--config-root", required=True, type=Path)
    parser.add_argument("--install-script", default=PROJECT_ROOT / "site/public/install.sh", type=Path)
    parser.add_argument("--work-dir", default=PROJECT_ROOT / "target/local-release-glowup", type=Path)
    parser.add_argument("--skip-install", action="store_true")
    args = parser.parse_args()

    if args.work_dir.exists():
        shutil.rmtree(args.work_dir)
    args.work_dir.mkdir(parents=True)
    dist = args.work_dir / "dist"
    artifacts = args.work_dir / "artifacts"
    manifests = args.work_dir / "manifests"
    for path in (dist, artifacts, manifests):
        path.mkdir(parents=True)

    stable_version = deb_version(args.input_deb)
    nightly_version = next_patch_version(stable_version)
    arch = deb_arch(args.input_deb)

    with local_release_server(dist) as base_url:
        stable_manifest_url = f"{base_url}/assets/stable/manifest.json"
        nightly_manifest_url = f"{base_url}/assets/nightly/manifest.json"
        release_download_base = f"{base_url}/releases/download"
        stable_deb = artifacts / "stable" / f"v{stable_version}" / f"Capsem_{stable_version}_{arch}.deb"
        nightly_deb = artifacts / "nightly" / f"v{nightly_version}" / f"Capsem_{nightly_version}_{arch}.deb"
        stable_sbom = artifacts / "stable" / f"v{stable_version}" / "capsem-sbom.spdx.json"
        nightly_sbom = artifacts / "nightly" / f"v{nightly_version}" / "capsem-sbom.spdx.json"

        repack_deb(args.input_deb, stable_deb, args.bin_dir, args.config_root, stable_manifest_url)
        repack_deb(args.input_deb, nightly_deb, args.bin_dir, args.config_root, nightly_manifest_url)
        rewrite_deb_version(nightly_deb, nightly_version)
        generate_sbom(stable_sbom, stable_deb)
        generate_sbom(nightly_sbom, nightly_deb)

        # Serve release artifacts from the exact URL shape used by release metadata.
        copy_artifact_tree(stable_deb, dist / "releases" / "download" / f"v{stable_version}" / stable_deb.name)
        copy_artifact_tree(stable_sbom, dist / "releases" / "download" / f"v{stable_version}" / stable_sbom.name)
        copy_artifact_tree(nightly_deb, dist / "releases" / "download" / f"v{nightly_version}" / nightly_deb.name)
        copy_artifact_tree(nightly_sbom, dist / "releases" / "download" / f"v{nightly_version}" / nightly_sbom.name)

        stable_manifest = manifests / "stable-assets-manifest.json"
        nightly_manifest = manifests / "nightly-assets-manifest.json"
        shutil.copy2(args.assets_dir / "manifest.json", stable_manifest)
        shutil.copy2(args.assets_dir / "manifest.json", nightly_manifest)

        record_binary(stable_manifest, stable_version, stable_deb, stable_sbom, release_download_base)
        record_binary(nightly_manifest, nightly_version, nightly_deb, nightly_sbom, release_download_base)
        build_channel(stable_manifest, args.assets_dir, args.config_root / "profiles", "stable", dist, base_url)
        stable_channel_manifest = dist / "assets" / "stable" / "manifest.json"
        stable_channel_sha_before_nightly = file_sha256(stable_channel_manifest)
        stable_channel_packages_before_nightly = current_package_versions(stable_channel_manifest)
        build_channel(nightly_manifest, args.assets_dir, args.config_root / "profiles", "nightly", dist, base_url)
        if file_sha256(stable_channel_manifest) != stable_channel_sha_before_nightly:
            raise SystemExit("nightly channel build mutated stable manifest")
        if current_package_versions(stable_channel_manifest) != stable_channel_packages_before_nightly:
            raise SystemExit("nightly channel build mutated stable package records")

        install_script_url = f"{base_url}/install.sh"
        shutil.copy2(args.install_script, dist / "install.sh")
        corp_dir = args.work_dir / "corp"
        corp_dir.mkdir()
        corp_manifest = corp_dir / "manifest.json"
        shutil.copy2(stable_channel_manifest, corp_manifest)
        corp_manifest_url = corp_manifest.resolve().as_uri()
        write_report(
            args.work_dir / "report.json",
            base_url,
            stable_version,
            nightly_version,
            stable_manifest_url,
            nightly_manifest_url,
        )
        check_generated_release(base_url, stable_manifest_url, stable_deb, dist, "stable")
        check_generated_release(base_url, nightly_manifest_url, nightly_deb, dist, "nightly")
        if not args.skip_install:
            run_installed_glowup(
                install_script_url=install_script_url,
                release_base_url=base_url,
                stable_manifest_url=stable_manifest_url,
                nightly_manifest_url=nightly_manifest_url,
                corp_manifest_url=corp_manifest_url,
                nightly_deb=dist
                / "releases"
                / "download"
                / f"v{nightly_version}"
                / nightly_deb.name,
                stable_version=stable_version,
                nightly_version=nightly_version,
                arch=arch,
            )

    print(
        "local release glow-up passed: "
        f"stable={stable_version} nightly={nightly_version} dist={dist}"
    )
    return 0


def run(cmd: list[str], *, cwd: Path = PROJECT_ROOT, env: dict[str, str] | None = None) -> None:
    merged = os.environ.copy()
    if env:
        merged.update(env)
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, env=merged, check=True)


def deb_version(path: Path) -> str:
    return subprocess.check_output(["dpkg-deb", "-f", str(path), "Version"], text=True).strip()


def deb_arch(path: Path) -> str:
    arch = subprocess.check_output(["dpkg-deb", "-f", str(path), "Architecture"], text=True).strip()
    if arch not in {"amd64", "arm64"}:
        raise SystemExit(f"unsupported local glow-up deb architecture: {arch}")
    return arch


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def current_package_versions(manifest_path: Path) -> list[str]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    return sorted(
        package["version"]
        for package in manifest.get("packages", [])
        if isinstance(package, dict) and package.get("status") == "current"
    )


def next_patch_version(version: str) -> str:
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", version)
    if not match:
        raise SystemExit(f"local glow-up needs a semver package version, got {version}")
    major, minor, patch = match.groups()
    return f"{major}.{minor}.{int(patch) + 1}"


def repack_deb(input_deb: Path, output_deb: Path, bin_dir: Path, config_root: Path, manifest_url: str) -> None:
    output_deb.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "bash",
            "scripts/repack-deb.sh",
            "--manifest",
            manifest_url,
            str(input_deb),
            str(bin_dir),
            str(config_root),
            str(PROJECT_ROOT / "assets"),
            str(output_deb),
        ]
    )


def rewrite_deb_version(path: Path, version: str) -> None:
    with tempfile.TemporaryDirectory(prefix="capsem-deb-reversion-") as raw:
        root = Path(raw)
        unpacked = root / "deb"
        run(["dpkg-deb", "-R", str(path), str(unpacked)])
        control = unpacked / "DEBIAN" / "control"
        lines = control.read_text(encoding="utf-8").splitlines()
        control.write_text(
            "\n".join(
                f"Version: {version}" if line.startswith("Version: ") else line for line in lines
            )
            + "\n",
            encoding="utf-8",
        )
        manifest_origin = unpacked / "usr/share/capsem/assets/manifest-origin.json"
        if manifest_origin.exists():
            origin = json.loads(manifest_origin.read_text(encoding="utf-8"))
            stamped_at = (
                datetime.datetime.now(datetime.timezone.utc)
                .replace(microsecond=0)
                .isoformat()
                .replace("+00:00", "Z")
            )
            origin["package_version"] = version
            origin["packaged_at"] = stamped_at
            manifest_origin.write_text(
                json.dumps(origin, sort_keys=True) + "\n",
                encoding="utf-8",
            )
        run(["dpkg-deb", "-b", str(unpacked), str(path)])


def generate_sbom(output: Path, deb: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    run(["python3", "scripts/generate-host-binary-sbom.py", "--output", str(output), str(deb)])


def record_binary(manifest: Path, version: str, deb: Path, sbom: Path, release_download_base: str) -> None:
    run(
        [
            "cargo",
            "run",
            "-p",
            "capsem-admin",
            "--",
            "assets",
            "channel",
            "record-binary",
            "--manifest-path",
            str(manifest),
            "--version",
            version,
            "--artifact",
            str(deb),
            "--artifact",
            str(sbom),
        ],
        env={"CAPSEM_RELEASE_URL": release_download_base},
    )


def build_channel(
    manifest: Path,
    assets_dir: Path,
    profiles_dir: Path,
    channel: str,
    dist: Path,
    base_url: str,
) -> None:
    run(
        [
            "cargo",
            "run",
            "-p",
            "capsem-admin",
            "--",
            "assets",
            "channel",
            "build",
            "--manifest",
            manifest.resolve().as_uri(),
            "--assets-dir",
            str(assets_dir),
            "--profiles-dir",
            str(profiles_dir),
            "--channel",
            channel,
            "--manifest-version",
            "1.0.0",
            "--out-dir",
            str(dist),
        ],
        env={"CAPSEM_RELEASE_URL": f"{base_url}/releases/download"},
    )


def copy_artifact_tree(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def write_report(
    path: Path,
    base_url: str,
    stable_version: str,
    nightly_version: str,
    stable_manifest_url: str,
    nightly_manifest_url: str,
) -> None:
    path.write_text(
        json.dumps(
            {
                "schema": "capsem.local_release_glowup.v1",
                "base_url": base_url,
                "stable_version": stable_version,
                "nightly_version": nightly_version,
                "stable_manifest_url": stable_manifest_url,
                "nightly_manifest_url": nightly_manifest_url,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def check_generated_release(
    base_url: str,
    manifest_url: str,
    expected_deb: Path,
    dist: Path,
    channel: str,
) -> None:
    with urllib.request.urlopen(manifest_url, timeout=30) as response:
        manifest = json.loads(response.read())
    packages = manifest.get("packages")
    if not isinstance(packages, list) or not packages:
        raise SystemExit(f"generated {channel} release manifest has no packages")
    package = next((item for item in packages if item.get("name") == expected_deb.name), None)
    if package is None:
        raise SystemExit(f"generated {channel} release manifest missing {expected_deb.name}")
    if not str(package.get("url", "")).startswith(f"{base_url}/releases/download/"):
        raise SystemExit(f"generated {channel} package URL is not local: {package.get('url')}")
    missing_assets: list[str] = []
    for url in release_asset_urls(manifest):
        if url.startswith(f"{base_url}/"):
            relative = url.removeprefix(f"{base_url}/")
        elif url.startswith("/"):
            relative = url.removeprefix("/")
        else:
            raise SystemExit(f"generated VM asset URL is not local: {url}")
        if not (dist / relative).is_file():
            missing_assets.append(url)
    if missing_assets:
        raise SystemExit(
            f"generated {channel} release is missing VM asset blob(s): "
            + ", ".join(missing_assets)
        )


def release_asset_urls(manifest: dict[str, object]) -> list[str]:
    urls: list[str] = []
    profiles = manifest.get("profiles")
    if not isinstance(profiles, dict):
        raise SystemExit("generated stable release manifest has no profile graph")
    for profile in profiles.values():
        if not isinstance(profile, dict):
            continue
        architectures = profile.get("architectures")
        if not isinstance(architectures, list):
            continue
        for architecture in architectures:
            if not isinstance(architecture, dict):
                continue
            for section in ("images", "evidence"):
                rows = architecture.get(section)
                if not isinstance(rows, list):
                    continue
                for row in rows:
                    if isinstance(row, dict) and isinstance(row.get("url"), str):
                        url = row["url"]
                        if "/assets/releases/" in url:
                            urls.append(url)
    if not urls:
        raise SystemExit("generated stable release manifest has no VM asset URLs")
    return urls


def run_installed_glowup(
    *,
    install_script_url: str,
    release_base_url: str,
    stable_manifest_url: str,
    nightly_manifest_url: str,
    corp_manifest_url: str,
    nightly_deb: Path,
    stable_version: str,
    nightly_version: str,
    arch: str,
) -> None:
    script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
check_service_installed() {{
  "$HOME/.capsem/bin/capsem" status | tee "$HOME/.capsem/service-status.txt"
  grep -F "Installed: true" "$HOME/.capsem/service-status.txt"
  grep -F "Running:   true" "$HOME/.capsem/service-status.txt"
  grep -F "Service:   ok" "$HOME/.capsem/service-status.txt"
  grep -F "Gateway:   ok" "$HOME/.capsem/service-status.txt"
}}
check_binary_versions() {{
  expected="$1"
  for bin in {' '.join(HOST_BINARIES)}; do
    test -x "$HOME/.capsem/bin/$bin"
    if [ "$bin" = "capsem" ]; then
      "$HOME/.capsem/bin/$bin" version > "$HOME/.capsem/$bin.version" 2>&1
    else
      "$HOME/.capsem/bin/$bin" --version > "$HOME/.capsem/$bin.version" 2>&1
    fi
    grep -F "$expected" "$HOME/.capsem/$bin.version"
  done
}}
check_update_log() {{
  event="$1"
  source="$2"
  grep -F '"event":"'"$event"'"' "$HOME/.capsem/logs/update.log"
  grep -F '"source":"'"$source"'"' "$HOME/.capsem/logs/update.log"
}}
compiled_binary_version={stable_version}
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=stable CAPSEM_RELEASE_BASE_URL={release_base_url} sh
test -x "$HOME/.capsem/bin/capsem"
test -f "$HOME/.capsem/assets/manifest.json"
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
stable_manifest_sha=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
check_binary_versions {stable_version}
check_service_installed
test -f "$HOME/.capsem/logs/install.log"
grep -F "event=manifest_source source={stable_manifest_url}" "$HOME/.capsem/logs/install.log"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/logs/install.log"
grep -F "event=assets_hydrated" "$HOME/.capsem/logs/install.log"
grep -F "event=service_install_invoked" "$HOME/.capsem/logs/install.log"
check_update_log asset_update_complete {stable_manifest_url}
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {stable_version}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {nightly_manifest_url}
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {nightly_manifest_url}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {stable_manifest_url}
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {stable_manifest_url}
stable_manifest_sha_after_switch=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
test "$stable_manifest_sha" = "$stable_manifest_sha_after_switch"
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {corp_manifest_url}
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {corp_manifest_url}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {stable_manifest_url}
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {stable_manifest_url}
stable_manifest_sha_after_corp_switch=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
test "$stable_manifest_sha" = "$stable_manifest_sha_after_corp_switch"
cp {nightly_deb} {nightly_deb}.good
printf 'corrupt nightly package' > {nightly_deb}
set +e
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_MANIFEST_URL={nightly_manifest_url} "$HOME/.capsem/bin/capsem" update --yes > "$HOME/.capsem/bad-update.log" 2>&1
bad_update_status=$?
set -e
test "$bad_update_status" -ne 0
grep -E "sha256 mismatch|size mismatch" "$HOME/.capsem/bad-update.log"
check_update_log binary_update_failed {nightly_manifest_url}
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {stable_version}
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{stable_version}"' "$HOME/.capsem/assets/manifest-origin.json"
mv {nightly_deb}.good {nightly_deb}
rm -f "$HOME/.capsem/updates/installers/Capsem_{nightly_version}_{arch}.deb"
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_MANIFEST_URL={nightly_manifest_url} "$HOME/.capsem/bin/capsem" update --yes
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{nightly_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log binary_update_complete {nightly_manifest_url}
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {nightly_version}
test -f "$HOME/.capsem/updates/installers/Capsem_{nightly_version}_{arch}.deb"
# The hermetic local nightly package rewrites Debian metadata/provenance to
# prove the package-manager path without recompiling a second binary cohort.
# Real public release packages are separately executed by the post-deploy gate.
check_binary_versions "$compiled_binary_version"
check_service_installed
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {corp_manifest_url}
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{nightly_version}"' "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {corp_manifest_url}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {corp_manifest_url}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {stable_manifest_url}
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
check_update_log asset_update_complete {stable_manifest_url}
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=nightly CAPSEM_RELEASE_BASE_URL={release_base_url} sh
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-origin.json"
grep -F '"package_version": "{nightly_version}"' "$HOME/.capsem/assets/manifest-origin.json"
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {nightly_version}
check_binary_versions "$compiled_binary_version"
check_service_installed
"""
    run(["bash", "-lc", script])


@contextlib.contextmanager
def local_release_server(root: Path):
    class ThreadingServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
        daemon_threads = True

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(root))
    server = ThreadingServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        host, port = server.server_address
        yield f"http://{host}:{port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


if __name__ == "__main__":
    raise SystemExit(main())
