#!/usr/bin/env python3
"""Hermetic local release glow-up for the install test rail.

This script intentionally uses the same build commands as the release lane:

* a Tauri-built .deb is repacked by ``scripts/repack-deb.sh``;
* host binary SBOMs are generated by ``scripts/generate-host-binary-sbom.py``;
* binary metadata is recorded by ``capsem-admin assets channel record-binary``;
* release-channel manifests are generated by ``capsem-admin assets channel build``;
* ``site/public/install.sh`` installs from a local HTTP release channel;
* the installed CLI switches stable -> nightly -> stable through ``--channel``;
* an explicit corporate manifest locks the machine onto that corporate channel.

No hand-authored release manifest is created here.
"""

from __future__ import annotations

import argparse
import contextlib
import errno
import functools
import hashlib
import http.server
import json
import os
from pathlib import Path
import shutil
import socketserver
import subprocess
import threading
import urllib.request


PROJECT_ROOT = Path(__file__).resolve().parents[1]
HOST_BINARIES = (
    "capsem",
    "capsem-service",
    "capsem-process",
    "capsem-tui",
    "capsem-mcp",
    "capsem-mcp-aggregator",
    "capsem-mcp-builtin",
    "capsem-gateway",
    "capsem-tray",
    "capsem-admin",
)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-deb", required=True, type=Path)
    parser.add_argument("--bin-dir", required=True, type=Path)
    parser.add_argument("--assets-dir", required=True, type=Path)
    parser.add_argument("--config-root", required=True, type=Path)
    parser.add_argument("--install-script", default=PROJECT_ROOT / "site/public/install.sh", type=Path)
    parser.add_argument("--work-dir", default=PROJECT_ROOT / "target/local-release-glowup", type=Path)
    parser.add_argument("--skip-install", action="store_true")
    args = parser.parse_args()

    if args.work_dir.exists():
        shutil.rmtree(args.work_dir)
    args.work_dir.mkdir(parents=True)
    dist = args.work_dir / "dist"
    artifacts = args.work_dir / "artifacts"
    manifests = args.work_dir / "manifests"
    for path in (dist, artifacts, manifests):
        path.mkdir(parents=True)
    report_disk_capacity(args.work_dir, "local release glow-up start")

    stable_version = deb_version(args.input_deb)
    nightly_version = stable_version
    arch = deb_arch(args.input_deb)

    with local_release_server(dist) as base_url:
        stable_manifest_url = f"{base_url}/assets/stable/manifest.json"
        nightly_manifest_url = f"{base_url}/assets/nightly/manifest.json"
        stable_download_base = f"{base_url}/releases/download/stable"
        nightly_download_base = f"{base_url}/releases/download/nightly"
        stable_deb = artifacts / "stable" / f"v{stable_version}" / f"Capsem_{stable_version}_{arch}.deb"
        nightly_deb = artifacts / "nightly" / f"v{nightly_version}" / f"Capsem_{nightly_version}_{arch}.deb"
        stable_sbom = artifacts / "stable" / f"v{stable_version}" / "capsem-sbom.spdx.json"
        nightly_sbom = artifacts / "nightly" / f"v{nightly_version}" / "capsem-sbom.spdx.json"

        repack_deb(
            args.input_deb,
            stable_deb,
            args.bin_dir,
            args.config_root,
            args.assets_dir,
            stable_manifest_url,
        )
        repack_deb(
            args.input_deb,
            nightly_deb,
            args.bin_dir,
            args.config_root,
            args.assets_dir,
            nightly_manifest_url,
        )
        generate_sbom(stable_sbom, stable_deb)
        generate_sbom(nightly_sbom, nightly_deb)

        # Serve release artifacts from the exact URL shape used by release metadata.
        copy_artifact_tree(stable_deb, dist / "releases" / "download" / "stable" / f"v{stable_version}" / stable_deb.name)
        copy_artifact_tree(stable_sbom, dist / "releases" / "download" / "stable" / f"v{stable_version}" / stable_sbom.name)
        copy_artifact_tree(nightly_deb, dist / "releases" / "download" / "nightly" / f"v{nightly_version}" / nightly_deb.name)
        copy_artifact_tree(nightly_sbom, dist / "releases" / "download" / "nightly" / f"v{nightly_version}" / nightly_sbom.name)

        stable_manifest = manifests / "stable-assets-manifest.json"
        nightly_manifest = manifests / "nightly-assets-manifest.json"
        shutil.copy2(args.assets_dir / "manifest.json", stable_manifest)
        shutil.copy2(args.assets_dir / "manifest.json", nightly_manifest)
        report_disk_capacity(args.work_dir, "before immutable VM blob staging")
        stage_vm_asset_blobs(stable_manifest, args.assets_dir, dist)

        record_binary(stable_manifest, stable_version, stable_deb, stable_sbom, stable_download_base)
        record_binary(nightly_manifest, nightly_version, nightly_deb, nightly_sbom, nightly_download_base)
        build_channel(stable_manifest, args.assets_dir, args.config_root / "profiles", "stable", dist, base_url)
        stable_channel_manifest = dist / "assets" / "stable" / "manifest.json"
        stable_channel_sha_before_nightly = file_sha256(stable_channel_manifest)
        stable_channel_packages_before_nightly = current_package_versions(stable_channel_manifest)
        build_channel(nightly_manifest, args.assets_dir, args.config_root / "profiles", "nightly", dist, base_url)
        if file_sha256(stable_channel_manifest) != stable_channel_sha_before_nightly:
            raise SystemExit("nightly channel build mutated stable manifest")
        if current_package_versions(stable_channel_manifest) != stable_channel_packages_before_nightly:
            raise SystemExit("nightly channel build mutated stable package records")

        install_script_url = f"{base_url}/install.sh"
        shutil.copy2(args.install_script, dist / "install.sh")
        corp_dir = dist / "corp"
        corp_dir.mkdir()
        corp_manifest = corp_dir / "manifest.json"
        shutil.copy2(stable_channel_manifest, corp_manifest)
        corp_manifest_url = f"{base_url}/corp/manifest.json"
        write_report(
            args.work_dir / "report.json",
            base_url,
            stable_version,
            nightly_version,
            stable_manifest_url,
            nightly_manifest_url,
        )
        check_generated_release(base_url, stable_manifest_url, stable_deb, dist, "stable")
        check_generated_release(base_url, nightly_manifest_url, nightly_deb, dist, "nightly")
        if not args.skip_install:
            run_installed_glowup(
                install_script_url=install_script_url,
                release_base_url=base_url,
                stable_manifest_url=stable_manifest_url,
                nightly_manifest_url=nightly_manifest_url,
                corp_manifest_url=corp_manifest_url,
                package_version=stable_version,
            )

    print(
        "local release glow-up passed: "
        f"stable={stable_version} nightly={nightly_version} dist={dist}"
    )
    return 0


def run(cmd: list[str], *, cwd: Path = PROJECT_ROOT, env: dict[str, str] | None = None) -> None:
    merged = os.environ.copy()
    if env:
        merged.update(env)
    print("+ " + " ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=cwd, env=merged, check=True)


def deb_version(path: Path) -> str:
    return subprocess.check_output(["dpkg-deb", "-f", str(path), "Version"], text=True).strip()


def deb_arch(path: Path) -> str:
    arch = subprocess.check_output(["dpkg-deb", "-f", str(path), "Architecture"], text=True).strip()
    if arch not in {"amd64", "arm64"}:
        raise SystemExit(f"unsupported local glow-up deb architecture: {arch}")
    return arch


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def current_package_versions(manifest_path: Path) -> list[str]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    return sorted(
        package["version"]
        for package in manifest.get("packages", [])
        if isinstance(package, dict) and package.get("status") == "current"
    )


def report_disk_capacity(path: Path, label: str) -> None:
    usage = shutil.disk_usage(path)
    gib = 1024**3
    print(
        f"Disk capacity ({label}): {usage.free / gib:.1f} GiB free "
        f"of {usage.total / gib:.1f} GiB",
        flush=True,
    )


def repack_deb(
    input_deb: Path,
    output_deb: Path,
    bin_dir: Path,
    config_root: Path,
    assets_dir: Path,
    manifest_url: str,
) -> None:
    output_deb.parent.mkdir(parents=True, exist_ok=True)
    run(
        [
            "bash",
            "scripts/repack-deb.sh",
            "--manifest",
            manifest_url,
            str(input_deb),
            str(bin_dir),
            str(config_root),
            str(assets_dir),
            str(output_deb),
        ]
    )


def generate_sbom(output: Path, deb: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    run(["python3", "scripts/generate-host-binary-sbom.py", "--output", str(output), str(deb)])


def record_binary(manifest: Path, version: str, deb: Path, sbom: Path, release_download_base: str) -> None:
    run(
        [
            "cargo",
            "run",
            "-p",
            "capsem-admin",
            "--",
            "assets",
            "channel",
            "record-binary",
            "--manifest-path",
            str(manifest),
            "--version",
            version,
            "--artifact",
            str(deb),
            "--artifact",
            str(sbom),
        ],
        env={"CAPSEM_RELEASE_URL": release_download_base},
    )


def build_channel(
    manifest: Path,
    assets_dir: Path,
    profiles_dir: Path,
    channel: str,
    dist: Path,
    base_url: str,
) -> None:
    run(
        [
            "cargo",
            "run",
            "-p",
            "capsem-admin",
            "--",
            "assets",
            "channel",
            "build",
            "--manifest",
            manifest.resolve().as_uri(),
            "--assets-dir",
            str(assets_dir),
            "--profiles-dir",
            str(profiles_dir),
            "--channel",
            channel,
            "--manifest-version",
            "1.0.0",
            "--asset-source-base",
            f"{base_url}/assets/releases/{{asset_version}}",
            "--out-dir",
            str(dist),
        ],
        env={"CAPSEM_RELEASE_URL": f"{base_url}/releases/download/{channel}"},
    )


def copy_artifact_tree(source: Path, target: Path) -> None:
    """Stage an immutable artifact without duplicating it when possible.

    The local release server only reads these files.  A same-filesystem
    hardlink therefore preserves the exact bytes while avoiding another copy
    of the multi-gigabyte VM asset cohort late in ``just test``.  macOS and
    Linux both support this path.  Filesystems that cannot hardlink across the
    source/dist boundary retain the portable copy behavior.
    """
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(source, target)
    except OSError as error:
        fallback_errors = {
            errno.EACCES,
            errno.EPERM,
            errno.EXDEV,
            errno.ENOTSUP,
            errno.EOPNOTSUPP,
        }
        if error.errno not in fallback_errors:
            raise
        shutil.copy2(source, target)


def stage_vm_asset_blobs(manifest_path: Path, assets_dir: Path, dist: Path) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    assets = manifest.get("assets")
    if not isinstance(assets, dict):
        raise SystemExit("local glow-up asset manifest has no assets object")
    version = assets.get("current")
    releases = assets.get("releases")
    release = releases.get(version) if isinstance(releases, dict) else None
    arches = release.get("arches") if isinstance(release, dict) else None
    if not isinstance(version, str) or not isinstance(arches, dict):
        raise SystemExit("local glow-up asset manifest has no current release arches")
    release_dir = dist / "assets" / "releases" / version
    release_dir.mkdir(parents=True, exist_ok=True)
    for arch, rows in arches.items():
        if not isinstance(arch, str) or not isinstance(rows, dict):
            raise SystemExit("local glow-up asset manifest has invalid architecture rows")
        for logical_name, descriptor in rows.items():
            source = assets_dir / arch / logical_name
            if not source.is_file() or not isinstance(descriptor, dict):
                raise SystemExit(f"local glow-up VM asset is missing: {source}")
            expected_size = descriptor.get("size")
            if source.stat().st_size != expected_size:
                raise SystemExit(f"local glow-up VM asset size mismatch: {source}")
            # The immediately following capsem-admin channel build validates
            # every source digest against this same manifest.
            copy_artifact_tree(source, release_dir / f"{arch}-{logical_name}")


def write_report(
    path: Path,
    base_url: str,
    stable_version: str,
    nightly_version: str,
    stable_manifest_url: str,
    nightly_manifest_url: str,
) -> None:
    path.write_text(
        json.dumps(
            {
                "schema": "capsem.local_release_glowup.v1",
                "base_url": base_url,
                "stable_version": stable_version,
                "nightly_version": nightly_version,
                "stable_manifest_url": stable_manifest_url,
                "nightly_manifest_url": nightly_manifest_url,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def check_generated_release(
    base_url: str,
    manifest_url: str,
    expected_deb: Path,
    dist: Path,
    channel: str,
) -> None:
    request = urllib.request.Request(
        manifest_url,
        headers={"User-Agent": "capsem-release-client/1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        manifest = json.loads(response.read())
    packages = manifest.get("packages")
    if not isinstance(packages, list) or not packages:
        raise SystemExit(f"generated {channel} release manifest has no packages")
    package = next((item for item in packages if item.get("name") == expected_deb.name), None)
    if package is None:
        raise SystemExit(f"generated {channel} release manifest missing {expected_deb.name}")
    package_url = str(package.get("url", ""))
    if not package_url.startswith(f"{base_url}/releases/download/"):
        raise SystemExit(f"generated {channel} package URL is not local: {package.get('url')}")
    package_path = dist / package_url.removeprefix(f"{base_url}/")
    if not package_path.is_file():
        raise SystemExit(f"generated {channel} package URL is not served: {package_url}")
    missing_assets: list[str] = []
    for url in release_asset_urls(manifest):
        if url.startswith(f"{base_url}/"):
            relative = url.removeprefix(f"{base_url}/")
        else:
            raise SystemExit(f"generated VM asset URL is not absolute and local: {url}")
        if not (dist / relative).is_file():
            missing_assets.append(url)
    if missing_assets:
        raise SystemExit(
            f"generated {channel} release is missing VM asset blob(s): "
            + ", ".join(missing_assets)
        )


def release_asset_urls(manifest: dict[str, object]) -> list[str]:
    urls: list[str] = []
    profiles = manifest.get("profiles")
    if not isinstance(profiles, dict):
        raise SystemExit("generated stable release manifest has no profile graph")
    for profile in profiles.values():
        if not isinstance(profile, dict):
            continue
        architectures = profile.get("architectures")
        if not isinstance(architectures, list):
            continue
        for architecture in architectures:
            if not isinstance(architecture, dict):
                continue
            for section in ("images", "evidence"):
                rows = architecture.get(section)
                if not isinstance(rows, list):
                    continue
                for row in rows:
                    if isinstance(row, dict) and isinstance(row.get("url"), str):
                        url = row["url"]
                        if "/assets/releases/" in url:
                            urls.append(url)
    if not urls:
        raise SystemExit("generated stable release manifest has no VM asset URLs")
    return urls


def run_installed_glowup(
    *,
    install_script_url: str,
    release_base_url: str,
    stable_manifest_url: str,
    nightly_manifest_url: str,
    corp_manifest_url: str,
    package_version: str,
) -> None:
    script = f"""
set -euxo pipefail
export DEBIAN_FRONTEND=noninteractive
check_service_installed() {{
  "$HOME/.capsem/bin/capsem" status | tee "$HOME/.capsem/service-status.txt"
  grep -F "Installed: true" "$HOME/.capsem/service-status.txt"
  grep -F "Running:   true" "$HOME/.capsem/service-status.txt"
  grep -F "Service:   ok" "$HOME/.capsem/service-status.txt"
  grep -F "Gateway:   ok" "$HOME/.capsem/service-status.txt"
}}
verify_installed_release() {{
  manifest_url="$1"
  channel="$2"
  package_version="$3"
  python3 scripts/verify-installed-release.py \
    --capsem "$HOME/.capsem/bin/capsem" \
    --manifest-url "$manifest_url" \
    --channel "$channel" \
    --package-version "$package_version"
}}
check_binary_versions() {{
  expected="$1"
  for bin in {' '.join(HOST_BINARIES)}; do
    test -x "$HOME/.capsem/bin/$bin"
    if [ "$bin" = "capsem" ]; then
      "$HOME/.capsem/bin/$bin" version > "$HOME/.capsem/$bin.version" 2>&1
    else
      "$HOME/.capsem/bin/$bin" --version > "$HOME/.capsem/$bin.version" 2>&1
    fi
    grep -F "$expected" "$HOME/.capsem/$bin.version"
  done
}}
check_update_log() {{
  event="$1"
  source="$2"
  python3 - "$event" "$source" "$HOME/.capsem/logs/update.log" <<'PY'
import json
import pathlib
import sys
event, source, path = sys.argv[1:]
rows = [json.loads(line) for line in pathlib.Path(path).read_text().splitlines()]
if not any(row.get("event") == event and row.get("source") == source for row in rows):
    raise SystemExit(f"missing correlated update audit event={{event}} source={{source}}")
PY
}}
check_origin_channel() {{
  channel="$1"
  source="$2"
  locked="$3"
  python3 - "$channel" "$source" "$locked" "$HOME/.capsem/assets/manifest-metadata.json" <<'PY'
import json
import pathlib
import sys
channel, source, locked, path = sys.argv[1:]
origin = json.loads(pathlib.Path(path).read_text())
assert origin["channel"] == channel, origin
assert origin["manifest_url"] == source, origin
assert origin["channel_locked"] is (locked == "true"), origin
PY
}}
release_channels_url={release_base_url}/channels.json
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=stable CAPSEM_RELEASE_BASE_URL={release_base_url} sh
test -x "$HOME/.capsem/bin/capsem"
test -f "$HOME/.capsem/assets/manifest.json"
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
stable_manifest_sha=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
check_binary_versions {package_version}
check_service_installed
verify_installed_release {stable_manifest_url} stable {package_version}
test -f "$HOME/.capsem/logs/install.log"
grep -F "event=manifest_source source={stable_manifest_url}" "$HOME/.capsem/logs/install.log"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/logs/install.log"
grep -F "event=assets_hydrated" "$HOME/.capsem/logs/install.log"
grep -F "event=service_install_invoked" "$HOME/.capsem/logs/install.log"
check_update_log asset_update_complete {stable_manifest_url}
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {package_version}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --assets --channel nightly
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel nightly {nightly_manifest_url} false
check_update_log asset_update_complete {nightly_manifest_url}
verify_installed_release {nightly_manifest_url} nightly {package_version}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --assets --channel stable
grep -F {stable_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel stable {stable_manifest_url} false
check_update_log asset_update_complete {stable_manifest_url}
verify_installed_release {stable_manifest_url} stable {package_version}
stable_manifest_sha_after_switch=$(sha256sum "$HOME/.capsem/assets/manifest.json" | cut -d' ' -f1)
test "$stable_manifest_sha" = "$stable_manifest_sha_after_switch"
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {corp_manifest_url}
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
check_origin_channel corp {corp_manifest_url} true
check_update_log asset_update_complete {corp_manifest_url}
verify_installed_release {corp_manifest_url} corp {package_version}
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets
grep -F {corp_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
check_update_log asset_update_complete {corp_manifest_url}
set +e
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" CAPSEM_RELEASE_CHANNELS_URL="$release_channels_url" "$HOME/.capsem/bin/capsem" update --assets --channel nightly > "$HOME/.capsem/corp-escape.log" 2>&1
corp_escape_status=$?
set -e
test "$corp_escape_status" -ne 0
grep -F "corporate channel is locked" "$HOME/.capsem/corp-escape.log"
check_origin_channel corp {corp_manifest_url} true
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {package_version}
set +e
CAPSEM_HOME="$HOME/.capsem" CAPSEM_RUN_DIR="$HOME/.capsem/run" "$HOME/.capsem/bin/capsem" update --assets --manifest {nightly_manifest_url} > "$HOME/.capsem/corp-repoint.log" 2>&1
corp_repoint_status=$?
set -e
test "$corp_repoint_status" -ne 0
grep -F "corporate channel is locked to" "$HOME/.capsem/corp-repoint.log"
check_origin_channel corp {corp_manifest_url} true
sudo apt-get remove --purge -y capsem || true
rm -rf "$HOME/.capsem"
curl -fsSL {install_script_url} | CAPSEM_CHANNEL=nightly CAPSEM_RELEASE_BASE_URL={release_base_url} sh
grep -F {nightly_manifest_url} "$HOME/.capsem/assets/manifest-metadata.json"
grep -F '"package_version": "{package_version}"' "$HOME/.capsem/assets/manifest-metadata.json"
dpkg-query -W -f='${{Version}}' capsem | grep -Fx {package_version}
check_binary_versions {package_version}
check_service_installed
verify_installed_release {nightly_manifest_url} nightly {package_version}
"""
    run(["bash", "-lc", script])


@contextlib.contextmanager
def local_release_server(root: Path):
    class ThreadingServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
        daemon_threads = True

    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(root))
    server = ThreadingServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        host, port = server.server_address
        yield f"http://{host}:{port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


if __name__ == "__main__":
    raise SystemExit(main())
