"""Offline OCI acceptance through a real, disposable Capsem guest.

No model, credential or MCP requests are generated by this fixture. Network
attempts are denied inside the container before reaching host routing.
Execution and filesystem behavior are observed through the existing service boundary.
"""

import contextlib
import hashlib
import json
import re
import sqlite3
from pathlib import Path

import pytest
from helpers.constants import CODE_PROFILE_ID, DEFAULT_CPUS, DEFAULT_RAM_MB
from helpers.service import (
    ServiceInstance,
    vm_name,
    vm_session_db_path,
    wait_exec_ready,
)

pytestmark = pytest.mark.integration
FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "oci"


@pytest.fixture
def oci_vm():
    service = ServiceInstance()
    name = vm_name("oci")
    try:
        service.start()
        client = service.client()
        client.post(
            "/vms/create",
            {
                "name": name,
                "profile_id": CODE_PROFILE_ID,
                "ram_mb": DEFAULT_RAM_MB,
                "cpus": DEFAULT_CPUS,
            },
            timeout=90,
        )
        assert wait_exec_ready(client, name)
        yield service, client, name
    finally:
        service.stop()


def test_oci_kernel_and_runtime_are_functional(oci_vm, tmp_path):
    _, client, name = oci_vm
    result = client.post(
        f"/vms/{name}/exec",
        {
            "command": "set -eu; uname -rm; runc --version; "
            'sha256sum "$(command -v runc)"; '
            "test -f /sys/fs/cgroup/cgroup.controllers; "
            "unshare --mount --pid --uts --ipc --net --fork /bin/true; "
            "cat /sys/fs/cgroup/cgroup.controllers",
            "timeout_secs": 15,
        },
    )
    (tmp_path / "oci-platform.json").write_text(json.dumps(result, indent=2))
    assert result["exit_code"] == 0, result
    assert {"cpu", "memory", "pids"} <= set(result["stdout"].split()), result


def test_offline_oci_adversarial_suite(oci_vm, tmp_path):
    service, client, name = oci_vm
    for filename in ("bundle.py", "probe.py"):
        payload = (FIXTURES / filename).read_bytes()
        result = client.post_bytes(
            f"/vms/{name}/files/content?path=oci/{filename}", payload
        )
        assert result == {"success": True, "size": len(payload)}
    payload = bytes(range(256))
    assert client.post_bytes(
        f"/vms/{name}/files/content?path=oci/input.bin", payload
    ) == {
        "success": True,
        "size": len(payload),
    }
    result = client.post(
        f"/vms/{name}/exec",
        {
            "command": "/usr/bin/python3 /root/oci/probe.py",
            "timeout_secs": 180,
        },
        timeout=200,
    )
    (tmp_path / "oci-result.json").write_text(json.dumps(result, indent=2))
    assert result["exit_code"] == 0, result
    output = result["stdout"] + result["stderr"]
    digest = re.search(r"OCI_ROOTFS_SHA256=([0-9a-f]{64})", output)
    assert digest, output
    assert "Ran 8 tests" in output and "OK" in output, output
    status, contents = client.get_bytes(
        f"/vms/{name}/files/content?path=oci/output.bin"
    )
    assert status == 200 and contents == payload
    status, manifest = client.get_bytes(
        f"/vms/{name}/files/content?path=oci/manifest.json"
    )
    assert status == 200
    assert hashlib.sha256(manifest).hexdigest() == digest[1]
    (tmp_path / "oci-rootfs-manifest.json").write_bytes(manifest)
    db_path = vm_session_db_path(service.tmp_dir, client, name)
    service.stop(cleanup=False)  # The DB-owned shutdown barrier makes reads exact.
    with contextlib.closing(sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)) as db:
        rows = db.execute(
            "SELECT exit_code, source, stdout_bytes, stderr_bytes, credential_ref "
            "FROM exec_events WHERE command = ?",
            ("/usr/bin/python3 /root/oci/probe.py",),
        ).fetchall()
    assert rows == [
        (0, "api", len(result["stdout"].encode()), len(result["stderr"].encode()), None)
    ]


def test_fresh_session_does_not_inherit_container_files(oci_vm):
    _, client, name = oci_vm
    marker = "/var/tmp/oci-session-marker"
    first = client.post(
        f"/vms/{name}/exec",
        {
            "command": f"test ! -e {marker} && printf private > {marker}",
            "timeout_secs": 10,
        },
    )
    assert first["exit_code"] == 0, first
    other = vm_name("oci-fresh")
    client.post(
        "/vms/create",
        {
            "name": other,
            "profile_id": CODE_PROFILE_ID,
            "ram_mb": DEFAULT_RAM_MB,
            "cpus": DEFAULT_CPUS,
        },
        timeout=90,
    )
    try:
        assert wait_exec_ready(client, other)
        second = client.post(
            f"/vms/{other}/exec",
            {
                "command": f"test ! -e {marker}",
                "timeout_secs": 10,
            },
        )
        assert second["exit_code"] == 0, second
    finally:
        client.delete(f"/vms/{other}/delete")
