"""Generated from Capsem OpenAPI. Do not edit."""

from .create_vm import create_vm as create_vm
from .delete_vm import delete_vm as delete_vm
from .download_vm_file import download_vm_file as download_vm_file
from .exec_vm import exec_vm as exec_vm
from .fork_vm import fork_vm as fork_vm
from .get_hypervisor_info import get_hypervisor_info as get_hypervisor_info
from .get_hypervisor_logs import get_hypervisor_logs as get_hypervisor_logs
from .get_update_status import get_update_status as get_update_status
from .get_vm_changes import get_vm_changes as get_vm_changes
from .get_vm_history import get_vm_history as get_vm_history
from .get_vm_info import get_vm_info as get_vm_info
from .get_vm_logs import get_vm_logs as get_vm_logs
from .get_vm_snapshots_status import get_vm_snapshots_status as get_vm_snapshots_status
from .get_vm_stats_detail import get_vm_stats_detail as get_vm_stats_detail
from .get_vm_stats_summary import get_vm_stats_summary as get_vm_stats_summary
from .get_vm_status import get_vm_status as get_vm_status
from .get_vm_timeline import get_vm_timeline as get_vm_timeline
from .list_profiles import list_profiles as list_profiles
from .list_vm_files import list_vm_files as list_vm_files
from .list_vm_snapshots import list_vm_snapshots as list_vm_snapshots
from .list_vms import list_vms as list_vms
from .pause_vm import pause_vm as pause_vm
from .restart_hypervisor import restart_hypervisor as restart_hypervisor
from .resume_vm import resume_vm as resume_vm
from .start_vm import start_vm as start_vm
from .stop_vm import stop_vm as stop_vm
from .update_hypervisor import update_hypervisor as update_hypervisor
from .upload_vm_file import upload_vm_file as upload_vm_file
