// @ts-nocheck
// Vite plugin: embeds the latest release notes at compile time.
// Reads LATEST_RELEASE.md (generated by `just cut-release`) and exports
// a virtual module `virtual:release-notes` with { html, version }.
// Type-checking disabled: this runs at build time in Vite's Node context, not in the app.

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const VIRTUAL_ID = 'virtual:release-notes';
const RESOLVED_ID = '\0' + VIRTUAL_ID;
const __dirname = dirname(fileURLToPath(import.meta.url));

const FALLBACK = `export const html = '<p>No release notes available.</p>';\nexport const version = '';`;

export default function releaseNotesPlugin() {
  return {
    name: 'release-notes',
    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
    },
    load(id) {
      if (id !== RESOLVED_ID) return;

      const filePath = resolve(__dirname, '../../LATEST_RELEASE.md');
      let raw;
      try {
        raw = readFileSync(filePath, 'utf-8');
      } catch {
        return FALLBACK;
      }

      // Format: "version: X.Y.Z\n---\n<markdown body>"
      const sep = raw.indexOf('---');
      if (sep === -1) return FALLBACK;

      const header = raw.slice(0, sep).trim();
      const version = header.replace(/^version:\s*/, '').trim();
      const body = raw.slice(sep + 3).trim();
      if (!body) return FALLBACK;

      const html = marked.parse(body, { async: false });
      const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

      return `export const html = \`${escaped}\`;\nexport const version = '${version}';`;
    },
  };
}
