// AUTO-GENERATED by scripts/generate_schema.py -- DO NOT EDIT
// Source: config/defaults.json (from guest/config/*.toml)
//
// Regenerate: just run (or just test)

import type { ResolvedSetting, SettingsNode, McpServerInfo, McpToolInfo, McpPolicyInfo } from './types';

// Helper: creates a mock setting with sensible defaults for empty fields.
function ms(overrides: Partial<ResolvedSetting> & { id: string; category: string; name: string; setting_type: ResolvedSetting['setting_type'] }): ResolvedSetting {
  return {
    description: '',
    default_value: overrides.setting_type === 'bool' ? false : overrides.setting_type === 'number' ? 0 : '',
    effective_value: overrides.setting_type === 'bool' ? false : overrides.setting_type === 'number' ? 0 : '',
    source: 'default',
    modified: null,
    corp_locked: false,
    enabled_by: null,
    enabled: true,
    metadata: { domains: [], choices: [], min: null, max: null, rules: {} },
    ...overrides,
  };
}

// Helper: wrap a flat ResolvedSetting into a SettingsLeaf node.
function leaf(s: ResolvedSetting): SettingsNode {
  return { kind: 'leaf', ...s };
}

export let mockSettings: ResolvedSetting[] = [
  ms({     id: 'app.auto_update', category: 'App', name: 'Auto-check for updates', setting_type: 'bool', description: 'Check for new Capsem versions on launch', default_value: true, effective_value: true }),
  ms({     id: 'ai.anthropic.allow', category: 'Anthropic', name: 'Allow Anthropic', setting_type: 'bool', description: 'Enable API access to Anthropic (*.anthropic.com).', default_value: true, effective_value: true, metadata: { domains: [], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: true, put: false, delete: false, other: false } } } }),
  ms({     id: 'ai.anthropic.api_key', category: 'Anthropic', name: 'Anthropic API Key', setting_type: 'apikey', description: 'API key for Anthropic. Injected as ANTHROPIC_API_KEY env var.', default_value: '', effective_value: '', enabled_by: 'ai.anthropic.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, docs_url: 'https://console.anthropic.com/settings/keys', prefix: 'sk-ant-' } }),
  ms({     id: 'ai.anthropic.domains', category: 'Anthropic', name: 'Anthropic Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: '*.anthropic.com, *.claude.com', effective_value: '*.anthropic.com, *.claude.com', enabled_by: 'ai.anthropic.allow', enabled: false }),
  ms({     id: 'ai.anthropic.claude.settings_json', category: 'Claude Code', name: 'Claude Code settings.json', setting_type: 'file', description: 'Content for /root/.claude/settings.json. Bypass permissions, disable telemetry/updates for sandboxed execution.', default_value: { path: '/root/.claude/settings.json', content: '{"permissions":{"defaultMode":"bypassPermissions"},"env":{"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC":"1"}}' }, effective_value: { path: '/root/.claude/settings.json', content: '{"permissions":{"defaultMode":"bypassPermissions"},"env":{"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC":"1"}}' }, enabled_by: 'ai.anthropic.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.anthropic.claude.state_json', category: 'Claude Code', name: 'Claude Code state (.claude.json)', setting_type: 'file', description: 'Content for /root/.claude.json. Skips onboarding, trust dialogs, and keybinding prompts.', default_value: { path: '/root/.claude.json', content: '{"hasCompletedOnboarding":true,"hasTrustDialogAccepted":true,"hasTrustDialogHooksAccepted":true,"shiftEnterKeyBindingInstalled":true,"theme":"dark","numStartups":1,"opusProMigrationComplete":true,"sonnet1m45MigrationComplete":true,"projects":{"/root":{"allowedTools":[],"hasTrustDialogAccepted":true,"projectOnboardingSeenCount":1}}}' }, effective_value: { path: '/root/.claude.json', content: '{"hasCompletedOnboarding":true,"hasTrustDialogAccepted":true,"hasTrustDialogHooksAccepted":true,"shiftEnterKeyBindingInstalled":true,"theme":"dark","numStartups":1,"opusProMigrationComplete":true,"sonnet1m45MigrationComplete":true,"projects":{"/root":{"allowedTools":[],"hasTrustDialogAccepted":true,"projectOnboardingSeenCount":1}}}' }, enabled_by: 'ai.anthropic.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.anthropic.claude.credentials_json', category: 'Claude Code', name: 'Claude Code OAuth credentials', setting_type: 'file', description: 'Content for /root/.claude/.credentials.json. OAuth tokens for subscription-based auth (Pro/Max). Injected from host when detected.', default_value: { path: '/root/.claude/.credentials.json', content: '' }, effective_value: { path: '/root/.claude/.credentials.json', content: '' }, enabled_by: 'ai.anthropic.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.google.allow', category: 'Google AI', name: 'Allow Google AI', setting_type: 'bool', description: 'Enable API access to Google AI (*.googleapis.com).', default_value: true, effective_value: true, metadata: { domains: [], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: true, put: false, delete: false, other: false } } } }),
  ms({     id: 'ai.google.api_key', category: 'Google AI', name: 'Google AI API Key', setting_type: 'apikey', description: 'API key for Google AI. Injected as GEMINI_API_KEY env var.', default_value: '', effective_value: '', enabled_by: 'ai.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, docs_url: 'https://aistudio.google.com/apikey', prefix: 'AIza' } }),
  ms({     id: 'ai.google.domains', category: 'Google AI', name: 'Google AI Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: '*.googleapis.com', effective_value: '*.googleapis.com', enabled_by: 'ai.google.allow', enabled: false }),
  ms({     id: 'ai.google.gemini.settings_json', category: 'Gemini CLI', name: 'Gemini CLI settings.json', setting_type: 'file', description: 'Content for /root/.gemini/settings.json. Bypass permissions, disable telemetry/updates for sandboxed execution.', default_value: { path: '/root/.gemini/settings.json', content: '{"homeDirectoryWarningDismissed":true,"general":{"disableAutoUpdate":true,"disableUpdateNag":true},"ui":{"hideTips":true,"hideBanner":false},"privacy":{"usageStatisticsEnabled":false,"sessionRetention":"none"},"telemetry":{"enabled":false},"security":{"auth":{"selectedType":"gemini-api-key"},"folderTrust.enabled":false},"ide":{"hasSeenNudge":true},"tools":{"sandbox":false}}' }, effective_value: { path: '/root/.gemini/settings.json', content: '{"homeDirectoryWarningDismissed":true,"general":{"disableAutoUpdate":true,"disableUpdateNag":true},"ui":{"hideTips":true,"hideBanner":false},"privacy":{"usageStatisticsEnabled":false,"sessionRetention":"none"},"telemetry":{"enabled":false},"security":{"auth":{"selectedType":"gemini-api-key"},"folderTrust.enabled":false},"ide":{"hasSeenNudge":true},"tools":{"sandbox":false}}' }, enabled_by: 'ai.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.google.gemini.projects_json', category: 'Gemini CLI', name: 'Gemini CLI projects.json', setting_type: 'file', description: 'Content for /root/.gemini/projects.json. Project directory mappings.', default_value: { path: '/root/.gemini/projects.json', content: '{"projects":{"/root":"root"}}' }, effective_value: { path: '/root/.gemini/projects.json', content: '{"projects":{"/root":"root"}}' }, enabled_by: 'ai.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.google.gemini.trusted_folders_json', category: 'Gemini CLI', name: 'Gemini CLI trustedFolders.json', setting_type: 'file', description: 'Content for /root/.gemini/trustedFolders.json. Pre-trusted workspace dirs.', default_value: { path: '/root/.gemini/trustedFolders.json', content: '{"/root":"TRUST_FOLDER"}' }, effective_value: { path: '/root/.gemini/trustedFolders.json', content: '{"/root":"TRUST_FOLDER"}' }, enabled_by: 'ai.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.google.gemini.installation_id', category: 'Gemini CLI', name: 'Gemini CLI installation_id', setting_type: 'file', description: 'Content for /root/.gemini/installation_id. Stable UUID avoids first-run prompts.', default_value: { path: '/root/.gemini/installation_id', content: 'capsem-sandbox-00000000-0000-0000-0000-000000000000' }, effective_value: { path: '/root/.gemini/installation_id', content: 'capsem-sandbox-00000000-0000-0000-0000-000000000000' }, enabled_by: 'ai.google.allow', enabled: false }),
  ms({     id: 'ai.google.gemini.google_adc_json', category: 'Gemini CLI', name: 'Google Cloud ADC', setting_type: 'file', description: 'Content for /root/.config/gcloud/application_default_credentials.json. OAuth credentials for Google Cloud auth. Injected from host when detected.', default_value: { path: '/root/.config/gcloud/application_default_credentials.json', content: '' }, effective_value: { path: '/root/.config/gcloud/application_default_credentials.json', content: '' }, enabled_by: 'ai.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'json' } }),
  ms({     id: 'ai.openai.allow', category: 'OpenAI', name: 'Allow OpenAI', setting_type: 'bool', description: 'Enable API access to OpenAI (*.openai.com).', default_value: true, effective_value: true, metadata: { domains: [], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: true, put: false, delete: false, other: false } } } }),
  ms({     id: 'ai.openai.api_key', category: 'OpenAI', name: 'OpenAI API Key', setting_type: 'apikey', description: 'API key for OpenAI. Injected as OPENAI_API_KEY env var.', default_value: '', effective_value: '', enabled_by: 'ai.openai.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, docs_url: 'https://platform.openai.com/api-keys', prefix: 'sk-' } }),
  ms({     id: 'ai.openai.domains', category: 'OpenAI', name: 'OpenAI Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: '*.openai.com', effective_value: '*.openai.com', enabled_by: 'ai.openai.allow', enabled: false }),
  ms({     id: 'ai.openai.codex.config_toml', category: 'Codex CLI', name: 'Codex CLI config.toml', setting_type: 'file', description: 'Content for /root/.codex/config.toml. MCP servers, auth, etc.', default_value: { path: '/root/.codex/config.toml', content: '[mcp_servers.capsem]\ncommand = "/run/capsem-mcp-server"' }, effective_value: { path: '/root/.codex/config.toml', content: '[mcp_servers.capsem]\ncommand = "/run/capsem-mcp-server"' }, enabled_by: 'ai.openai.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'toml' } }),
  ms({     id: 'repository.git.identity.author_name', category: 'Git Identity', name: 'Author name', setting_type: 'text', description: 'Name used for git commits. Injected as GIT_AUTHOR_NAME and GIT_COMMITTER_NAME.', default_value: '', effective_value: '' }),
  ms({     id: 'repository.git.identity.author_email', category: 'Git Identity', name: 'Author email', setting_type: 'text', description: 'Email used for git commits. Injected as GIT_AUTHOR_EMAIL and GIT_COMMITTER_EMAIL.', default_value: '', effective_value: '' }),
  ms({     id: 'repository.providers.github.allow', category: 'GitHub', name: 'Allow GitHub', setting_type: 'bool', description: 'Enable access to GitHub and GitHub-hosted content.', default_value: true, effective_value: true, metadata: { domains: ['github.com', '*.github.com', '*.githubusercontent.com'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: true, put: false, delete: false, other: false } } } }),
  ms({     id: 'repository.providers.github.domains', category: 'GitHub', name: 'GitHub Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'github.com, *.github.com, *.githubusercontent.com', effective_value: 'github.com, *.github.com, *.githubusercontent.com', enabled_by: 'repository.providers.github.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'repository.providers.github.token', category: 'GitHub', name: 'GitHub Token', setting_type: 'apikey', description: 'Personal access token for git push over HTTPS. Injected into .git-credentials.', default_value: '', effective_value: '', enabled_by: 'repository.providers.github.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, docs_url: 'https://github.com/settings/tokens', prefix: 'ghp_' } }),
  ms({     id: 'repository.providers.gitlab.allow', category: 'GitLab', name: 'Allow GitLab', setting_type: 'bool', description: 'Enable access to GitLab and GitLab-hosted content.', default_value: false, effective_value: false, metadata: { domains: ['gitlab.com', '*.gitlab.com'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: true, put: false, delete: false, other: false } } } }),
  ms({     id: 'repository.providers.gitlab.domains', category: 'GitLab', name: 'GitLab Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'gitlab.com, *.gitlab.com', effective_value: 'gitlab.com, *.gitlab.com', enabled_by: 'repository.providers.gitlab.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'repository.providers.gitlab.token', category: 'GitLab', name: 'GitLab Token', setting_type: 'apikey', description: 'Personal access token for git push over HTTPS. Injected into .git-credentials.', default_value: '', effective_value: '', enabled_by: 'repository.providers.gitlab.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, docs_url: 'https://gitlab.com/-/user_settings/personal_access_tokens', prefix: 'glpat-' } }),
  ms({     id: 'security.web.allow_read', category: 'Web', name: 'Allow read requests', setting_type: 'bool', description: 'Allow GET/HEAD/OPTIONS for domains not in any allow/block list.', default_value: false, effective_value: false }),
  ms({     id: 'security.web.allow_write', category: 'Web', name: 'Allow write requests', setting_type: 'bool', description: 'Allow POST/PUT/DELETE/PATCH for domains not in any allow/block list.', default_value: false, effective_value: false }),
  ms({     id: 'security.web.custom_allow', category: 'Web', name: 'Allowed domains', setting_type: 'text', description: 'Comma-separated domain patterns to allow. Wildcards supported (*.example.com).', default_value: 'elie.net, *.elie.net, ash-speed.hetzner.com, en.wikipedia.org, *.wikipedia.org', effective_value: 'elie.net, *.elie.net, ash-speed.hetzner.com, en.wikipedia.org, *.wikipedia.org', metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.web.custom_block', category: 'Web', name: 'Blocked domains', setting_type: 'text', description: 'Comma-separated domain patterns to block. Takes priority over custom allow list.', default_value: '', effective_value: '', metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.search.google.allow', category: 'Google', name: 'Allow Google', setting_type: 'bool', description: 'Enable access to Google web search.', default_value: true, effective_value: true, metadata: { domains: ['www.google.com', 'google.com'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.search.google.domains', category: 'Google', name: 'Google Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'www.google.com, google.com', effective_value: 'www.google.com, google.com', enabled_by: 'security.services.search.google.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.search.bing.allow', category: 'Bing', name: 'Allow Bing', setting_type: 'bool', description: 'Enable access to Bing web search.', default_value: false, effective_value: false, metadata: { domains: ['www.bing.com', 'bing.com'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.search.bing.domains', category: 'Bing', name: 'Bing Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'www.bing.com, bing.com', effective_value: 'www.bing.com, bing.com', enabled_by: 'security.services.search.bing.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.search.duckduckgo.allow', category: 'DuckDuckGo', name: 'Allow DuckDuckGo', setting_type: 'bool', description: 'Enable access to DuckDuckGo web search.', default_value: false, effective_value: false, metadata: { domains: ['duckduckgo.com', '*.duckduckgo.com'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.search.duckduckgo.domains', category: 'DuckDuckGo', name: 'DuckDuckGo Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'duckduckgo.com, *.duckduckgo.com', effective_value: 'duckduckgo.com, *.duckduckgo.com', enabled_by: 'security.services.search.duckduckgo.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.registry.debian.allow', category: 'Debian', name: 'Allow Debian', setting_type: 'bool', description: 'Enable access to Debian.', default_value: true, effective_value: true, metadata: { domains: ['deb.debian.org', 'security.debian.org'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.registry.debian.domains', category: 'Debian', name: 'Debian Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'deb.debian.org, security.debian.org', effective_value: 'deb.debian.org, security.debian.org', enabled_by: 'security.services.registry.debian.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.registry.npm.allow', category: 'npm', name: 'Allow npm', setting_type: 'bool', description: 'Enable access to npm.', default_value: true, effective_value: true, metadata: { domains: ['registry.npmjs.org', '*.npmjs.org'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.registry.npm.domains', category: 'npm', name: 'npm Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'registry.npmjs.org, *.npmjs.org', effective_value: 'registry.npmjs.org, *.npmjs.org', enabled_by: 'security.services.registry.npm.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.registry.pypi.allow', category: 'PyPI', name: 'Allow PyPI', setting_type: 'bool', description: 'Enable access to PyPI.', default_value: true, effective_value: true, metadata: { domains: ['pypi.org', 'files.pythonhosted.org'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.registry.pypi.domains', category: 'PyPI', name: 'PyPI Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'pypi.org, files.pythonhosted.org', effective_value: 'pypi.org, files.pythonhosted.org', enabled_by: 'security.services.registry.pypi.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'security.services.registry.crates.allow', category: 'crates.io', name: 'Allow crates.io', setting_type: 'bool', description: 'Enable access to crates.io.', default_value: true, effective_value: true, metadata: { domains: ['crates.io', 'static.crates.io'], choices: [], min: null, max: null, rules: { default: { domains: [], path: null, get: true, post: false, put: false, delete: false, other: false } } } }),
  ms({     id: 'security.services.registry.crates.domains', category: 'crates.io', name: 'crates.io Domains', setting_type: 'text', description: 'Comma-separated domain patterns. Wildcards (*.example.com) match all subdomains.', default_value: 'crates.io, static.crates.io', effective_value: 'crates.io, static.crates.io', enabled_by: 'security.services.registry.crates.allow', enabled: false, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, format: 'domain_list' } }),
  ms({     id: 'vm.snapshots.auto_max', category: 'Snapshots', name: 'Auto snapshot limit', setting_type: 'number', description: 'Maximum number of automatic rolling snapshots.', default_value: 10, effective_value: 10, metadata: { domains: [], choices: [], min: 1, max: 50, rules: {  } } }),
  ms({     id: 'vm.snapshots.manual_max', category: 'Snapshots', name: 'Manual snapshot limit', setting_type: 'number', description: 'Maximum number of named manual snapshots.', default_value: 12, effective_value: 12, metadata: { domains: [], choices: [], min: 1, max: 50, rules: {  } } }),
  ms({     id: 'vm.snapshots.auto_interval', category: 'Snapshots', name: 'Auto snapshot interval', setting_type: 'number', description: 'Seconds between automatic snapshots.', default_value: 300, effective_value: 300, metadata: { domains: [], choices: [], min: 30, max: 3600, rules: {  } } }),
  ms({     id: 'vm.environment.shell.term', category: 'Shell', name: 'TERM', setting_type: 'text', description: 'Terminal type for the guest shell.', default_value: 'xterm-256color', effective_value: 'xterm-256color' }),
  ms({     id: 'vm.environment.shell.home', category: 'Shell', name: 'HOME', setting_type: 'text', description: 'Home directory for the guest shell.', default_value: '/root', effective_value: '/root' }),
  ms({     id: 'vm.environment.shell.path', category: 'Shell', name: 'PATH', setting_type: 'text', description: 'Executable search path for the guest shell.', default_value: '/opt/ai-clis/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', effective_value: '/opt/ai-clis/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' }),
  ms({     id: 'vm.environment.shell.lang', category: 'Shell', name: 'LANG', setting_type: 'text', description: 'Locale for the guest shell.', default_value: 'C', effective_value: 'C' }),
  ms({     id: 'vm.environment.shell.bashrc', category: 'Shell', name: 'Bash configuration', setting_type: 'file', description: 'User shell config sourced at login. Customize prompt, aliases, and functions.', default_value: { path: '/root/.bashrc', content: '# Prompt: green bold "capsem" with blue directory\nPS1=\'\\[\\033[1;32m\\]capsem\\[\\033[0m\\]:\\[\\033[1;34m\\]\\w\\[\\033[0m\\]\\$ \'\n\n# Aliases\nalias pip=\'uv pip\'\nalias pip3=\'uv pip\'\nalias python=\'uv run python\'\nalias python3=\'uv run python3\'\nalias gemini=\'gemini --yolo\'\nalias ls=\'ls --color=auto\'\nalias ll=\'ls -la --color=auto\'\nalias grep=\'grep --color=auto\'\n' }, effective_value: { path: '/root/.bashrc', content: '# Prompt: green bold "capsem" with blue directory\nPS1=\'\\[\\033[1;32m\\]capsem\\[\\033[0m\\]:\\[\\033[1;34m\\]\\w\\[\\033[0m\\]\\$ \'\n\n# Aliases\nalias pip=\'uv pip\'\nalias pip3=\'uv pip\'\nalias python=\'uv run python\'\nalias python3=\'uv run python3\'\nalias gemini=\'gemini --yolo\'\nalias ls=\'ls --color=auto\'\nalias ll=\'ls -la --color=auto\'\nalias grep=\'grep --color=auto\'\n' }, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'bash' } }),
  ms({     id: 'vm.environment.shell.tmux_conf', category: 'Shell', name: 'tmux configuration', setting_type: 'file', description: 'tmux terminal multiplexer config. Customize appearance, keybindings, and behavior.', default_value: { path: '/root/.tmux.conf', content: 'set -g default-terminal "tmux-256color"\nset -ag terminal-features ",xterm-256color:RGB"\nset -g mouse on\nset -g escape-time 0\nset -g history-limit 50000\nset -g status-style "bg=default,fg=colour8"\nset -g status-left ""\nset -g status-right ""\nset -g pane-border-style "fg=colour8"\nset -g pane-active-border-style "fg=colour4"\nset -g message-style "bg=default,fg=colour4"\n' }, effective_value: { path: '/root/.tmux.conf', content: 'set -g default-terminal "tmux-256color"\nset -ag terminal-features ",xterm-256color:RGB"\nset -g mouse on\nset -g escape-time 0\nset -g history-limit 50000\nset -g status-style "bg=default,fg=colour8"\nset -g status-left ""\nset -g status-right ""\nset -g pane-border-style "fg=colour8"\nset -g pane-active-border-style "fg=colour4"\nset -g message-style "bg=default,fg=colour4"\n' }, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, filetype: 'conf' } }),
  ms({     id: 'vm.environment.ssh.public_key', category: 'SSH', name: 'SSH public key', setting_type: 'text', description: 'Public key injected as /root/.ssh/authorized_keys in the guest VM.', default_value: '', effective_value: '' }),
  ms({     id: 'vm.environment.tls.ca_bundle', category: 'TLS', name: 'CA bundle path', setting_type: 'text', description: 'Path to the CA certificate bundle in the guest. Injected as REQUESTS_CA_BUNDLE, NODE_EXTRA_CA_CERTS, and SSL_CERT_FILE.', default_value: '/etc/ssl/certs/ca-certificates.crt', effective_value: '/etc/ssl/certs/ca-certificates.crt' }),
  ms({     id: 'vm.resources.cpu_count', category: 'Resources', name: 'CPU cores', setting_type: 'number', description: 'Number of CPU cores allocated to the VM.', default_value: 4, effective_value: 4, metadata: { domains: [], choices: [], min: 1, max: 8, rules: {  } } }),
  ms({     id: 'vm.resources.ram_gb', category: 'Resources', name: 'RAM', setting_type: 'number', description: 'Amount of RAM allocated to the VM in GB.', default_value: 4, effective_value: 4, metadata: { domains: [], choices: [], min: 1, max: 16, rules: {  } } }),
  ms({     id: 'vm.resources.scratch_disk_size_gb', category: 'Resources', name: 'Scratch disk size', setting_type: 'number', description: 'Size of the ephemeral scratch disk in GB.', default_value: 16, effective_value: 16, metadata: { domains: [], choices: [], min: 1, max: 128, rules: {  } } }),
  ms({     id: 'vm.resources.log_bodies', category: 'Resources', name: 'Log request bodies', setting_type: 'bool', description: 'Capture request/response bodies in telemetry.', default_value: false, effective_value: false }),
  ms({     id: 'vm.resources.max_body_capture', category: 'Resources', name: 'Max body capture', setting_type: 'number', description: 'Maximum bytes of body to capture in telemetry.', default_value: 4096, effective_value: 4096, metadata: { domains: [], choices: [], min: 0, max: 1048576, rules: {  } } }),
  ms({     id: 'vm.resources.retention_days', category: 'Resources', name: 'Session retention', setting_type: 'number', description: 'Number of days to retain session data.', default_value: 30, effective_value: 30, metadata: { domains: [], choices: [], min: 1, max: 365, rules: {  } } }),
  ms({     id: 'vm.resources.max_sessions', category: 'Resources', name: 'Maximum sessions', setting_type: 'number', description: 'Keep at most this many sessions (oldest culled first).', default_value: 100, effective_value: 100, metadata: { domains: [], choices: [], min: 1, max: 10000, rules: {  } } }),
  ms({     id: 'vm.resources.min_content_sessions', category: 'Resources', name: 'Minimum content sessions', setting_type: 'number', description: 'Always keep at least this many sessions that contain AI activity, regardless of age. Empty test sessions are terminated first.', default_value: 25, effective_value: 25, metadata: { domains: [], choices: [], min: 0, max: 1000, rules: {  }, step: 1 } }),
  ms({     id: 'vm.resources.max_disk_gb', category: 'Resources', name: 'Maximum disk usage', setting_type: 'number', description: 'Maximum total disk usage for all sessions in GB.', default_value: 100, effective_value: 100, metadata: { domains: [], choices: [], min: 1, max: 1000, rules: {  } } }),
  ms({     id: 'vm.resources.terminated_retention_days', category: 'Resources', name: 'Terminated session retention', setting_type: 'number', description: 'Days to keep terminated session records in the index. After this, the record is permanently deleted.', default_value: 365, effective_value: 365, metadata: { domains: [], choices: [], min: 30, max: 3650, rules: {  } } }),
  ms({     id: 'appearance.dark_mode', category: 'Appearance', name: 'Dark mode', setting_type: 'bool', description: 'Use dark color scheme in the UI.', default_value: true, effective_value: true, metadata: { domains: [], choices: [], min: null, max: null, rules: {  }, side_effect: 'toggle_theme' } }),
  ms({     id: 'appearance.font_size', category: 'Appearance', name: 'Font size', setting_type: 'number', description: 'Terminal font size in pixels.', default_value: 14, effective_value: 14, metadata: { domains: [], choices: [], min: 8, max: 32, rules: {  } } }),
];

/** Recompute `enabled` flags based on parent toggle values. */
export function recomputeEnabled() {
  const values = new Map<string, boolean>();
  for (const s of mockSettings) {
    if (typeof s.effective_value === 'boolean') {
      values.set(s.id, s.effective_value as boolean);
    }
  }
  for (const s of mockSettings) {
    if (s.enabled_by) {
      s.enabled = values.get(s.enabled_by) ?? false;
    }
  }
}

export function buildMockTree(): SettingsNode[] {
  return [
    { kind: 'group', enabled: true, key: 'app', name: 'App', description: 'Application settings', collapsed: false, children: [
      leaf(mockSettings.find(s => s.id === 'app.auto_update')!),
      { kind: 'action', key: 'app.check_update', name: 'Check for updates', description: 'Manually check if a new version is available', action: 'check_update' } as any,
    ]},
    { kind: 'group', enabled: true, key: 'ai', name: 'AI Providers', description: 'AI model provider configuration', collapsed: false, children: [
      { kind: 'group', enabled: true, key: 'ai.anthropic', name: 'Anthropic', description: 'Claude Code AI agent', enabled_by: 'ai.anthropic.allow', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'ai.anthropic.allow')!),
        leaf(mockSettings.find(s => s.id === 'ai.anthropic.api_key')!),
        leaf(mockSettings.find(s => s.id === 'ai.anthropic.domains')!),
        { kind: 'group', enabled: true, key: 'ai.anthropic.claude', name: 'Claude Code', description: 'Claude Code configuration files', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'ai.anthropic.claude.settings_json')!),
          leaf(mockSettings.find(s => s.id === 'ai.anthropic.claude.state_json')!),
          leaf(mockSettings.find(s => s.id === 'ai.anthropic.claude.credentials_json')!),
        ]},
      ]},
      { kind: 'group', enabled: true, key: 'ai.google', name: 'Google AI', description: 'Google Gemini AI provider', enabled_by: 'ai.google.allow', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'ai.google.allow')!),
        leaf(mockSettings.find(s => s.id === 'ai.google.api_key')!),
        leaf(mockSettings.find(s => s.id === 'ai.google.domains')!),
        { kind: 'group', enabled: true, key: 'ai.google.gemini', name: 'Gemini CLI', description: 'Gemini CLI configuration files', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'ai.google.gemini.settings_json')!),
          leaf(mockSettings.find(s => s.id === 'ai.google.gemini.projects_json')!),
          leaf(mockSettings.find(s => s.id === 'ai.google.gemini.trusted_folders_json')!),
          leaf(mockSettings.find(s => s.id === 'ai.google.gemini.installation_id')!),
          leaf(mockSettings.find(s => s.id === 'ai.google.gemini.google_adc_json')!),
        ]},
      ]},
      { kind: 'group', enabled: true, key: 'ai.openai', name: 'OpenAI', description: 'OpenAI API provider', enabled_by: 'ai.openai.allow', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'ai.openai.allow')!),
        leaf(mockSettings.find(s => s.id === 'ai.openai.api_key')!),
        leaf(mockSettings.find(s => s.id === 'ai.openai.domains')!),
        { kind: 'group', enabled: true, key: 'ai.openai.codex', name: 'Codex CLI', description: 'Codex CLI configuration files', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'ai.openai.codex.config_toml')!),
        ]},
      ]},
    ]},
    { kind: 'group', enabled: true, key: 'repository', name: 'Repositories', description: 'Code hosting and git configuration', collapsed: false, children: [
        { kind: 'group', enabled: true, key: 'repository.git.identity', name: 'Git Identity', description: 'Author name and email for commits inside the VM', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'repository.git.identity.author_name')!),
          leaf(mockSettings.find(s => s.id === 'repository.git.identity.author_email')!),
        ]},
      { kind: 'group', enabled: true, key: 'repository.providers', name: 'Providers', description: 'Code hosting platforms', collapsed: false, children: [
        { kind: 'group', enabled: true, key: 'repository.providers.github', name: 'GitHub', description: 'GitHub and GitHub-hosted content', enabled_by: 'repository.providers.github.allow', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'repository.providers.github.allow')!),
          leaf(mockSettings.find(s => s.id === 'repository.providers.github.domains')!),
          leaf(mockSettings.find(s => s.id === 'repository.providers.github.token')!),
        ]},
        { kind: 'group', enabled: true, key: 'repository.providers.gitlab', name: 'GitLab', description: 'GitLab and GitLab-hosted content', enabled_by: 'repository.providers.gitlab.allow', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'repository.providers.gitlab.allow')!),
          leaf(mockSettings.find(s => s.id === 'repository.providers.gitlab.domains')!),
          leaf(mockSettings.find(s => s.id === 'repository.providers.gitlab.token')!),
        ]},
      ]},
    ]},
    { kind: 'group', enabled: true, key: 'security', name: 'Security', description: 'Network access control, web services, and security presets', collapsed: false, children: [
      { kind: 'action', key: 'security.preset', name: 'Security Preset', description: 'Predefined security configurations', action: 'preset_select' } as any,
      { kind: 'group', enabled: true, key: 'security.web', name: 'Web', description: 'Default actions for unknown domains', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'security.web.allow_read')!),
        leaf(mockSettings.find(s => s.id === 'security.web.allow_write')!),
        leaf(mockSettings.find(s => s.id === 'security.web.custom_allow')!),
        leaf(mockSettings.find(s => s.id === 'security.web.custom_block')!),
      ]},
      { kind: 'group', enabled: true, key: 'security.services', name: 'Services', description: 'Search engines and package registries', collapsed: false, children: [
        { kind: 'group', enabled: true, key: 'security.services.search', name: 'Search Engines', description: 'Web search engine access', collapsed: false, children: [
          { kind: 'group', enabled: true, key: 'security.services.search.google', name: 'Google', description: 'Google web search', enabled_by: 'security.services.search.google.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.search.google.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.search.google.domains')!),
          ]},
          { kind: 'group', enabled: true, key: 'security.services.search.bing', name: 'Bing', description: 'Bing web search', enabled_by: 'security.services.search.bing.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.search.bing.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.search.bing.domains')!),
          ]},
          { kind: 'group', enabled: true, key: 'security.services.search.duckduckgo', name: 'DuckDuckGo', description: 'DuckDuckGo web search', enabled_by: 'security.services.search.duckduckgo.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.search.duckduckgo.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.search.duckduckgo.domains')!),
          ]},
        ]},
        { kind: 'group', enabled: true, key: 'security.services.registry', name: 'Package Registries', description: 'Package manager registries', collapsed: false, children: [
          { kind: 'group', enabled: true, key: 'security.services.registry.debian', name: 'Debian', description: 'Debian package registry', enabled_by: 'security.services.registry.debian.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.registry.debian.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.registry.debian.domains')!),
          ]},
          { kind: 'group', enabled: true, key: 'security.services.registry.npm', name: 'npm', description: 'npm package registry', enabled_by: 'security.services.registry.npm.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.registry.npm.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.registry.npm.domains')!),
          ]},
          { kind: 'group', enabled: true, key: 'security.services.registry.pypi', name: 'PyPI', description: 'PyPI package registry', enabled_by: 'security.services.registry.pypi.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.registry.pypi.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.registry.pypi.domains')!),
          ]},
          { kind: 'group', enabled: true, key: 'security.services.registry.crates', name: 'crates.io', description: 'crates.io package registry', enabled_by: 'security.services.registry.crates.allow', collapsed: false, children: [
            leaf(mockSettings.find(s => s.id === 'security.services.registry.crates.allow')!),
            leaf(mockSettings.find(s => s.id === 'security.services.registry.crates.domains')!),
          ]},
        ]},
      ]},
    ]},
    { kind: 'group', enabled: true, key: 'vm', name: 'VM', description: 'Virtual machine configuration', collapsed: false, children: [
      { kind: 'action', key: 'vm.rerun_wizard', name: 'Setup Wizard', description: 'Re-run the first-time setup wizard to reconfigure providers, repositories, and security.', action: 'rerun_wizard' } as any,
      { kind: 'group', enabled: true, key: 'vm.snapshots', name: 'Snapshots', description: 'Automatic and manual workspace snapshot settings', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'vm.snapshots.auto_max')!),
        leaf(mockSettings.find(s => s.id === 'vm.snapshots.manual_max')!),
        leaf(mockSettings.find(s => s.id === 'vm.snapshots.auto_interval')!),
      ]},
      { kind: 'group', enabled: true, key: 'vm.environment', name: 'Environment', description: 'Shell and environment variables', collapsed: false, children: [
        { kind: 'group', enabled: true, key: 'vm.environment.shell', name: 'Shell', description: 'Guest shell settings', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.term')!),
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.home')!),
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.path')!),
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.lang')!),
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.bashrc')!),
          leaf(mockSettings.find(s => s.id === 'vm.environment.shell.tmux_conf')!),
        ]},
        { kind: 'group', enabled: true, key: 'vm.environment.ssh', name: 'SSH', description: 'SSH key configuration', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'vm.environment.ssh.public_key')!),
        ]},
        { kind: 'group', enabled: true, key: 'vm.environment.tls', name: 'TLS', description: 'TLS certificate configuration', collapsed: false, children: [
          leaf(mockSettings.find(s => s.id === 'vm.environment.tls.ca_bundle')!),
        ]},
      ]},
      { kind: 'group', enabled: true, key: 'vm.resources', name: 'Resources', description: 'Hardware, telemetry, and session limits', collapsed: false, children: [
        leaf(mockSettings.find(s => s.id === 'vm.resources.cpu_count')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.ram_gb')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.scratch_disk_size_gb')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.log_bodies')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.max_body_capture')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.retention_days')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.max_sessions')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.min_content_sessions')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.max_disk_gb')!),
        leaf(mockSettings.find(s => s.id === 'vm.resources.terminated_retention_days')!),
      ]},
    ]},
    { kind: 'group', enabled: true, key: 'appearance', name: 'Appearance', description: 'UI appearance and display settings', collapsed: false, children: [
      leaf(mockSettings.find(s => s.id === 'appearance.dark_mode')!),
      leaf(mockSettings.find(s => s.id === 'appearance.font_size')!),
    ]},
  ];
}

// ---------------------------------------------------------------------------
// MCP mock data (generated from defaults.json + config/mcp-tools.json)
// ---------------------------------------------------------------------------

export let MOCK_MCP_SERVERS: McpServerInfo[] = [];

export let MOCK_MCP_TOOLS: McpToolInfo[] = [
  {
    namespaced_name: 'fetch_http',
    original_name: 'fetch_http',
    description: 'Fetch a URL and return its content. In \'markdown\' mode (default), HTML is converted to clean markdown preserving head...',
    server_name: 'builtin',
    annotations: { title: 'Fetch HTTP', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: true },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'grep_http',
    original_name: 'grep_http',
    description: 'Fetch a URL and search its content for a regex pattern (case-insensitive). By default, searches extracted text (HTML ...',
    server_name: 'builtin',
    annotations: { title: 'Grep HTTP', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: true },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'http_headers',
    original_name: 'http_headers',
    description: 'Return HTTP status code and response headers for a URL. By default uses HEAD (no body downloaded, faster). Set method...',
    server_name: 'builtin',
    annotations: { title: 'HTTP Headers', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: true },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_changes',
    original_name: 'snapshots_changes',
    description: 'List files that have changed in the workspace compared to automatic checkpoints. Each entry includes the file path, o...',
    server_name: 'builtin',
    annotations: { title: 'List changed files', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_list',
    original_name: 'snapshots_list',
    description: 'List all workspace snapshots (automatic and manual). Shows slot index, origin (auto/manual), name, age, blake3 hash, ...',
    server_name: 'builtin',
    annotations: { title: 'List snapshots', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_revert',
    original_name: 'snapshots_revert',
    description: 'Revert a file to its state at a specific checkpoint. Use the checkpoint ID from snapshots_changes output, or omit che...',
    server_name: 'builtin',
    annotations: { title: 'Revert file', read_only_hint: false, destructive_hint: true, idempotent_hint: true, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_create',
    original_name: 'snapshots_create',
    description: 'Create a named workspace snapshot (checkpoint). The snapshot captures the current state of all files and can be used ...',
    server_name: 'builtin',
    annotations: { title: 'Create snapshot', read_only_hint: false, destructive_hint: false, idempotent_hint: false, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_delete',
    original_name: 'snapshots_delete',
    description: 'Delete a manual snapshot by checkpoint ID. Only manual (named) snapshots can be deleted. Automatic snapshots are mana...',
    server_name: 'builtin',
    annotations: { title: 'Delete snapshot', read_only_hint: false, destructive_hint: true, idempotent_hint: true, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_history',
    original_name: 'snapshots_history',
    description: 'Show the history of a specific file across all snapshots. For each snapshot that contains a version of the file, show...',
    server_name: 'builtin',
    annotations: { title: 'File history', read_only_hint: true, destructive_hint: false, idempotent_hint: true, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
  {
    namespaced_name: 'snapshots_compact',
    original_name: 'snapshots_compact',
    description: 'Compact multiple snapshots into a single new manual snapshot. Merges workspaces with newest-file-wins strategy. Delet...',
    server_name: 'builtin',
    annotations: { title: 'Compact snapshots', read_only_hint: false, destructive_hint: true, idempotent_hint: false, open_world_hint: false },
    pin_hash: null,
    approved: true,
    pin_changed: false,
  },
];

export const MOCK_MCP_POLICY: McpPolicyInfo = {
  global_policy: 'allow',
  default_tool_permission: 'allow',
  blocked_servers: [],
  tool_permissions: {},
};
