name: Publish
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build
        run: uv build
      
      - name: Test
        run: uv run -m pytest
      
      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
